karma.conf.js

hook up coveralls

---

.travis.yml
karma.conf.js
packages/initiatives/package-lock.json
packages/initiatives/src/initiatives.ts
packages/initiatives/test/initiatives.test.ts
packages/sites/README.md
packages/sites/package-lock.json
packages/sites/package.json
packages/sites/src/index.ts
packages/sites/src/sites.ts
packages/sites/test/sites.test.ts
packages/sites/tsconfig.json

ISSUES CLOSED: #5 
80% sure i interpreted the instructions correctly.

feat(sites): add sites package (fetchDomain, fetchDomains)

---

packages/annotations/package-lock.json
packages/annotations/package.json
packages/annotations/src/annotations.ts
packages/annotations/test/annotations.test.ts
packages/annotations/test/mocks/anno_search.ts
packages/initiatives/package-lock.json
packages/sites/package-lock.json

```js
searchAnnotations({ url: `https://services.arcgis.com/bkrWlSKcjUDFDtgw/arcgis/rest/services/Hub%20Annotations/FeatureServer/0` })
response => 
{
features: [{
attributes: {
OBJECTID: 1,
author: "casey",
data: "this is where the comments go",
created_at: 1349395200000,
dataset_id: "sgj432",
Shape__Area: 1,
Shape__Length: 1
}
},
{
attributes: {
OBJECTID: 1,
author: "casey",
data: "this is where the comments go",
created_at: 1349395200001,
dataset_id: "xds466",
Shape__Area: 1,
Shape__Length: 1
}
},
{
attributes: {
OBJECTID: 1,
author: "casey",
data: "i like to hear myself talk",
created_at: 1349395200002,
dataset_id: "xds466",
Shape__Area: 1,
Shape__Length: 1
}
],
users: [{
username: "casey",
fullName: "Casey Jones",
firstName: "Casey",
lastName: "Jones",
description: "Neogeographer and …
```

decorate query results with user info

---

packages/annotations/src/add.ts
packages/annotations/test/crud.test.ts

enforce adding target field when creating new annos

---

docs/src/guides/from-a-cdn.md
docs/src/guides/node.md
support/publish.sh

(and fix publish script to point at the right GitHub org)

docs(cdn): update cdn sample to show that deps are external

---

package-lock.json
packages/solutions/README.md
packages/solutions/package-lock.json
packages/solutions/package.json
packages/solutions/src/index.ts
packages/solutions/src/solutions.ts
packages/solutions/test/solutions.test.ts
packages/solutions/tsconfig.json

just clearing the :golf: for @dbouwman.

stub in a new (empty) solutions package

---

packages/common/src/util.ts

I am not able to get my local copy to build due to #47, but here are the type changes I was going to suggest.

slightly less generic types for util fns

---

demos/oauth2-browser/package.json
docs/src/api/_declaration.html

fix bad links to raw source

---

docs/src/_layout.html
docs/src/guides/create-an-initiative.md
docs/src/guides/from-a-cdn.md
docs/src/guides/index.md
docs/src/guides/node.md
docs/src/guides/using-es6.md

implementing @tomwayson's _excellent_ suggestions.
ISSUES CLOSED: #72

docs(:book:): rename guide topic and other small tweaks

---

docs/src/api/_layout.html
docs/src/js/nav-toggle.js
docs/src/sass/style.scss
package.json

add nav-toggle

---

.travis.yml

used the travis cli to encrypt the slack token:
`travis encrypt "esri-webgis:SUPER-SECRET-TOKEN-HERE" --add notifications.slack`

chore: send travis notifications to slack

---

packages/events/package.json
packages/events/src/util.ts
packages/events/test/util.test.ts

util to convert event type to where clause

adding getEventQueryFromType util method

---

demos/oauth2-browser/package.json
packages/annotations/package-lock.json
packages/annotations/package.json
packages/annotations/src/add.ts
packages/annotations/src/delete.ts
packages/annotations/src/update.ts
packages/annotations/test/crud.test.ts
packages/auth/package-lock.json
packages/auth/package.json
packages/common/package-lock.json
packages/common/package.json
packages/domains/package-lock.json
packages/domains/package.json
packages/events/package-lock.json
packages/events/package.json
packages/initiatives/package-lock.json
packages/initiatives/package.json
packages/initiatives/test/groups.test.ts
packages/sites/package-lock.json
packages/solutions/package-lock.json

fix invalid semver ranges all over the place

---

package-lock.json
package.json
packages/annotations/src/search.ts
packages/annotations/test/create.test.ts
packages/annotations/test/crud.test.ts
packages/annotations/test/search.test.ts
packages/annotations/test/util.test.ts
packages/auth/test/auth.test.ts
packages/events/test/search.test.ts
packages/events/test/util.test.ts
packages/initiatives/src/migrations/upgrade-one-dot-one.ts
packages/initiatives/src/migrations/upgrade-two-dot-zero.ts
packages/initiatives/test/activate.test.ts
packages/initiatives/test/add.test.ts
packages/initiatives/test/geometry.test.ts
packages/initiatives/test/get.test.ts
packages/initiatives/test/migrator.ts
packages/initiatives/test/mocks/initiative-instance.ts
packages/initiatives/test/model.test.ts
packages/initiatives/test/search.test.ts
packages/initiatives/test/update.test.ts
packages/sites/test/sites.test.ts

and downgrade lerna to `v2.11.0` (luckily @tomwayson's release problem is _still_ fixed).
@esri/hub-auth
@esri/hub-events
resolves these:
```shell
$ npm run lint
> @esri/hub.js@1.7.2 lint /Users/john6251/github/hub.js
> tslint --project tsconfig.json 
ERROR: /Users/john6251/github/hub.js/packages/annotations/src/search.ts[9, 3]: 'IQueryResponse' is declared but its value is never read.
ERROR: /Users/john6251/github/hub.js/packages/annotations/test/create.test.ts[125, 5]: Promises must be handled appropriately
ERROR: /Users/john6251/github/hub.js/packages/annotations/test/create.test.ts[212, 5]: Promises must be handled appropriately
ERROR: /Users/john6251/github/hub.js/packages/annotations/test/create.test.ts[229 …
```

chore: lint for the TS 3.x lint gods

---

README.md

this is only a (codecov) test.

bump copyright year

---

packages/events/src/search.ts
packages/events/test/mocks/event_search.ts
packages/events/test/search.test.ts

fixes for bugs https://github.com/Esri/hub.js/issues/133 and https://github.com/Esri/hub.js/issues/135

missing auth for site query and switching to `searchItems`

---

support/changelog.js

port of https://github.com/Esri/arcgis-rest-js/pull/162
it was so long ago i forgot that i'd already solved the problem i was seeing.

ensure that CHANGELOG script generates valid diff urls

---

CONTRIBUTING.md
README.md

these could have helped @pranavkulkarni

surface a few more npm run dev examples

---

CHANGELOG.md
packages/common/src/index.ts

- expose getTypes and getCategories functions from hub-common

expose getTypes and getCategories

---

package-lock.json
packages/common/src/api.ts
packages/common/test/api.test.ts
packages/events/package.json
packages/events/src/util.ts

Addresses the issues @jPurush brought up in https://github.com/Esri/hub.js/pull/149#discussion_r277482573

fix getHubApiUrl() logic to clarify that it only works w/ AGO URLs

---

packages/initiatives/src/activate.ts

This is the first step of a larger set of changes... but is needed asap

When activating initiative, do not create an open-data group

---

packages/common/package-lock.json
packages/common/src/categories.ts

We want to show storymaps as "App"  on the list-card in the UI.
https://esriarlington.tpondemand.com/entity/91584-storymaps-items-show-up-as-app

add storymap to categories

---

packages/initiatives/src/migrator.ts

fix(bump initiative schema version): bump initiative schema version

---

packages/search/src/ago/helpers/filters/filter-schema.ts

supports categories and license filter
@esri/hub-search

feat(adds categories and license to filter schema)

---

packages/common/src/util.ts
packages/common/test/util.test.ts
packages/search/src/ago/helpers/filters/build-filter.ts
packages/search/src/ago/helpers/filters/create-filters.ts
packages/search/src/ago/helpers/filters/filter-schema.ts
packages/search/test/ago/helpers/filters/build-filter.test.ts

filter AGO items by modified date
@esri/hub-search

feat(filter-between-dates): filter AGO items by modified date

---

packages/search/src/ago/compute-items-facets.ts
packages/search/src/ago/helpers/aggs/categories.ts
packages/search/src/ago/helpers/aggs/create-aggs.ts
packages/search/src/ago/helpers/aggs/index.ts
packages/search/test/ago/compute-items-facets.test.ts
packages/search/test/ago/helpers/aggs/categories.test.ts

filter and aggregate by categories
@esri/hub-search

feat(categories): filter and aggregate by categories

---

package-lock.json
package.json
packages/common/src/items/index.ts
packages/common/src/items/interpolate-item-id.ts
packages/common/src/resources/_add-token-to-resource-url.ts
packages/common/src/resources/fetch-and-upload-thumbnail.ts
packages/common/src/resources/index.ts
packages/common/src/resources/upload-resources-from-url.ts
packages/common/src/types.ts
packages/common/test/extent/get-geographic-org-extent.test.ts
packages/common/test/extent/get-org-extent-as-bbox.test.ts
packages/common/test/i18n/get-culture.test.ts
packages/common/test/items/interpolate-item-id.test.ts
packages/common/test/resources/_add-token-to-resource-url.test.ts
packages/common/test/resources/convert-solution-template-resources-to-assets.test.ts
packages/common/test/resources/fetch-and-upload-thumbnail.test.ts
packages/common/test/resources/get-item-assets.test.ts
packages/common/test/resources/get-item-thumbnail-url.test.ts
packages/common/test/resources/upload-resources-from-url.test.ts
packages/initiatives/src/convert-initiative-to-template.ts
packages/initiatives/test/convert-initiative-to-template.test.ts

Issue: https://github.com/Esri/hub.js/issues/236
TP: [126869](https://esriarlington.tpondemand.com/entity/126869-chore-move-_more_-hub-utils)

chore move more hub utils

---

packages/common/src/i18n/fetch-hub-translation.ts
packages/common/src/items/serialize-model.ts
packages/common/src/objects/_deep-map-values.ts
packages/common/src/objects/deep-string-replace.ts
packages/common/src/resources/_which-blob/_is-node.ts
packages/common/src/resources/_which-blob/_which-blob.ts
packages/common/src/resources/_which-blob/index.ts
packages/common/src/resources/string-to-blob.ts
packages/common/test/resources/fetch-and-upload-resource.test.ts
packages/common/test/resources/fetch-and-upload-thumbnail.test.ts
packages/common/test/resources/fetch-image-as-blob.test.ts
packages/common/test/resources/string-to-blob.test.ts

- change imports to not use the `index` files - resolves some circular deps
- drop use of `util` and instead internalize some type check fns
~TODO: This still needs a resolution around `FetchBlob` as per #248~
Opted to drop "isomorphic" support for `Blob` as that was causing all manner of grief in UMD and (apparently) ESM builds

Solution.js Related Issues

---

packages/events/package.json
packages/initiatives/package.json
packages/sites/package.json
packages/solutions/package.json

@esri/hub-events
ISSUES CLOSED: #251

fix(peerDependencies): fix invalid peerDependencies

---

packages/common/package.json
packages/sites/src/teams/create-hub-team.ts
packages/sites/src/teams/create-hub-teams.ts

Removes un-used deps, and adds missing typings on two Teams functions

remove node-fetch, fetch-blob deps, add missing types

---

packages/sites/src/link-site-and-page.ts
packages/sites/test/link-site-and-page.test.ts

fix: linkSiteAndPage didn't account for old site items

---

support/publish.sh

Use force push in release script

---

packages/surveys/README.md

Just updates the README for `hub-surveys` package

1366998 - Update hub-surveys README

---

README.md
docs/src/api/_declaration.html
package-lock.json
package.json
packages/teams/README.md
packages/teams/package-lock.json
packages/teams/package.json
packages/teams/src/index.ts
packages/teams/src/teams.ts
packages/teams/test/teams.test.ts
packages/teams/tsconfig.json

As it says - just adds the "empty" package for teams.
Over time, we will migrate Team functionality currently in the sites package into this package.
Closes #285

Add Teams package, Fix Arrays in Doc

---

packages/sites/src/layout/convert-card.ts
packages/sites/src/layout/get-card-dependencies.ts
packages/sites/src/layout/types.ts
packages/sites/test/layout/convert-card.test.ts
packages/sites/test/layout/get-card-dependencies.test.ts

3 tasks
https://esriarlington.tpondemand.com/entity/140483-collaborator-no-longer-auto-templates-core
https://esriarlington.tpondemand.com/entity/123451-collaborator-autotemplates-app-from-sitepage-layout
https://esriarlington.tpondemand.com/entity/123452-collaborator-autotemplates-survey-from-sitepage-layout

Templating Fixes

---

packages/common/src/categories.ts
packages/common/test/content.test.ts
packages/search/package.json
packages/search/test/ago/encode-ago-query.test.ts
packages/search/test/ago/helpers/filters/collection.test.ts

Reverts Esri/hub.js#300 - See comments here: https://esriarlington.tpondemand.com/entity/138933-content-editor-can-pick-a-featured

Revert "c/141567 changed Hub Page and Site Page types to Site types from Document"

---

packages/common/src/request.ts
packages/common/test/request.test.ts
packages/content/src/hub.ts
packages/content/test/hub.test.ts

feat(request): add hubApiRequest() for making requests to the Hub API

---

packages/common/src/request.ts
packages/content/test/hub.test.ts

fix(hubApiRequest): url should include /api/v3

---

packages/common/src/urls/get-item-api-url.ts
packages/common/src/urls/get-item-data-url.ts

fix(getItemApiUrl): fix missing ?f=json

---

packages/downloads/src/portal/portal-request-dataset-export.ts
packages/downloads/src/request-dataset-export.ts
packages/downloads/test/portal/portal-request-dataset-export.test.ts
packages/downloads/test/request-dataset-export.test.ts

Adds support for a `where` filter on download requests using the Portal API.

Support where filter on portal downloads.

---

packages/content/src/portal.ts

fix(itemToContent()): handles empty extent

---

packages/common/src/resources/get-item-thumbnail-url.ts
packages/common/test/resources/get-item-thumbnail-url.test.ts

feat(getItemThumbnailUrl): add support for specifying width of thumbnail

---

packages/common/src/types.ts
packages/content/src/content.ts
packages/content/src/portal.ts
packages/content/test/content.test.ts
packages/content/test/portal.test.ts

fix(itemToContent): moved normalizedType generation to better spot

---

packages/common/src/request.ts
packages/content/src/hub.ts
packages/content/src/index.ts
packages/content/src/portal.ts
packages/content/src/slugs.ts

feat(slugs): expose isSlug, addContextToSlug, and removeContextFromSlug functions

---

packages/common/src/types.ts
packages/content/src/hub.ts
packages/content/src/portal.ts
packages/content/test/portal.test.ts

parsing item categories to match indexer logic

---

package-lock.json
packages/common/src/types.ts
packages/content/src/hub.ts
packages/content/src/portal.ts
packages/content/test/hub.test.ts
packages/content/test/portal.test.ts

affects: @esri/hub-common,  @esri/hub-content
continuation of the effort to address: #322
When in portal make an extra fetch to get the item's groups.

feat(getContent): return item group ids

---

packages/common/src/types.ts
packages/content/src/content.ts
packages/content/src/hub.ts
packages/content/src/portal.ts
packages/content/test/content.test.ts

affects: @esri/hub-common, @esri/hub-content
ISSUES CLOSED: 401

feat(getContent): ensure orgId for hub created content

---

package-lock.json
packages/sites/src/get-members.ts
packages/sites/src/index.ts
packages/sites/test/get-members.test.ts

add new getMembers function to allow authenticated and unauthenticated users to fetch a list of
members by username
[Related Issue](https://github.com/Esri/hub.js/issues/397)
future work:
- once the Hub API User Search is complete, we should integrate it into this function for AGO users 
and use the current implementation as a fallback for enterprise users
- extend or create a new function that supports full search of members, not just fetching by username

feat(hub-sites): add getMembers function

---

docs/src/guides/operation-stack.md
packages/common/src/OperationError.ts
packages/common/src/OperationStack.ts
packages/common/src/types.ts
packages/common/src/util.ts
packages/common/test/OperationError.test.ts
packages/common/test/OperationStack.test.ts
packages/common/test/util.test.ts

Adds:
- OperationStack & OperationError
- Operation Stack Doc
- last, uniqueBy, filterBy
Pulled from new Solution.js, but need here for use in sites package

Hoist OperationStack, OperationError and utils from Solution.js

---

packages/common/package-lock.json
packages/common/package.json

fix(common): fix umd build not bundling adlib

---

packages/content/src/hub.ts

…dLicense to content from dataset

fix(content): add structuredLicense to content from dataset

---

package-lock.json
packages/annotations/src/add.ts
packages/annotations/src/update.ts
packages/annotations/src/util.ts
packages/annotations/test/util.test.ts

affects: @esri/hub-annotations
ISSUES CLOSED: #430

fix(annotations): throw error when all adds or updates fail

---

package-lock.json
packages/content/src/hub.ts
packages/content/test/hub.test.ts
packages/content/test/mocks/datasets/feature-layer.json

feat: add contentStatus to datasetToItem

---

packages/downloads/src/portal/portal-export-success-handler.ts
packages/downloads/test/portal/portal-export-success-handler.test.ts

fix(@esri/hub-downloads): form data must use key typekeywords, not typeKeywords

---

docs/src/_layout.html
docs/src/api/_declaration.html

As it says - docs are already published w/ these changes

[DOC]: fix links to code and add GH link in header

---

package-lock.json
packages/annotations/package.json
packages/common/package.json
packages/content/package.json
packages/downloads/package.json
packages/initiatives/package.json
packages/search/package.json
packages/sites/package.json
packages/surveys/package.json
packages/teams/package.json

I think we should have the packages be on the same node version as the root of the project as described [here](https://docs.volta.sh/advanced/workspaces).

volta in packages should reference root package.json

---

package-lock.json
package.json
packages/common/src/objects/index.ts
packages/common/src/objects/set-prop.ts
packages/common/src/types.ts
packages/common/test/objects/set-prop.test.ts
packages/sites/src/_ensure-telemetry.ts
packages/sites/src/drafts/build-draft.ts
packages/sites/src/drafts/fetch-draft.ts
packages/sites/src/drafts/index.ts
packages/sites/src/drafts/site-draft-include-list.ts
packages/sites/src/drafts/upgrade-draft-schema.ts
packages/sites/src/update-site.ts
packages/sites/src/upgrade-site-schema.ts
packages/sites/test/_draft-model-1.3.ts
packages/sites/test/_ensure-telemetry.test.ts
packages/sites/test/drafts/fetch-draft.test.ts
packages/sites/test/drafts/upgrade-draft-schema.test.ts
packages/sites/test/historical-site-draft-schemas/1-3.ts
packages/sites/test/update-site.test.ts
packages/sites/test/upgrade-site-schema.test.ts

Implements solution 1 from https://github.com/Esri/hub.js/issues/498

draft schema migrations

---

packages/content/src/hub.ts

fix(content): prefer item extent from dataset

---

demos/ember-app/package.json
demos/node/package.json
demos/webpack/package.json
packages/annotations/package.json
packages/common/package.json
packages/content/package.json
packages/downloads/package.json
packages/events/package.json
packages/initiatives/package.json
packages/search/package.json
packages/sites/package.json
packages/surveys/package.json
packages/teams/package.json

Thanks to @MikeTschudi for noticing that our internal peerDependencies are out of date.

fix internal (hub.js) peerDependencies

---

packages/search/package-lock.json
packages/search/src/content/index.ts
packages/search/test/content/index.test.ts

affects: @esri/hub-search
My code was looking for the catalog at the wrong path and didn't properly point `fetchSite` at the right environment.
`npm t`
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/1475

fix(hub-search): fix catalog path, pass along portal URL

---

docs/src/guides/hub-discussions.md

adds guide for hub-discussions package https://github.com/Esri/hub.js/issues/572

docs(hub-discussions): adds hub-discussions guide

---

docs/src/guides/hub-discussions.md

docs(hub-discussions): incorporating feedback

---

demos/node/package-lock.json
package-lock.json
packages/teams/src/utils/index.ts

export `_search-teams` function

C/export _search-teams function

---

package-lock.json
packages/common/src/search/_searchGroups.ts
packages/common/src/urls/index.ts
packages/common/src/urls/upgrade-protocol.ts
packages/common/test/search/_searchGroups.test.ts
packages/common/test/urls/upgrade-protocol.test.ts

- _searchGroups fn now returns a site team url
- add upgradeProtocol function

feat: _searchGroups fn now return a site team url and add upgradeProtocol function

---

docs/src/guides/context.md
packages/common/src/ArcGISContext.ts
packages/common/src/ArcGISContextManager.ts
packages/common/test/ArcGISContextManager.test.ts

- add a guide for using ArcGISContext and ArcGISContextManager
- update jsdoc comments for both classes

docs: add guide and update jsdoc for context

---

package-lock.json
packages/discussions/src/types.ts

Adds a new `ChannelFilter` enum to `@esri/hub-discussions` that will be used to filter searches for posts to those that the current user has one or more posts.
Non functional
1. Closes Issues: [2262](https://devtopia.esri.com/dc/hub/issues/2262)
Used semantic release commit syntax

feat: add ChannelFilter type to discussions

---

packages/discussions/src/types.ts

feat(): export PostSort and ChannelSort

---

packages/common/src/search/types.ts

Add optional `accordionOpen` and `pageSize` to IFacet interface

feat(hub-common): add optional accordionOpen and pageSize to IFacet interface

---

packages/common/README.md

Force a Release b/c I borked things

feat: release HubSite and HubSiteManager

---

packages/common/src/sites/HubSites.ts

feat: force release

---

docs/src/guides/search-filters.md

Adds a Guide for working with `Filter`. Draft of this was reviewed in #743 

Search Filter Guide

---

package-lock.json
packages/common/src/content/_internal.ts
packages/common/test/content.test.ts

Part of https://devtopia.esri.com/dc/hub/issues/3339

fix(hub-common): fix additional resource logic to handle metadata props possibly being arrays

---

docs/src/guides/from-a-cdn.md

Update broken CDN example with new code, using ESM + Skypack
Paste example code int jsbin
1. Closes Issues: #<number>
Closes #770 

docs: update cdn example to use esm + skypack

---

packages/common/src/core/types/IHubTimeline.ts

- Remove `leadingElement` and `trailingElement` and make `isEditing` optional
- Replace `id` with `key`

fix(hub-common): IHubStage modifications

---

packages/initiatives/src/index.ts

export migrateSchema() from @esri/hub-initiatives
run tests
1. Closes Issues: [3554](https://devtopia.esri.com/dc/hub/issues/3554)

feat: export migrateSchema() from @esri/hub-initiatives

---

docs/src/guides/content-search.md
docs/src/guides/hub-entities.md
docs/src/guides/hub-search.md
packages/common/src/search/types/IHubCatalog.ts

- first cut of `hubSearch` guide
- IQuery, IFilter and IPredicate docs
- read docs when published?

docs: add hub-search docs

---

package-lock.json
packages/common/src/search/serializeQueryForPortal.ts
packages/common/test/projects/HubProjects.test.ts
packages/common/test/search/_internal/portalSearchGroups.test.ts
packages/common/test/search/_internal/portalSearchItems.test.ts
packages/common/test/search/_internal/portalSearchUsers.test.ts
packages/common/test/search/serializeQueryForPortal.test.ts

fix: predicates need to be wrapped in parens

---

packages/teams/src/utils/getOrgGroupLimit.ts
packages/teams/test/utils/can-user-create-team-in-product.test.ts

- swap customer orgids and add qa id
- get into ui, then we can test 

fix: swap customer orgids and add qa id

---

packages/discussions/src/types.ts

Adding support for acl when it comes to creating channels
Create a channel with ACL paramater
https://devtopia.esri.com/dc/hub/issues/4526

feat(hub-discussions): adding acl support for channels

---

packages/common/src/core/_internal/PropertyMapper.ts
packages/common/src/core/_internal/sharedWith.ts
packages/common/src/core/behaviors/IWithSharingBehavior.ts
packages/common/src/core/behaviors/index.ts
packages/common/src/core/types/types.ts
packages/common/src/projects/HubProject.ts
packages/common/test/core/_internal/sharedWith.test.ts
packages/common/test/projects/HubProject.test.ts

Adds `IWithSharingBehavior` interface, and implementation for `HubProject` class
- run tests

feat: add sharing behavior interface and implementation for project

---

package-lock.json
packages/common/src/urls/get-campaign-url.ts
packages/common/src/urls/index.ts
packages/common/test/urls/get-campaign-url.test.ts
packages/discussions/src/types.ts
packages/discussions/src/utils/posts.ts
packages/discussions/test/utils/posts.test.ts

[4624](https://devtopia.esri.com/dc/hub/issues/4624)

feat(hub-discussions): add parseMentionedUsers util

---

packages/common/src/projects/HubProjects.ts

Adds `timeline` to the PropertyMapper definition for `IHubProject`
- run tests
1. Closes Issues: #<number> (if appropriate) n/a

feat: add timeline to hubproject property mapper

---

package-lock.json
packages/common/src/urls/index.ts
packages/common/src/urls/is-safe-redirect-url.ts
packages/common/test/urls/is-safe-redirect-url.test.ts
packages/discussions/src/posts.ts
packages/discussions/src/types.ts
packages/discussions/test/posts.test.ts

* Adds `isSafeRedirectUrl` method in support of [4624](https://devtopia.esri.com/dc/hub/issues/4624)
- All tests pass
1. Closes Issues: #<4624> (if appropriate)

feat(): add isSafeRedirectUrl

---

package-lock.json
packages/discussions/src/utils/request.ts
packages/discussions/test/request.test.ts

[4624](https://devtopia.esri.com/dc/hub/issues/4624)
- Passes additional headers through to discussions requests
1. Closes Issues: #<4624> (if appropriate)

feat(): pass headers through createPost createReply and updatePost

---

package-lock.json
packages/common/src/core/schemas/hubproject.ts
packages/common/test/projects/HubProjects.test.ts

Update create project ui schema

feat: hub project create ui schema update

---

package-lock.json
packages/common/src/core/schemas/hubproject.ts

update the project `schema` & create/edit `uiSchema`s to support setting a project status 

feat: update project schemas to support status

---

packages/common/e2e/catalog-collection.e2e.ts
packages/common/src/content/HubContent.ts
packages/common/src/pages/HubPages.ts
packages/common/src/projects/HubProjects.ts
packages/common/src/search/Catalog.ts
packages/common/src/search/types/IHubSearchResult.ts
packages/common/src/search/types/types.ts
packages/common/src/sites/HubSites.ts
packages/common/test/search/Catalog.test.ts

Add `.contains(identifier, opts)` to `Catalog` class.
Issue [4867](https://devtopia.esri.com/dc/hub/issues/4867)
First step to implementing [Content Display Validation](https://devtopia.esri.com/dc/hub/issues/4802)
- run tests

feat: add catalog contains function

---

packages/common/src/sites/index.ts

2. 
Much 🤦🏼‍♂️ so 🤦🏼‍♂️
yeah...

fix: actually export HubSite class

---

package-lock.json
packages/discussions/src/index.ts
packages/discussions/src/utils/channels/can-post-to-channel.ts
packages/discussions/src/utils/constants.ts
packages/discussions/src/utils/posts.ts
packages/discussions/test/utils/posts.test.ts

- Implements `isDiscussable` in `discussions` package
1. Closes Issues: #4896 (if appropriate)

feat(): items can be designated as discussable

---

package-lock.json
packages/common/src/core/schemas/hubproject.ts

1. Description: Forgot to add helper text for featured image field.

fix: add helperText for featured image field

---

packages/sites/src/drafts/site-draft-include-list.ts

Adds telemetry properties to include list for saving a draft
1. (Helps) Close Issues: 4208

feat(): add telemetry to draft include list

---

package-lock.json
packages/common/src/content/_internal.ts
packages/common/test/content.test.ts

- Fix logic for initiative templates in getHubRelativeUrl
- Enhance logic for solutions in getHubRelativeUrl
- Add tests for above
1. Closes Issues: [5239](https://zentopia.esri.com/workspaces/collaboration-sprint-board-614f9bfc0946c40011ef574e/issues/dc/hub/5239)

fix(hub-common): fix logic and add tests for getHubRelativeUrl

---

.gitignore
.vscode/extensions.json
README.md

chore(hub-common): add recommended vscode extensions

---

package-lock.json

package.json and package-lock.json are apparently out of sync so the release gh action is failing

chore: update package-lock.json so release will work

---

package-lock.json

package.json and package-lock.json are apparently out of sync so the release gh action is failing

chore: update package-lock.json again so release will work

---

package-lock.json
packages/common/src/sites/_internal/_migrate-feed-config.ts
packages/common/src/sites/index.ts
packages/sites/src/drafts/upgrade-draft-schema.ts
packages/sites/test/drafts/upgrade-draft-schema.test.ts

1. Description: Updates upgradeDraftSchema to use most recent migration.
1. Closes Issues: #5935

feat(): draft schema migration update

---

packages/common/src/search/_internal/portalSearchItems.ts
packages/common/test/search/_internal/portalSearchItems.test.ts

Create a non-exported function which can be used to execute a portal search, using `IQuery`, but without processing the results into `IHubSearchResult` objects, leaving them as plain `IItem`s.
Ended up building a new function vs extending the return types on `portalSearchItems` as that would have been a type-breaking change, and ends up being messy to work with.
1. Closes Issues: #[6232](https://devtopia.esri.com/dc/hub/issues/6232) …

feat: add portalSearchItemsAsItems function

---

karma.conf.js
package-lock.json
packages/common/src/core/types/DynamicValues.ts
packages/common/src/core/types/index.ts
packages/common/src/search/_internal/combineQueries.ts
packages/common/src/search/_internal/portalSearchItems.ts
packages/common/src/utils/index.ts
packages/common/src/utils/internal/aggregateValues.ts
packages/common/src/utils/internal/resolveDynamicValue.ts
packages/common/src/utils/internal/resolveDynamicValues.ts
packages/common/src/utils/internal/resolveItemQueryValues.ts
packages/common/src/utils/internal/resolvePortalValues.ts
packages/common/src/utils/internal/resolveServiceQueryValues.ts
packages/common/src/utils/memoize.ts
packages/common/test/search/_internal/combineQueries.test.ts
packages/common/test/utils/internal/aggregateValues.test.ts
packages/common/test/utils/internal/resolveDynamicValue.test.ts
packages/common/test/utils/internal/resolveDynamicValues.test.ts
packages/common/test/utils/internal/resolveItemQueryValues.test.ts
packages/common/test/utils/internal/resolvePortalValues.test.ts
packages/common/test/utils/internal/resolveServiceQueryValues.test.ts
packages/common/test/utils/memoize.test.ts

Adds types and functions for dynamic value definition and resolution. This is the underlying subsystem that will power Metrics as well as run-time interpolation of layouts, and deploy time interpolation of templates
1. Closes Issues: #[6326](https://devtopia.esri.com/dc/hub/issues/6326)
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section …

feat: dynamic value implementation

---

README.md
packages/sites/src/ensure-required-site-properties.ts
packages/sites/test/ensure-required-site-properties.test.ts

Function `ensureRequiredSiteProperties` sets the capabilities in a model, deleting any capabilities already in the model. With this PR, the function ensures that the required properties are present without deleting capabilities that are not required.
Run unit tests
https://github.com/Esri/solution.js/issues/1050 …

feat: keep capabilities in model while ensuring default capabilities

---

packages/common/src/core/schemas/shared/subschemas.ts
packages/common/src/core/types/IHubProject.ts
packages/common/src/core/types/IHubTimeline.ts
packages/common/src/projects/_internal/ProjectSchema.ts
packages/common/src/projects/_internal/ProjectUiSchemaCreate.ts
packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts

[6897](https://devtopia.esri.com/dc/hub/issues/6897)
- add "onHold" as a status option to both projects and timeline stages
- add helper text to the location field on project creation (added to the project create uiSchema)
- hide the title and description fields of the timeline on project details (added to the project edit uiSchema)
- abstract and extend the timeline schema definition
1. [x] updated `peerDependencies` as …

feat: small project enhancements

---

package-lock.json
packages/common/src/capabilities/types.ts
packages/common/src/projects/_internal/ProjectBusinessRules.ts
packages/common/src/types.ts

1. Description: Adds metrics to project capability permissions …

feat: add metrics to project capability permissions

---

packages/common/src/content/edit.ts
packages/common/src/content/fetch.ts
packages/common/src/core/_internal/PropertyMapper.ts
packages/common/src/discussions/edit.ts
packages/common/src/discussions/fetch.ts
packages/common/src/initiatives/HubInitiatives.ts
packages/common/src/projects/edit.ts
packages/common/src/projects/fetch.ts
packages/common/src/sites/HubSite.ts
packages/common/src/sites/HubSites.ts
packages/common/test/content/edit.test.ts
packages/common/test/core/helpers/PropertyMapper.test.ts

Reverts Esri/hub.js#1098
blarg - last push failed... but I did not see it 🤦‍♂️

Revert "feat: make propertyMapper more generic"

---

package-lock.json
packages/common/src/core/HubItemEntity.ts
packages/common/test/core/HubItemEntity.test.ts

No issue, just a problem julianne and i noticed.

fix: include owner with setAccess

---

packages/common/src/sites/HubSites.ts
packages/common/test/sites/HubSites.test.ts

Issue - https://devtopia.esri.com/dc/hub/issues/7337
Fixes a couple saving issues with the `updateSite` logic
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section …

fix(hub-common): saving sites guarantees a unique slug and prevents field loss in site data

---

packages/common/src/capabilities/getWorkspaceCapabilities.ts

Adds the page capability permissions to the capability permissions list. 
1. Closes Issues: #7219 (if appropriate) …

fix(): add page capability permissions to capability permissions list

---

packages/common/src/users/index.ts

1. Description: I didin't export the darn thing...
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release instructions …

fix: actually export new function from index

---

packages/common/src/permissions/checkPermission.ts
packages/common/src/projects/_internal/ProjectBusinessRules.ts

No issue. I noticed that alpha permissions were not working.

fix: alpha permissions

---

packages/common/src/search/_internal/hubSearchChannels.ts
packages/common/test/search/_internal/hubSearchChannels.test.ts

1. Description: Adds support for searching by `Channel Name` and adds the ability to search my multiple `Channel Access` in the same search.
1. Closes Issues: 7411 …

feat(): search by channel name and multi access

---

packages/common/src/pages/HubPages.ts
packages/common/src/permissions/HubPermissionPolicies.ts

1. Description: Adds convertModelToPage function and updates temp:workspace:released permission

feat: convertModelToPage and update temp:workspace:released permission

---

packages/common/src/groups/_internal/enrichments.ts
packages/common/src/search/utils.ts
packages/common/src/sites/HubSites.ts
packages/common/src/sites/_internal/convertCatalogToLegacyFormat.ts
packages/common/test/groups/_internal/enrichments.test.ts
packages/common/test/mocks/portal-get-group/simple-response.json
packages/common/test/sites/HubSites.test.ts
packages/common/test/sites/_internal/convertCatalogToLegacyFormat.test.ts

Part of https://devtopia.esri.com/dc/hub/issues/7177

feat(hub-common): add user membership enrichment and have updateSite persist catalog changes

---

packages/common/src/groups/_internal/GroupBusinessRules.ts
packages/common/src/search/types/types.ts

- Change group members and content permissions to view
- Fix typo in `SortOption` …

fix: group permissions

---

docs/src/api/_declaration.html
docs/src/api/_layout.html

Just changes to doc generator files.

docs: add package version to toc

---

package-lock.json
packages/common/src/sites/HubSite.ts
packages/common/test/sites/HubSite.test.ts

Revert "fix: handle undefined context.portal"

---

.github/workflows/release.yml
package-lock.json
packages/common/src/sites/HubSite.ts
packages/common/test/sites/HubSite.test.ts

13.17.x patch

---

.github/workflows/release.yml
package-lock.json
packages/common/src/sites/HubSite.ts
packages/common/test/sites/HubSite.test.ts

Revert "13.17.x patch"

---

.github/workflows/release.yml
package-lock.json
packages/common/src/sites/HubSite.ts
packages/common/test/sites/HubSite.test.ts

fix: handle undefined context.portal

---

.github/workflows/release.yml
package.json
packages/common/src/sites/HubSite.ts
packages/common/test/sites/HubSite.test.ts

Revert "fix(hub-common): handle undefined context.portal"

---

packages/common/src/utils/poll.ts
packages/common/test/utils/poll.test.ts

- adds incremental delay to `poll` util to satisfy Portal API request

fix: add incremental delay and comments to polling util

---

package-lock.json
packages/common/src/core/schemas/index.ts
packages/common/src/core/schemas/shared/subschemas.ts

Updates privacy config schema for proper validation.

fix: update privacy config schema

---

package-lock.json

feat(hub-common): added rows to text area input

---

packages/common/src/core/schemas/internal/metrics/ProjectUiSchemaMetrics.ts
packages/common/src/core/schemas/internal/metrics/editorToMetric.ts
packages/common/src/core/types/Metrics.ts
packages/common/src/projects/HubProject.ts
packages/common/src/projects/_internal/ProjectSchema.ts
packages/common/test/core/schemas/internal/metrics/ProjectUiSchemaMetrics.test.ts
packages/common/test/core/schemas/internal/metrics/editorToMetric.test.ts
packages/common/test/projects/HubProject.test.ts

Updates projectSchema and ProjectMetricsUiSchema for creating metrics in the metrics pane. 
1. Closes Issues: [#6633](https://zentopia.esri.com/workspaces/collaboration-sprint-board-614f9bfc0946c40011ef574e/issues/dc/hub/6633)
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do …

feat(): update project schema/metricsUiSchema

---

packages/common/src/core/schemas/internal/subsetSchema.ts
packages/common/test/core/schemas/internal/filterSchemaToUiSchema.test.ts

fix(): update subsetSchema

---

packages/common/src/core/schemas/internal/metrics/StatCardUiSchema.ts
packages/common/test/core/schemas/internal/metrics/StatCardUiSchema.test.ts

1. Closes Issues: [#9123](https://devtopia.esri.com/dc/hub/issues/9123) …

fix(): explicitly say control for stat card uiSchema

---

package-lock.json
packages/common/src/content/_internal/ContentSchema.ts
packages/common/src/content/_internal/ContentUiSchemaSettings.ts
packages/common/src/content/_internal/getPropertyMap.ts
packages/common/src/core/types/IHubEditableContent.ts
packages/common/test/content/_internal/ContentUiSchemaSettings.test.ts
packages/common/test/content/fetch.test.ts

Part of https://devtopia.esri.com/dc/hub/issues/8957

feat(hub-common): remove hostedDownloads beta setting from content schemas / entity calculations

---

packages/common/src/core/schemas/internal/getCardEditorSchemas.ts

fix(): await uiSchema build

---

packages/common/src/surveys/utils/is-map-question.ts

1. Closes Issues: #[9539](https://devtopia.esri.com/dc/hub/issues/9539) …

feat(hub-common): update feedback util

---

packages/common/src/surveys/utils/get-s123-edit-url.ts
packages/common/src/surveys/utils/index.ts
packages/common/test/surveys/utils/get-s123-edit-url.test.ts

1. Closes Issues: #[9581](https://devtopia.esri.com/dc/hub/issues/9581) …

feat(hub-common): add get s123 edit url util

---

packages/common/src/content/fetchItemJobRecords.ts
packages/common/src/content/index.ts
packages/common/src/content/types.ts
packages/common/test/content/fetchItemJobRecords.test.ts

Part of https://devtopia.esri.com/dc/hub/issues/9626

feat(hub-common): add fetchItemJobRecords function

---

package-lock.json
packages/common/src/content/_internal/ContentBusinessRules.ts
packages/common/src/content/_internal/ContentUiSchemaSettings.ts

feat: alter feature flag for scheduler on content settings

---

package-lock.json

feat(hub-common): nested categories

---

package-lock.json
packages/common/src/core/types/ActionLinks.ts
packages/common/src/core/types/IHubEvent.ts
packages/common/src/events/_internal/PropertyMapper.ts
packages/common/test/events/_internal/PropertyMapper.test.ts

1. Description: Adds tooltips for entity hero action buttons.
1. Closes Issues: #9320 …

feat(hub-common): add register button tooltips

---

packages/common/src/core/schemas/internal/metrics/MetricSchema.ts
packages/common/src/core/schemas/internal/metrics/definitions.ts
packages/common/src/initiatives/_internal/InitiativeSchema.ts
packages/common/src/projects/_internal/ProjectSchema.ts

fix(): update schema

---

package-lock.json
packages/common/src/permissions/HubPermissionPolicies.ts
packages/common/src/permissions/types/Permission.ts
packages/common/src/projects/_internal/ProjectBusinessRules.ts

1. Description: Adds new env permissions and slight tweaks to projects initiative workspace/tab permissions. …

feat: new env permissions && permission tweaks

---

package-lock.json
packages/common/src/core/types/IHubEvent.ts
packages/common/src/events/_internal/EventSchemaEdit.ts
packages/common/src/events/_internal/EventUiSchemaEdit.ts
packages/common/src/events/_internal/PropertyMapper.ts
packages/common/src/events/_internal/validations.ts
packages/common/src/events/defaults.ts
packages/common/src/events/edit.ts
packages/common/src/events/types.ts
packages/common/test/events/_internal/EventSchemaEdit.test.ts
packages/common/test/events/_internal/EventUiSchemaEdit.test.ts
packages/common/test/events/_internal/PropertyMapper.test.ts
packages/common/test/events/defaults.test.ts
packages/common/test/events/edit.test.ts

1. Description: Adds location picker to events.
1. Closes Issues: #10088

feat(hub-common): add events location picker

---

packages/common/src/events/api/orval/api/orval-events.ts

fix(hub-common): update event location type

---

packages/common/src/events/api/orval/api/orval-events.ts

feat(hub-common): add event capabilities field

---

packages/common/src/core/types/IHubEvent.ts
packages/common/src/events/_internal/PropertyMapper.ts
packages/common/src/events/_internal/getPropertyMap.ts
packages/common/test/events/_internal/PropertyMapper.test.ts
packages/common/test/events/edit.test.ts
packages/common/test/events/fetch.test.ts

feat(hub-common): add registration count props

---

packages/common/src/core/schemas/internal/metrics/InitiativeUiSchemaMetrics.ts
packages/common/src/core/schemas/internal/metrics/ProjectUiSchemaMetrics.ts
packages/common/test/core/schemas/internal/metrics/ProjectUiSchemaMetrics.test.ts

fix(): update uiSchemas

---

packages/common/src/core/schemas/types.ts

feat(): add notice type to uiSchemaElementTypes

---

packages/common/src/core/schemas/internal/events/EventGalleryCardSchema.ts

1. Description: Adds calendar layout option to event gallery card.
1. Closes Issues: #10963 …

feat(hub-common): add calendar layout option

---

packages/common/src/users/_internal/UserBusinessRules.ts

- Remove alpha gating from user Content & Groups panes
- Remove un-used `hub:user:workspace:shared-with-me` permission …

feat: remove alpha gating of user content and groups panes

---

packages/common/README.md

BREAKING CHANGE: force release of earlier breaking change commits
Just trying to force sematic release to run

feat: update readme with details on breaking changes

---

packages/common/src/index.ts

BREAKING CHANGE: removed association functions; minor changes to a few interfaces

feat: minor comment change in ts file to try to force release to run

---

package-lock.json
packages/common/src/discussions/utils.ts
packages/common/test/discussions/utils.test.ts

1. Description: Adds helper function for determining CSV download file name.
1. Closes Issues: #11042 …

feat(hub-common): add csv file name function

---

packages/common/src/core/schemas/shared/CatalogSchema.ts

Updates the catalog schemas to include appearance settings. …

fix(): update correct schemas for catalog editing

---

packages/common/src/core/schemas/shared/CatalogSchema.ts

Revert "fix(): update correct schemas for catalog editing"

---

packages/common/src/urls/hub-cdn-urlmap.ts
packages/common/test/urls/get-hub-locale-asset-url.test.ts

No issue, site creation is failing on qa because we hard-coded our cdn buckets.

fix: fix hub_cdn_urls

---

packages/common/src/events/api/events.ts
packages/common/src/events/api/orval/api/orval-events.ts
packages/common/src/events/api/types.ts
packages/common/test/events/api/events.test.ts

Issue https://devtopia.esri.com/dc/hub/issues/12177
1. Description: add function `searchEvents` to hub-common for events3 …

feat(hub-common): add searchEvents function

---

packages/common/src/sites/_internal/applyDefaultCollectionMigration.ts

BREAKING CHANGE: removes deprecated functions

feat: remove deprecated functions

---

packages/common/src/core/schemas/types.ts

- [12660](https://devtopia.esri.com/dc/hub/issues/12660)
Adds new "Text" `UiSchemaElementType` to support inline text in the configuration editor …

feat: add new Text UiSchemaElementType

---

packages/common/src/users/_internal/UserBusinessRules.ts

1. Description: Gates events pane in user workspace to premium users.
1. Closes Issues: #12970
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release instructions …

fix(hub-common): gate events pane to premium users

---

packages/common/src/utils/get-hub-product.ts

Purely used to force a breaking change release, when we merge this PR

fix: lint error; will be used to force breaking change
