packages/annotations/package.json, packages/common-types/package.json, packages/initiatives/package.json, packages/sites/package.json, umd-base-profile.js
=> fix(all): treat arcigs-rest-js packages as external and bump to latest

CHANGELOG.md, packages/common/src/util.ts, packages/common/test/util.test.ts
This is supported `findBy(someArray, 'deep.nested.prop', 'foo');`
Includes a test.
Made with ❤️ in Fort Collins, Colorado
=> findBy supports deep dotting

packages/annotations/README.md, packages/annotations/package-lock.json, packages/annotations/src/add.ts, packages/annotations/src/delete.ts, packages/annotations/src/search.ts, packages/annotations/src/update.ts, packages/auth/package-lock.json, packages/common/package-lock.json, packages/initiatives/package-lock.json, packages/sites/package-lock.json, packages/solutions/package-lock.json
Added examples - but before merging I would like to discuss simple improvements to the method signatures that exposes less of the implementation.
- Directly use the `annotationsUrl` without requiring adding a layer index `+ '/0'`
- Remove redundant parameter names `addAnnotations({adds: [...]})`
- Make Delete consistent with updates and add 
- `addAnnotations({annotations: [{attributes: {description: "Kinda Awesome!"}]})`
- `updateAnnotations({annotations: [{attributes: {OBJECTID: 1, description: "More Awesomer!"}]})`
- `deleteAnnotations({annotations: [{attributes: {OBJECTID: 1}]})`
=> Added examples for simple Annotation CRUD

CHANGELOG.md, packages/annotations/package.json, packages/auth/package.json, packages/common/package.json, packages/domains/package.json, packages/initiatives/package.json, packages/sites/package.json, packages/solutions/package.json
@esri/hub-auth
@esri/hub-domains
=> chore(**/package.json): bump ArcGIS Rest Js

packages/initiatives/src/get.ts, packages/sites/README.md, packages/sites/src/sites.ts, packages/sites/test/sites.test.ts
deprecate old fns and remove from docs
ISSUES CLOSED: #60
=> refactor(sites): rename fetchDomain(s) to getDomain(s)

README.md, package.json, packages/annotations/package.json, packages/auth/package.json, packages/common/package.json, packages/domains/package.json, packages/initiatives/package.json, packages/sites/package.json, packages/solutions/package.json, support/dev.sh
added `dev:esm`, `dev:umd`, and `dev:node` scripts for initiative package (only, so far).
You can run `lerna run dev:esm --parallel` and `tsc` will launch in watch mode and recompile the ESM output instantly whenver you change the TS source for the initiatives package. 🎉 
But of course, the one we care about, `lerna run dev:umd --parallel`, does not work. I get this output:
```bash
➜  hub.js git:(chore/dist-scripts) lerna run dev:umd --parallel
lerna info version 2.8.0
lerna info run in 1 package(s): npm run dev:umd
@esri/hub-initiatives: > @esri/hub-initiatives@1.3.0 dev:umd /Users/tom/code/hub.js/packages/initiatives
@esri/hub-initiatives: > rollup -w -c ../../umd-base-profile.js
@esri/hub-initiatives: rollup v0.53.4
@esri/hub-initiatives: bundles ./src/index.ts → …
```
=> add dev scripts to watch a specific package and run a specific build

.travis.yml
`travis_retry` allegedly retries a failed command 3 times:
https://docs.travis-ci.com/user/common-build-problems/#travis_retry
=> chore(ci): retry tests on failure

package-lock.json, packages/annotations/src/create.ts, packages/annotations/src/layer-definition.ts, packages/annotations/src/search.ts, packages/annotations/test/create.test.ts, packages/annotations/test/search.ts
the tweaks above ensure the following capabilities are set on new hosted annotation services:
i dont know what this one even means, and whats more, i just wasted 4 hours of my life unintentionally confirming that setting it breaks _everything_:
to put it another way, i have confirmed manually that the settings here ensure the following
1. anonymous users can **only add** new features
2. named users can add new features **and** update their own features
3. organization administrators (and i assume those with special privileges) **can update** comments from other named users
3. **no one** can delete features
4. the service is appropriately protected from accidental deletion
=> fix: ensure editor tracking is wired up correctly in new anno services

CHANGELOG.md
doesn't _look_ like a problem in `support/changelog.js`. i _think_ it was a one-off thing.
=> fix bad links in changelog

docs/src/guides/create-an-initiative.md, docs/src/guides/index.md, docs/src/guides/work-with-annotations.md, packages/annotations/src/add.ts, packages/annotations/src/update.ts, packages/annotations/test/crud.test.ts
while i was in there i realized that the code i wrote previously for tacking on the 'author' attribute in annotation CRUD functions needed to be removed.
`created_at`, `updated_at`, `author` and `updater` are all managed by the server when editor tracking is enabled.
=> add guide for working with annotation services

CHANGELOG.md, packages/initiatives/src/remove.ts
Updated the removeInitiative function to always construct the url using the item owner's username. This allows an admin to delete an initiative they don't own
=> Ensure we use the owner url when deleting initiative items

.travis.yml, docs/src/guides/work-with-annotations.md, packages/annotations/src/add.ts, packages/annotations/src/create.ts, packages/annotations/src/delete.ts, packages/annotations/src/index.ts, packages/annotations/src/layer-definition.ts, packages/annotations/src/search.ts, packages/annotations/src/update.ts, packages/annotations/src/vote.ts, packages/annotations/test/create.test.ts, packages/annotations/test/mocks/anno_search.ts, packages/annotations/test/vote.test.ts
resolves #110 
```js
const orgId = "uCX...";
const authentication = new arcgisRest.UserSession({ username, password })
const serviceUrl = await arcgisHub.getAnnotationServiceUrl(orgId)
const url = `${serviceUrl}/0`;
const searchResponse = await arcgisHub.searchAnnotations({
url,
where: "OBJECTID = 1"
});
arcgisHub.voteOnAnnotation({
url,
authentication,
annotation: searchResponse.data[0],
downVote: true
});
```
to do:
-  [x] tests e5fddb3
=> add support for annotation voting

packages/common/src/util.ts, packages/common/test/util.test.ts
Once you see how this works, you will ask yourself... "Self, how have I lived without this?"
Ok, maybe it's not that awesome, but in Hub-land we do a LOT of data manipulation, and that involves a lot of checking if some deep-nested-property exists, and if to, grabbing it's value and pushing it into another object, or into an array.
`maybeAdd` allows us to drop a lot of the `if(valueExists) { pushValueIntoArray }` code.
Instead we can just 
```js
let ids =[];
ids = maybeAdd(ids, getProp(model, 'item.id'));
ids = maybeAdd(ids, getProp(model, 'item.properties.serviceId'));
ids = maybeAdd(ids, getProp(model, 'item.data.values.webmap'));
```
or get super cool and use it in a reduce...
```js
const ids = ['item.id', 'item.properties.sourceServiceId', 'data.values.webmap'].reduce((acc, key) => { …
```
=> Add maybeAdd util fn

packages/annotations/src/search.ts, packages/annotations/test/search.test.ts
fixing incorrect where clause construction in `searchAllAnnotationVotes`. 
This is the fix for issue [122](https://github.com/Esri/hub.js/issues/122)
=> Invalid `where` parameter fix

docs/src/_layout.html, packages/annotations/src/layer-definition.ts, packages/annotations/src/search.ts, packages/annotations/src/vote.ts, packages/annotations/test/mocks/anno_search.ts, packages/annotations/test/search.test.ts, packages/annotations/test/vote.test.ts
* ensure that upvotes and downvotes aren't returned by search
* replace fieldname `value` with `vote`
* ensure that users can delete their own vote
* more descriptive `<meta>` tag in docs
@lisastaehli let me know if the second item in the list above is problematic. if you don't want to blow away your existing service entirely you should be able to add `vote` as an additional field in the ArcGIS Online UI. i'm happy to help if you run into any trouble.
RESOLVES:
#123, #124, #125, #118
=> fix: value > vote, loosen delete protection, omit votes from search

demos/oauth2-browser/package-lock.json, package-lock.json, packages/annotations/package-lock.json, packages/annotations/package.json, packages/auth/package-lock.json, packages/auth/package.json, packages/common/package-lock.json, packages/common/package.json, packages/domains/package-lock.json, packages/domains/package.json, packages/events/package-lock.json, packages/events/package.json, packages/initiatives/package-lock.json, packages/initiatives/package.json, packages/sites/package-lock.json, packages/sites/package.json, packages/solutions/package-lock.json, packages/solutions/package.json
today @jPurush learned (the painful way) that in her TypeScript project, webpack was bundling the `/umd`s.
more info: https://github.com/Esri/arcgis-rest-js/pull/421#issuecomment-448706802
@esri/hub-oauth-demo
@esri/hub-auth
@esri/hub-domains
@esri/hub-events
=> refactor: pkg.browser > pkg.unpkg

packages/auth/package.json
=> fix: fix auth filename in pkg to ensure the umd can be retrieved in observable etc.

packages/initiatives/package-lock.json, packages/initiatives/package.json, packages/initiatives/src/follow.ts, packages/initiatives/src/groups.ts, packages/initiatives/src/index.ts, packages/initiatives/test/follow.test.ts
resolves https://github.com/esridc/hub-components/issues/1
=> Feat: new methods for users to follow and unfollow initiatives

packages/annotations/package.json, packages/auth/package.json, packages/common/package.json, packages/domains/package.json, packages/events/package.json, packages/initiatives/package.json, packages/sites/package.json, packages/solutions/package.json
analogous to https://github.com/Esri/arcgis-rest-js/pull/490
@esri/hub-auth
@esri/hub-domains
@esri/hub-events
=> feat(tree): advertise sideEffect free code to webpack

packages/events/src/util.ts, packages/events/test/util.test.ts
Refactored `getEventServiceUrl` to add a new function `getEventServiceItems` in order for [hub-indexer](https://github.com/ArcGIS/hub-indexer/blob/9677cf6f94d61cc941bb86425963998f27e13f08/packages/api/middleware/events-fetch-feature-service.js#L18) to be able to get the public feature service url.
=> first pass at function to get event service item

packages/annotations/src/search.ts, packages/annotations/src/vote.ts, packages/events/src/register.ts, packages/initiatives/src/follow.ts
fixing the doc made it clearer that we still needed to rename a couple interfaces.
`ISearchAnnoRequestOptions` > `ISearchAnnoOptions`
`IVoteRequestOptions` > `IVoteOptions`
`IEventRegisterRequestOptions` > `IEventRegisterOptions`
`IFollowInitiativeRequestOptions` > `IFollowInitiativeOptions`
if there is anything else we want to hide/rename, speak now or forever hold your peace.
=> remove 'Request' from all extended RequestOption interfaces

CHANGELOG.md, docs/build-typedoc.js, packages/search/package-lock.json, packages/search/src/ago/compute-items-facets.ts, packages/search/src/ago/encode-ago-query.ts, packages/search/src/ago/get-items.ts, packages/search/src/ago/helpers/filters/encode-params.ts, packages/search/src/ago/helpers/filters/index.ts, packages/search/src/ago/params.ts, packages/search/src/ago/search.ts, packages/search/src/ago/serialize.ts, packages/search/test/ago/compute-items-facets.test.ts, packages/search/test/ago/get-items.test.ts, packages/search/test/ago/helpers/filters/encode-params.test.ts, packages/search/test/ago/search.test.ts, packages/search/test/ago/serialize.test.ts
In this PR --
1. Developed an algorithm to encode urls cleanly in serialize function. The crux of the algorithm is to handle filters and non-filters differently. It can URI encode any nested object like `{ a: { b: 2 }, c: 3 }` as `a[b]=2&c=3`
2. Removed circular dependency in computeItemsFacets function. I have addressed it by creating a `get-items` module shared between `agoSearch` and `computeItemsFacets`.
3. Fixed a bug wherein a blank string `""` didn't construct AGO query properly. So I have added a check in place for that.
=> search improvements

packages/search/README.md, packages/search/src/ago/helpers/filters/filter-schema.ts, packages/search/test/ago/serialize.test.ts
Recently orgId and initiativeId were added to catalog param schema in the opendata-ui legacy search (https://github.com/ArcGIS/opendata-ui/blob/master/packages/opendata-ui/app/utils/search/create-filters.js#L106). With unified search, that logic needs to be added in hub.js.
Sites with orgId and initiativeId work with this new change --
=> add orgId and initiativeId in filterSchema to add them to catalog

packages/common/package-lock.json, packages/initiatives/package-lock.json, packages/search/package-lock.json, packages/search/src/ago/helpers/filters/build-filter.ts, packages/search/src/ago/helpers/filters/filter-schema.ts, packages/search/test/ago/helpers/filters/build-filter.test.ts, packages/search/test/ago/serialize.test.ts
Recently some changes were made to legacy search in opendata-ui. They need to be in hub.js because unified search is now generally available. This PR makes the corresponding changes of lowercasing ago param keys to accommodate `search by orgId` for special hub home sites. Reference: https://github.com/ArcGIS/opendata-ui/blob/master/packages/opendata-ui/app/utils/search/encode-ago-query.js#L92
With this change, the below special hub home site returns results based on orgId!
=> fix(lowercase ago param keys): lowercase ago param keys

packages/search/src/ago/encode-ago-query.ts, packages/search/test/ago/encode-ago-query.test.ts
Give the ability to search for public content by removing the default -access public.
pass {restricted: true} to add it back
=> feat(search): use restricted option to scope search

package-lock.json, packages/initiatives/package-lock.json, packages/initiatives/src/activate.ts, packages/initiatives/src/groups.ts, packages/initiatives/src/templates.ts, packages/initiatives/src/util.ts, packages/initiatives/test/activate.test.ts, packages/initiatives/test/groups.test.ts, packages/initiatives/test/templates.test.ts, packages/initiatives/test/util.test.ts
This refactor creates a new orchestration method for creating the two groups required for activating an initiative so that it can handle users who do not have all the privs necessary to create
groups. It also allows activateInitiative to activate an embedded initiative by adding support for copying embedded image resources to AGO.
ISSUES CLOSED: #145
=> Create blank initiative

packages/search/src/ago/encode-ago-query.ts, packages/search/src/ago/helpers/filters/create-filters.ts, packages/search/test/ago/encode-ago-query.test.ts
support generating a correct filter from any key in ISearchParams
```
e.g. 
{
tags: 'water',
q: 'air'
}
-> q="air AND tags:water"
```
=> feat(search) support filters specified implicitly

packages/search/src/ago/helpers/filters/handle-filter.ts, packages/search/test/ago/encode-ago-query.test.ts, packages/search/test/ago/helpers/filters/handle-filter.test.ts
when searhcing for thigns tagged "tres" and things of type "web map", the generated query should be "type: web map AND tags: trees"
currently they ared ORed together so you get thigns that are web maps or trees
=> fix(search): multiple filters should be ANDed together

packages/search/src/ago/helpers/format/format-item.ts, packages/search/test/ago/helpers/format/format-item.test.ts
item extents are now formatted as from the Hub API
```js
{
type: 'envelope',
coordinates: [ [1,2], [3,4] ]
}
```
=> fix(search): format item extent properly

CHANGELOG.md, packages/common/src/util.ts, packages/common/test/util.test.ts
Implements extend in \`hub-common\`, which extends a target object with props from a source object, overwriting identically named props in target with those from source. Ignores null and undefined
values, similar to $.extend.
=> feat(implement extend in hub-common): implement extend

package-lock.json, packages/common/src/util.ts, packages/common/test/util.test.ts, packages/search/package-lock.json, packages/search/package.json, packages/search/src/ago/get-items.ts, packages/search/test/ago/get-items.test.ts
AGO supports max 3 countFields in a request. Hub search should send multiple requests for countFields > 3, collect responses and return
@esri/hub-search
=> feat(support-more-than-3-countFields): support-more-than-3-countFields

packages/initiatives/package-lock.json, packages/initiatives/src/groups.ts, packages/initiatives/test/groups.test.ts
[bug](https://esriarlington.tpondemand.com/entity/104035-bug-000126797-unique-initiative-name-detection)
The `checkGroupExists` function is used by Hub to check for initiatiative existance by searching for stuff like "My Initiative Name Core Team." But the way `checkGroupExists` is currently set up, it will match the group name fuzzily. This PR forces it to match group names exactly.
=> Exactly matching group titles for existance check

packages/search/src/ago/get-items.ts, packages/search/test/ago/get-items.test.ts
This PR addresses the issue where the first AGO response doesn't have an `aggregations` element, manifesting in the following hub-indexer error:
```
Cannot set property 'counts' of undefined","stack":"at Object.<anonymous> (/opt/hub-indexer/packages/api/node_modules/@esri/hub-search/dist/node/ago/get-items.js:36:49)
```
A test has been added to demonstrate the fix.  I'm not one with the TypeScript so hopefully this passes muster.
=> initialize aggregations on first result when it doesn't exist

packages/search/src/ago/helpers/filters/collection.ts, packages/search/test/ago/helpers/filters/collection.test.ts
This PR fixes an issue where an unsupported collection is filtered on, resulting in an `undefined` array of types to iterate over.  For example, `filter[collection]=any(Sites)`, where `Sites` is not a supported collection wrapper.  The solution proposed in this PR is to remove falsey `types` arrays before reducing to expanded form.  
An example log from kibana showing the production error is:
```
level="error" timestamp="2020-01-27T14:41:27.272Z" status="itemsSearch-failed" reason={"errorMessage":"Cannot read property 'forEach' of undefined","stack":"at /opt/hub-indexer/packages/api/node_modules/@esri/hub-search/dist/node/ago/helpers/filters/collection.js:10:15"} reqDetails={"query":{"includeFailures":"true","agg":{"fields":"downloadable,hasApi,source,tags,type,access"},"fields":{"datasets …
```
=> filter out falsey type arrays

packages/search/src/ago/helpers/format/highlights.ts, packages/search/test/ago/helpers/format/highlights.test.ts
This PR fixes the case where the query parameter passed to the highlighting function cannot be parsed a regular expression.  This happens when the query parameter is `*`, resulting in:
```
> new RegExp('*', 'ig')
SyntaxError: Invalid regular expression: /*/: Nothing to repeat
```
Here's the kibana log where this emerges in production:
https://ingress.prod.hub.geocloud.com/kibana/app/kibana#/doc/AWtbfdKt275U86vEW3Rl/logstash-2020.01.23/fluentd?id=AW_UJLyUqLTHbvUsMs2E&_g=()
When the query parameter cannot be parsed as a regexp, the logic treats the highlights as if no matches were found.  
TP issue: https://esriarlington.tpondemand.com/restui/board.aspx?#page=userstory/110728
=> handle case where query cannot be parsed as a regexp

CHANGELOG.md, package.json, packages/search/src/ago/helpers/filters/filter-schema.ts, packages/search/test/ago/helpers/filters/create-filters.test.ts
Filters should be consistent and all use the same default values. This PR updates the `tags` filter to `any` to be consistent with the others.
=> Changing tags filter to default to any

packages/common/src/categories.ts
Catching something we missed when adding support for exb apps in Hub, adding exb apps to the Apps category. Just a string change.
=> add exb apps to apps category

packages/initiatives/src/templates.ts, packages/initiatives/test/templates.test.ts
Ensure that `data.recommendedTemplates` will be taken from the template and applied to the resulting model
=> feat(hub/initiatives): allow recommendedTemplates thru during templating

packages/initiatives/src/activate.ts, packages/initiatives/src/add.ts, packages/initiatives/src/model.ts, packages/initiatives/test/add.test.ts
- remove use of determineOwner internal fn coming from rest-js, 
- stop injecting admin url for new initiatives
=> Remove determineOwner, stop setting Admin Url

packages/initiatives/src/migrator.ts
This PR fixes the CURRENT_SCHEMA_VERSION to be 2.2 so that the 2.2 migration runs.
=> fix(Fixes current initiative schema to be 2.2 so that the 2.2 migration runs)

packages/common/src/categories.ts, packages/common/test/content.test.ts
The `Site Application` type is for sites created by ArcGIS Enterprise.
=> fix(common): fix the missing "Site Application" type for the "site" ategory

packages/surveys/package.json
I mistakenly didn't rebase my [previous PR](https://github.com/Esri/hub.js/pull/283) against `master` before merging. This caused the `version` for the new `hub-survey` package to get out of sync w/ the rest of the packages and broke the `npm run release:prepare` command as a result.
=> Fix versions surveys package.json file that was breaking release:prepare

docs/build-typedoc.js, package-lock.json, package.json
Revert to 0.14.2 from 0.17.8 as the json structure changed and I don't have time to determine what
to modify in our doc generator.
When using 0.17.8 we seem to get duplicates in the various lists
We can likely filter these out once we have a change to sift though the giant json output structure and determine what to remove
=> docs(docs): revert Typedoc version

packages/surveys/src/sharing/set-access.ts, packages/surveys/test/sharing/set-access.test.ts
[138621](https://esriarlington.tpondemand.com/entity/138621-owneradmin-can-set-sharing-level-for)
The `setAccess` method should only update access for the `Form` and `Fieldworker`, if it exists.
=> 138621 - Don't share survey feature service from setAccess method

packages/common/src/categories.ts, packages/common/test/content.test.ts, packages/search/package.json, packages/search/test/ago/encode-ago-query.test.ts, packages/search/test/ago/helpers/filters/collection.test.ts
https://esriarlington.tpondemand.com/entity/141567-chore-move-pages-into-initiatives-collection
Hub Pages currently exist under documents but should exist under the 'sites' collection. This PR contains a change to move these under 'sites'
=> c/141567 changed Hub Page and Site Page types to Site types from Document

packages/common/src/util.ts, packages/common/test/util.test.ts
=> fix(cloneObject): fix cloneObject's handling of Date properties

docs/src/guides/from-a-cdn.md, support/deploy-doc-site.js
Fitlering out the initiatives package from the tsdoc broke the cdn guide page, so I changed the example to use a few functions from the sites package.
I then re-built and deployed the docs, but found that i had to change the ghpages.publish call to publish `docs/build/hub.js` otherwise the gh-pages branch would have `/hub.js` as it's root, changing the doc url to `https://esri.github.io/hub.js/hub.js` instead of just `https://esri.github.io/hub.js/`
This seems baffling as I don't see any other recent changes that would have changed the doc build output location... but reading the `travis.yml` file I *think* CI will be fine as it does not actually use the `deploy-doc-site.sh` script
=> Fix CDN Guide and Doc Publishing Base Url

packages/initiatives/src/activate.ts, packages/initiatives/src/index.ts, packages/initiatives/src/update-initiative-site-id.ts, packages/initiatives/test/mocks/fake-session.ts, packages/initiatives/test/update-initiative-site-id.test.ts, packages/sites/src/create-site.ts, packages/sites/test/create-site.test.ts
Convoluted, but basically when we create a site, if the user has Hub Premium licensing, we also create an Initiative item. But we create that _before_ we create the site item... so we can't interpolate the siteId into the Initiative.
This adds a step to the createSite fn to lookup the initiative and add the siteId to it.
That step is backed by a function that we will use in opendata-ui to "heal" initiatives that do not have a siteId in them
=> Add Site ID to Initiative if it was created with the Site

packages/content/src/content.ts, packages/content/test/content.test.ts
=> fix(getContent): fix handle un-indexed (usually private) content

packages/common/src/request.ts, packages/common/test/request.test.ts, packages/content/src/content.ts, packages/content/src/hub.ts, packages/content/src/slugs.ts, packages/content/test/content.test.ts, packages/content/test/hub.test.ts, packages/content/test/slugs.test.ts
The slug handling logic is copied (roughly) from the composer service in the Hub app.
I also had to add the ability for `hubRequest()` to pass params, either in the query string or body of the request, and I'd like @rgwozdz to review that b/c we'll eventually want to have all the download code start using that fn.
=> getContent() handles slugs

packages/content/src/hub.ts, packages/content/test/hub.test.ts
=> fix(getContentFromHub): return first record when filtering by slug

packages/content/src/content.ts, packages/content/test/content.test.ts
@JoshCrozier and I discussed that data is no longer needed for map content views - it was a legacy from JSAPI 3.x.
=> do not fetch data for maps

packages/teams/src/utils/_create-team-group.ts, packages/teams/src/utils/get-allowed-group-access.ts, packages/teams/test/utils/_create-team-group.test.ts, packages/teams/test/utils/get-allowed-group-access.test.ts
affects: @esri/hub-teams
When determining what access level to set for a Team, respect the org level public sharing flag
canSharePublic
=> fix(hub-teams): respect org-level public sharing flag

demos/oauth2-browser/package.json, packages/annotations/package.json, packages/common/package.json, packages/content/package.json, packages/downloads/package-lock.json, packages/downloads/package.json, packages/downloads/src/portal/portal-request-dataset-export.ts, packages/downloads/test/portal/portal-request-dataset-export.test.ts, packages/events/package.json, packages/initiatives/package.json, packages/search/package.json, packages/sites/package.json, packages/surveys/package.json, packages/teams/package.json
Download export requests for multilayer, portal items should export ALL layers.  This PR ensures that occurs by remove the "layers" property from the `exportItem` call.
=> Downloads: if item is a portal item and it is multilayer, export all layers

packages/downloads/src/download-status.ts, packages/downloads/src/hub/hub-poll-download-metadata.ts, packages/downloads/src/hub/hub-request-download-metadata.ts, packages/downloads/src/portal/portal-poll-export-job-status.ts, packages/downloads/src/request-download-metadata.ts, packages/downloads/test/hub/hub-poll-download-metadata.test.ts, packages/downloads/test/hub/hub-request-download-metadata.test.ts, packages/downloads/test/portal/portal-poll-export-job-status.test.ts, packages/downloads/test/request-download-metadata.test.ts
First off, apologies.  This PR includes a lot of changes due to auto-lint fixing.
The actual purpose of the PR is to standardize the error events that get emitted if there was an error in the download export process.  All error events look like:
```
{
detail: { error, metadata }
}
```
To facilitate that, I have also changed the response of the hubDownloadMetadata method to include the `errors` array from the Hub API.
All other changes are tests and linting.
=> Add errors array to hub api metadata and status to polling event metadata

packages/downloads/src/portal/portal-request-download-metadata.ts, packages/downloads/test/portal/portal-request-download-metadata.test.ts
affects: @esri/hub-downloads
The `fetchCacheSearchMetadata()` in the `downloads` package was not passing the layer id to its internal util function `fetchCacheSearchMetadata`. As a result, it created incorrect item types to query cache for sublayers of a feature service item. For example, it should be `CSV`, not `CSV Collection` for an individual sublayer.
=> fix(downloads): portalRequestDownloadMetadata() function did not recongize layer id

packages/downloads/src/hub/hub-poll-download-metadata.ts, packages/downloads/src/poll-download-metadata.ts, packages/downloads/test/hub/hub-poll-download-metadata.test.ts, packages/downloads/test/poll-download-metadata.test.ts
For datasets that don't expose a lastEditDate, the Hub API returns a status of `ready_unknown` when a file is ready on S3 - this means it's "ready" but unknown whether it is up-to-date with respect to the service.
The existing polling method in hub.js does not handle such status correctly.  This PR adds required handling.  The polling method:
* now includes an argument that tracks the existing S3 file's timestamp (if exists)
* now checks for `ready_unknown` status and if found, compares the new file's date to the old file's date to ensure the re-export has finished.  If so, a success event is emitted and polling is cancelled.
=> Handle status polling for datasets returning "ready_unknown" status

package-lock.json, packages/sites/src/domains/add-domain.ts, packages/sites/src/domains/update-domain.ts, packages/sites/test/domains/add-domain.test.ts, packages/sites/test/domains/update-domain.test.ts
Ensure that domain add/update coerce numeric site title to a string
When consuming hub.js in Ember (non-typescript) numeric site title can be passed into the add/update domain functions. This PR adds checks to coerce numerics to strings on this property.
=> fix(sites): coerce numeric site title to string

packages/sites/src/create-site-model-from-template.ts, packages/sites/test/create-site-model-from-template.test.ts
Typically we derive the site subdomain based on the site title. But if the title contains unicode chars, we can't use it, so instead we start from "site" and `ensureUniqueDomain` will increment that depending on existing sites until we get something like `site-21-<orgkey>.hub.arcgis.com`
Needed to address an issue in Hub re: cloning sites w/ Japanese titles, but will be an issue for any scenario where the title has unicode chars
=> fix(sites): Handle unicode chars in Site title

package-lock.json, packages/sites/src/create-site-model-from-template.ts, packages/sites/src/get-portal-site-hostname.ts, packages/sites/test/create-site-model-from-template.test.ts, packages/sites/test/get-portal-site-hostname.test.ts
Use portalSelf to derive site url for portal
We had some logic that used `window.location` via `_getLocation()` to derive the url of the resulting site. This logic worked when hub.js was running in the context of the Hub application (/apps/sites) but did not work when running in the context of the Solutions app.
This PR changes the logic to use the the `IPortal` passed into `getPortalSiteHostname` to derive the host + instance, and then construct the site url
Also handles the case when the title of a site is a number. This can happen because downstream apps using Hub.js may not be using typescript.
=> fix(sites): fix logic for site url on portal

package-lock.json, package.json, packages/downloads/src/download-status.ts, packages/downloads/src/portal/portal-export-completion-error.ts, packages/downloads/src/portal/portal-export-success-handler.ts, packages/downloads/src/portal/portal-get-exports-folder-id.ts, packages/downloads/src/portal/portal-poll-export-job-status.ts, packages/downloads/src/portal/portal-request-download-metadata.ts, packages/downloads/src/request-download-metadata.ts, packages/downloads/test/portal/portal-export-success-handler.test.ts, packages/downloads/test/portal/portal-get-exports-folder-id.test.ts, packages/downloads/test/portal/portal-poll-export-job-status.test.ts, packages/downloads/test/portal/portal-request-download-metadata.test.ts
* Adds a `ready_unknown` status for portal downloads
* Puts the portal export-complete handler in its own file
* Puts the function for acquiring exports folder id in its own file.
* Adds tests.
=> fix(@esri/hub-downloads): add support of ready_unknown status for portal

packages/sites/src/ensure-required-site-properties.ts
enable the `downloadSidebar` capability by default for new sites
=> feat(sites): enable the new download sidebar capability by default

packages/sites/src/ensure-required-site-properties.ts
Reverts Esri/hub.js#460
We need to remove the capability from the default list due to an issue in the new download UI.
=> Revert "feat(sites): enable the new download sidebar capability by default"

packages/common/src/index.ts
Although I added `OperationStack` and `OperationError` 3 months back, I did not actually _export_ them. 
Oh the shame.
=> feat: actually export OperationError and OperationStack

packages/downloads/src/portal/portal-export-success-handler.ts, packages/downloads/src/portal/portal-request-download-metadata.ts, packages/downloads/test/portal/portal-export-success-handler.test.ts, packages/downloads/test/portal/portal-request-download-metadata.test.ts, packages/downloads/test/request-download-metadata.test.ts
Portal searches using `typekeywords` appear to have issues with occurrences of `1`. For example, a search for keyword `export:abcdef0123456789abcdef0123456789_1` fails to narrow results properly and returns multiple items with keywords `export:abcdef0123456789abcdef0123456789_0`, `export:abcdef0123456789abcdef0123456789_1`, `export:abcdef0123456789abcdef0123456789_2`.  Changing the item/layer delimiter from `_` to `-` or `~` has no effect. Splitting the item id and layer id into separate terms (exportItem:abcdef0123456789abcdef0123456789, exportLayer:1`) also has no effect.  Attaching a string prefix to the layer index (exportItem:abcdef0123456789abcdef0123456789, exportLayer:layer1`) similarly has no effect.
I've reached out to the search team and the response is to use `filter` instead …
=> Change cached download search terms for portal

packages/annotations/package.json, packages/content/package.json, packages/events/package.json, packages/initiatives/package.json, packages/search/package.json, packages/sites/package.json, packages/surveys/package.json, packages/teams/package.json
affects: @esri/hub-annotations, @esri/hub-content, @esri/hub-events, @esri/hub-initiatives,
@esri/hub-search, @esri/hub-sites, @esri/hub-surveys, @esri/hub-teams
ISSUES CLOSED: #473
=> fix(everything): adding rest-js 3 to peer dep ranges

docs/src/guides/operation-stack.md, packages/common/src/OperationError.ts
Better handling of the `rootCause` optional param in `OperationError` constructor. 
If a `rootCause` is passed in, then we use it's `.stack` vs creating a new one b/c that will make the error look like it was thrown inside the OperationError constructor, which it is not.
Also updates the Operation Stack guide w/ example outputs
=> Ensure OperationStack retains rootCause

packages/sites/src/create-site-model-from-template.ts, packages/sites/test/create-site-model-from-template.test.ts
For complex reasons we were forcing the site title to be the solution title. We needed to dial back
that logic so static site names can be used.
This addresses a bug for the Solutions team needed for their 10.9 certification.
=> fix(hub-sites): ensure that we respect interpolation of site title

.github/workflows/build-test.yml, package.json, packages/annotations/package.json, packages/common/package.json, packages/content/package.json, packages/downloads/package.json, packages/events/package.json, packages/initiatives/package.json, packages/search/package.json, packages/sites/package.json, packages/surveys/package.json, packages/teams/package.json
affects: @esri/hub-annotations, @esri/hub-common, @esri/hub-content, @esri/hub-downloads,
@esri/hub-events, @esri/hub-initiatives, @esri/hub-search, @esri/hub-sites, @esri/hub-surveys,
@esri/hub-teams
implements first phase of #488
=> feat(everything): distribute es2017 build

packages/teams/src/utils/can-user-create-team-in-product.ts, packages/teams/test/utils/can-user-create-team-in-product.test.ts
This ensures that during the site deployment process we check that the user has some group capacity before
=> fix: check user groups before confirming they can create a team

packages/content/src/hub.ts, packages/content/test/hub.test.ts, packages/content/test/mocks/items/map-service.json
We now fetch the item from the AGO API even in cases where we were able to fetch it from the Hub API.
https://devtopia.esri.com/dc/hub/issues/53
=> feat(content): getContent now fetches the item from the AGO API 

packages/teams/src/well-known-teams.ts
affects: @esri/hub-teams
Content teams, in well known teams, membershipAccess set to everyone.
=> fix(hub-teams): content teams membershipAccess set to everyone

packages/teams/src/utils/get-team-by-id.ts, packages/teams/src/utils/get-team-members.ts, packages/teams/test/utils/get-team-by-id.test.ts, packages/teams/test/utils/get-team-members.test.ts
`getTeamById` and `getTeamMembers` were not passing the `IHubRequestOptions` forward, and instead creating a new object using just the auth... i.e. `{authentication: hubRo.authentication}` and that works for auth'd users. 
But for users who are not auth'd, not passing the whole `IHubRequestOptions` means that the `.portal` property is not available, and thus the urls constructed point to www.arcgis.com vs qaext.
=> fix: teams get functions needed to pass hubRo to rest-js fns

packages/content/src/hub.ts, packages/content/src/portal.ts, packages/content/test/hub.test.ts, packages/content/test/mocks/datasets/document.json, packages/content/test/mocks/datasets/feature-layer-with-metadata.json, packages/content/test/mocks/datasets/feature-layer.json, packages/content/test/portal.test.ts
looks like the API defaults to [] for itemExtent. previously I assumed it was falsey.
also, always return content.item, including the actual item extent for comparison
=> fix(content): return content.item &  handle when itemExtent is []

packages/common/src/collections.ts, packages/common/src/content.ts, packages/common/src/types.ts, packages/common/test/content.test.ts, packages/content/src/content.ts, packages/content/src/enrichments.ts, packages/content/src/hub.ts, packages/content/src/portal.ts, packages/content/test/content.test.ts, packages/content/test/enrichments.test.ts, packages/content/test/hub.test.ts, packages/content/test/portal.test.ts, packages/search/test/ago/encode-ago-query.test.ts
This PR gets closer to resolving #322. In essence, everything we need should be there _if_ the content was fetched from the Hub API. If the content is coming from portal, we still have to add logic to `enrichContent()` to fetch additional enrichments such as `server`, `layers`, `recordCount`, etc.
This PR also makes a few fixes to the way `itemToContent` and `datasetToContent` were handling `hubId` and `isPortal`. TLDR: we should only set `hubId` if we are fairy confident that it is in the index. Also, `isPortal` is not returned by the API, we'll need to set it (and the proxied `url`) in `enrichContent()` before calling `fetchEnrichments()`.
In service of those, the PR also moves several low level utils from the Hub app to Hub.js (getFamily, getItemHubId, etc), and it also re-orders how …
=> Content family and org

packages/sites/src/get-portal-site-hostname.ts, packages/sites/test/get-portal-site-hostname.test.ts
Correctly use portalSelf to compute the url for a newly created site
Resolves #552
=> fix(hub-sites): correctly generate site url

packages/teams/src/utils/can-edit-team.ts, packages/teams/test/utils/can-edit-team.test.ts
Add a new `canEditTeam` fn in teams package util to check whether a user has access to edit a team
5) [x] ran commit script (`npm run c`)
=> Add new canEditTeam fn in teams package util

.github/workflows/pull-request-tests.yml, packages/downloads/src/hub/hub-poll-download-metadata.ts, packages/downloads/test/hub/hub-poll-download-metadata.test.ts
We have tried a number of quick-fix approaches and nothing has worked, so the next thing is to try to swap to using hubRequest, and stubbing vs using fetchMock. Until that lands this PR skips the tests, and removes the backing functions from code-coverage
Also - apparently `prettier` cleaned things up... I love the _idea_ of prettier, but why/how is it SO inconsistent?
5) [ ] ran commit script (`npm run c`) - used conventional commit message
=> chore(hub-downloads): add fail() and move done()

packages/teams/src/well-known-teams.ts
I can't spell access apparently. This fixes that!
=> fix(hub-teams): fixes membershipAccess spelling in privPropValues hash

packages/teams/src/utils/get-user-creatable-teams.ts, packages/teams/test/utils/get-user-creatable-teams.test.ts
Previously we were updating the template inside the filter function, which didn't actually update the template that was output from getUserCreatableTeams. Swapped to using a reduce to both update the template and filter it.
=> fix(hub-teams): template was not properly updated based on privPropValue

packages/teams/src/utils/index.ts
Signed-off-by: Vivian Zhang <vzhang@esri.com>
export `canEditTeam` fn that was added in https://github.com/Esri/hub.js/pull/558
=> fix(hub-teams): export canEditTeam

.github/workflows/pre-release-tests.yml
1. Description: comments out windows build steps from pre-release-tests workflow
=> ci: remove windows build steps

docs/src/guides/composing-workflows.md, docs/src/guides/operation-pipe.md, packages/common/src/utils/create-operation-pipeline.ts, packages/common/test/utils/create-operation-pipeline.test.ts
Add the `createOperationPipeline` function, for use streamlining the Content Enrichments, and other chain type scenarios
TODO:
run tests
3) Screenshot/GIF: n/a
5) [x] ran commit script (`npm run c`)
=> feat(hub-common): add createOperationPipeline function

package-lock.json, packages/teams/src/add-or-invite-users-to-team.ts, packages/teams/src/types.ts, packages/teams/test/add-or-invite-users-to-team.test.ts, packages/teams/test/add-or-invite-users-to-teams.test.ts
1. Description: I neglected to add the groupId onto each groups response object thereby making it rather hard to locate. This is now corrected.
=> fix(hub-teams): add groupId to each groups add members response

packages/teams/src/create-hub-teams.ts, packages/teams/src/utils/remove-invalid-privs.ts, packages/teams/test/create-hub-teams.test.ts, packages/teams/test/utils/remove-invalid-privs.test.ts
affects: @esri/hub-teams
Handle missing subscriptionType prop in Enterprise
In enterprise portalSelf.subscriptionInfo.type is not defined. This will allow that to fail gracefully
5) [x] ran commit script (`npm run c`)
=> fix(hub-teams): createHubTeams in Enterprise

packages/teams/src/types.ts, packages/teams/src/utils/add-or-invite-community-users.ts, packages/teams/src/utils/handle-no-users.ts, packages/teams/test/utils/add-or-invite-community-users.test.ts, packages/teams/test/utils/handle-no-users.test.ts
1. Description: This allows one to limit sending emails to a single group out of n, while users are still added to all groups.
=> fix(hub-teams): allow for emails to be sent to only a single group

docs/src/guides/hub-discussions.md
changed the order of Discussions Guide to provide some up-front information and better onboarding.
=> docs(hub-discussions): simplified discussions guide

package-lock.json, packages/common/src/groups/add-users-workflow/workflow-sections/invite-users.ts, packages/teams/src/utils/process-invite-users.ts, packages/teams/test/utils/process-invite-users.test.ts
Made a slight oversight in a case where an admin in a core team can only invite users (not auto add them), we still want the person invited to be invited as an admin. This opens that option up.
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/1758
=> fix(hub-teams): allow for user to be invited as group admin

packages/search/src/content/index.ts
affects: @esri/hub-search
Documentation-only changes
=> docs(hub-search): add inline docs and examples to searchContent()

docs/src/README.md, docs/src/guides/content-search.md
add docs readme; add header for content-search
run `npm run docs:serve`, verify Search Content in TOC and that page renders
=> docs(hub-search): add docs readme; add header for content-search

packages/common/src/index.ts, packages/search/package.json, packages/search/src/content/helpers/convert-request-to-portal-params.ts, packages/search/src/util/merge-pagination/merge.ts, packages/search/test/content/helpers/convert-request-to-portal-params.test.ts
affects: @esri/hub-common, @esri/hub-search
`hub-search` was using `base-64` but we're standardizing on `abab`.
`npm t`
1. Closes Issues:
=> refactor(hub-search): use a new base-64 encoding lib

packages/content/src/enrichments.ts, packages/content/test/enrichments.test.ts
A bug in the content-upload component of opendata-ui mistakenly characterizes non-feature services as Feature Services, which has downstream effects. In this case, it breaks an assumption that anything characterized as a Feature Service will automatically have layers as part of assembling enrichments. Because these items are now in the open, this change adds a defense mechanism to [prevent 404's from the search page](https://devtopia.esri.com/dc/hub/issues/1908) when clicking on such an item
See [issue](https://devtopia.esri.com/dc/hub/issues/1908) for detailed repro. This also happens for **private** ArcGIS Online items. Once released an in UI, 404's should stop happening. **Note that this PR does not address …
=> fix(hub-content): introduces empty array to handle servers without layers mistakenly typed as feature

packages/content/src/enrichments.ts, packages/content/test/enrichments.test.ts
1. Description: After pulling #637 into the -ui app, I realized that we also needed to ser `hubId` for public layers, so here we are.
=> fix(hub-content): getLayerContent should update hubId

packages/common/src/index.ts, packages/common/src/search/fetch-datasets.ts, packages/common/src/search/index.ts, packages/common/test/search/fetch-datasets.test.ts
1. Description: add fetchDatasets() fn
1. another step towards #606 
=> feat(hub-common): add fetchDatasets() function

packages/search/src/content/helpers/convert-hub-response.ts, packages/search/src/content/helpers/convert-portal-response.ts, packages/search/src/types/content.ts, packages/search/test/content/helpers/convert-hub-response.test.ts, packages/search/test/content/helpers/convert-portal-response.test.ts, packages/search/test/content/index.test.ts
affects: @esri/hub-search
1. Resolves #606
=> fix(hub-search): searchContent() should return results as IHubContent[]

packages/common/src/objects/deepFind.ts, packages/common/src/objects/index.ts, packages/common/test/objects/deepFind.test.ts
Adds two helper functions to hub-common:
- `deepFind(object: any, predicate: (object: any) => boolean): any`
- `deepFindById(object: any, value: string | number): any`
Both can be used to search for objects in a deep graph which meet some condition. Akin to `Array.find`. If nothing is found that meets the condition, `undefined` is returned.
This is intended to be used in the context of loading card configuration out of a `layout` into a component on a generic website.
- run tests
For more …
=> feat(hub-common): deepFind, deepFindById functions

packages/common/e2e/search-groups.e2e.ts, packages/common/src/search/_searchGroups.ts, packages/common/src/search/content-utils.ts, packages/common/src/search/group-utils.ts, packages/common/src/search/index.ts, packages/common/src/search/types.ts, packages/common/test/mocks/mock-auth.ts, packages/common/test/mocks/portal-groups-search/simple-response.json, packages/common/test/search/_searchGroups.test.ts, packages/common/test/search/group-utils.test.ts
Add `_searchGroups` to hub-common, using `Filter<"group">`
- run tests
=> Add _searchGroups function

packages/common/src/search/index.ts
As it says - export all fns from `group-utils` in hub-common/search
Consume in another app... 
=> fix(hub-common): export group utils

packages/common/src/search/content-utils.ts, packages/common/src/search/group-utils.ts, packages/common/test/search/content-utils.test.ts, packages/common/test/search/group-utils.test.ts
- add `mergeGroupFilters(filters: Array<Filter<"group">>): Filter<"group">`
- fix issue in `mergeContentFilters` so multiple `term` entries are appended
run tests
=> feat(hub-common): add mergeGroupFilters

package-lock.json, package.json
This warning has been appearing for some time now, but it seems something bumped up versions and now it's actually erroring:
GH Actions should not throw this error
=> chore: bump karma-jasmine package to fix deprecation

packages/common/src/search/_searchGroups.ts
Fix thumbnailUrl typo in `_searchGroups`
=> fix: fix thumbnailUrl typo in _searchGroups

packages/common/e2e/search-content.e2e.ts, packages/common/e2e/search-groups.e2e.ts, packages/common/src/search/_searchContent.ts, packages/common/src/search/_searchGroups.ts, packages/common/src/search/types.ts, packages/common/src/search/utils.ts, packages/common/src/types.ts, packages/common/test/mocks/portal-groups-search/simple-response.json, packages/common/test/search/_searchContent.test.ts, packages/common/test/search/_searchGroups.test.ts, packages/common/test/search/utils.test.ts, packages/search/package.json, packages/search/src/types/common.ts, packages/search/src/types/content.ts
- adds `hasNext` and `.next()` to the response from `_searchContent` and `_searchGroups`
- changes the return types to `ISearchResponse<IHubContent>` and `ISearchResponse<IGroup>`
- removes multi-api search/merge logic from `_searchContent` as that is not needed and adds a lot of complexity for the `next()` function
- ensures that passing an `IApiDefinition` without auth, directs the search to the specified url (i.e. works with Enterprise)
-run tests
=> feat(hub-common): add next() to _searchContent and _searchGroups

packages/common/src/sites/upgrade-site-schema.ts
This PR adds an important warning to anyone adding a site schema migration.
1. Closes Issues: none
=> docs(hub-common): add warning message around site schema migrations

package-lock.json, packages/common/src/content.ts
**Description:**
Extracts the functionality for generating relative and absolute site urls out of `setContentSiteUrls` and into it's own function for others to consume. This is needed as part of https://devtopia.esri.com/dc/hub/issues/2571
[x] ran commit script (`npm run c`)
=> feat(hub-common): add getContentSiteUrls()

packages/common/src/content.ts, packages/common/test/content.test.ts
Resolves https://devtopia.esri.com/dc/hub/issues/2123.
Using normalizedType to calculate family solves the issue of legacy item types. For example, Hub
Initiative Templates used to be designated as type: 'Hub Initiative' with typeKeywords:
['hubInitiativeTemplate']. Running these old initiative templates through setContentType() used to
set family incorrectly as 'initiative'. Now family is correctly set to 'template'.
=> fix(hub-common): setContentType() now uses normalizedType to calculate family

packages/common/src/content/index.ts, packages/common/test/content.test.ts
get content type icon and content type label in itemToContent
=> feat(hub-common): get content type icon and content type label in itemToContent

packages/common/src/ArcGISContext.ts, packages/common/src/index.ts, packages/common/src/types.ts, packages/common/src/utils/index.ts, packages/common/src/utils/sessionLocalStorage.ts, packages/common/test/ArcGISContext.test.ts, packages/common/test/utils/sessionLocalStorage.test.ts
- Add ArcGISContext class and Session LocalStorage Utils
ArcGISContext is pretty similar to AppSettings class in hub-components, but more generically named, and moves localStorage from inside the class to separate utils.
Next step will be to pull this into -ui, and expose an instance on the app-settings service so that it is available for use with hub-components. Then, I'll update the hub-components package to use ArcGISContext instead of AppSettings, and finally update UI with latest of all packages, consuming ArcGISContext from the app-settings service.
- run tests
_Note_ If you don't run the commit script at least once, the Semantic Pull Request check will …
=> Add ArcGISContext class and Session LocalStorage Utils

packages/common/src/ArcGISContext.ts, packages/common/src/ArcGISContextState.ts, packages/common/test/ArcGISContext.test.ts
In order to have frameworks like Ember or React or Vue "react" when the state of the ArcGISContext changes is to expose the state on a property of the ArcGISContext instance, and when the context is modified, the state is replaced with a new reference.
So - this PR creates the `ArcGISContextState` class, which is exposed on `ArcGISContext.state`. When we addAuth or clearAuth, we replace the `ArcGISContextState` instance.
Have verified that this works in Ember
Run tests
=> fix: Add "state" to ArcGISContext to enable Frameworks to "react" to changes

karma.conf.js, packages/common/src/ArcGISContext.ts, packages/common/test/ArcGISContext.test.ts, packages/common/test/mocks/ExceptionFactory.ts
`ArcGISContext.create(...)` can now take  `portal:IPortal` and `currentUser:IUser` and will skip fetching those during initialization if passed in. This allows apps which already have this information to skip additional xhrs.
- runs tests
=> fix: more optional params to ArcGISContext

packages/common/src/content/index.ts, packages/common/src/types.ts
use content.type instead
`npm test`
=> refactor(hub-common): deprecate content.normalizedType

packages/common/src/collections.ts, packages/common/src/content/index.ts, packages/common/test/collections.test.ts, packages/common/test/content.test.ts
1. [x ran commit script (`npm run c`)
=> refactor(hub-common): move getCollection() to collection module

packages/discussions/src/types.ts
BREAKING CHANGE: move editor from IWithAuthor to IWithEditor
Decomposes IWithAuthor into IWithAuthor and IWithEditor (https://devtopia.esri.com/dc/hub/issues/3006)
N/A
=> feat(hub-discussions): add IWithEditor interface

packages/common/src/search/types.ts
Add defaultOrder and order props to ISortOption
=> feat(hub-common): add defaultOrder and order props to ISortOption

packages/common/src/content/_internal.ts, packages/common/src/content/compose.ts, packages/common/src/content/get-family.ts, packages/common/src/content/index.ts, packages/common/src/core/types/IHubContent.ts, packages/common/src/core/types/IHubContentEnrichments.ts, packages/common/src/core/types/IHubItemEntity.ts, packages/common/src/core/types/IServerEnrichments.ts, packages/common/src/core/types/index.ts, packages/common/test/compose.test.ts, packages/common/test/content.test.ts, packages/content/src/enrichments.ts, packages/content/test/enrichments.test.ts, packages/content/test/hub.test.ts, packages/content/test/portal.test.ts
affects: @esri/hub-common, @esri/hub-content
replaces existing implementations of itemToContent(), datasetToContent(), and getLayerContent()
If tests pass w/ complete coverage, we good.
1. Part of : [2870](https://devtopia.esri.com/dc/hub/issues/2870)
=> feat(hub-common): add composeContent()

package-lock.json, packages/common/src/sites/domains/index.ts, packages/common/src/sites/domains/remove-domains-by-site-id.ts, packages/common/test/sites/domains/remove-domains-by-site-id.test.ts, packages/sites/src/_remove-site-domains.ts, packages/sites/test/_remove-site-domains.test.ts
affects: @esri/hub-common, @esri/hub-sites
rename `removeDomain()` to `removeDomainById()`
add `removeDomainsBySiteId()` to delete all domains associated with a site
`removeDomain()` renamed to `removeDomainById()`
ISSUES CLOSED: [#3230](https://devtopia.esri.com/dc/hub/issues/3230)
- Update `_removeSiteDomains()` to use the new Domains DELETE endpoint `deleteBySiteId()`
- This allows `_removeSiteDomains()` to make a single request instead of requesting get all domain records by `siteId` and then sending parallel requests to delete each record
1. Closes Issues: [#3230](https://devtopia.esri.com/dc/hub/issues/3230)
_Note_ If you don't run the commit script at least once, the Semantic Pull …
=> feat(hub-common): add removeDomainsBySiteId()

package-lock.json, packages/common/src/content/_internal.ts, packages/common/src/content/compose.ts, packages/common/src/content/index.ts, packages/common/src/core/types/IHubAdditionalResource.ts, packages/common/src/core/types/IHubContent.ts, packages/common/test/compose.test.ts, packages/common/test/content.test.ts
Part of [3304](https://devtopia.esri.com/dc/hub/issues/3304)
Added to the IHubContent interface and created additional helpers to parse and transform additional resources from formal item metadata
=> feat(hub-common): add additional resources to IHubContent composition logic

packages/common/src/projects/HubProjects.ts, packages/common/test/projects/HubProjects.test.ts
The `Hub Project` item type landed on QAEXT so we can now switch the code to use that vs `Web Mapping Application`
Run tests
=> fix: switch to final item type for hub projects

package-lock.json, packages/common/src/content/compose.ts, packages/common/src/content/index.ts, packages/common/test/content.test.ts
I should not have removed the extent enrichment logic from `datasetToContent()` 
=> fix(hub-common): fix missing extent in datasetToContent()

packages/search/src/ago/get-items.ts, packages/search/test/ago/get-items.test.ts
affects: @esri/hub-search
top level countFields had all (unchunked) countFields
and overrides params.countFields
1. Closes Issues: [#3258](https://devtopia.esri.com/dc/hub/issues/3258)
=> fix(hub-search): fix not chunking countFields

packages/common/package.json, packages/common/src/content/fetch.ts, packages/common/test/content/fetch.test.ts
Part of [2866](https://devtopia.esri.com/dc/hub/issues/2866)
Also fixes a parity issue where slugs passed in to fetch content were not respected (i.e. the slug of the specified layer was populated instead).
=> fix(hub-common): only fetch record count for feature layers and tables (e.g. not raster layers)

packages/common/src/search/types.ts
Fix for https://github.com/Esri/hub.js/pull/750
=> fix(hub-common): use accordionClosed instead of accordionOpen

packages/common/src/content/_fetch.ts, packages/common/src/content/fetch.ts, packages/common/src/items/_enrichments.ts, packages/common/src/utils/_array.ts, packages/common/test/content/_fetch.test.ts, packages/common/test/utils/_array.test.ts
errors fetching enrichments form the Hub API were causing `fetchContent()` to fail, but instead we should have been catching them and adding them to `content.errors`, which is what this PR does.
=> fix(hub-common): fetchContent() handles & returns non-fatal errors

package-lock.json, packages/common/src/content/_internal.ts, packages/common/src/content/compose.ts, packages/common/test/content.test.ts, packages/content/test/hub.test.ts
Part of [2866](https://devtopia.esri.com/dc/hub/issues/2866).
It turns out that `item.spatialReference` isn't always a wkid. Sometimes, it is the name of a wkt (but not the full wkt itself). This is problematic since we don't currently have a way in our applications to lookup the full wkt that we would need for geospatial operations.
As such, we decided to give preference to the layer spatial reference, since it is a more predictable source of truth.
We also eliminated referencing the server's spatial reference since we are unsure if different layers can have different spatial references.
=> fix(hub-common): fix composeContent to prefer layer spatialReference to item spatialReference

packages/common/src/items/slugs.ts, packages/common/src/projects/HubProjects.ts, packages/common/test/items/slugs.test.ts, packages/common/test/projects/HubProjects.test.ts
1. Description - This PR does the following.
- Ensures any portal is passed on in case no auth is provided.
- Removes a wrapped error to maintain original error status code and message
- Handles null pointer when no project matching an identifier is found.
3. Instructions for testing:
Modified code in Hub Project API and saw proper responses.
4. [x] ran commit script (`npm run c`)
=> fix(hub-common): defaults q param of fetchItemsBySlug to be slug and adds portal

package-lock.json, packages/common/src/content/fetch.ts, packages/common/test/content/fetch.test.ts
Fix for https://devtopia.esri.com/dc/hub/issues/3488
Targeted strike for older services (version < 10.5)
=> fix(hub-common): re-fetch target layer for legacy services that return sparsely populated layers

packages/common/src/content/_internal.ts, packages/common/src/content/compose.ts, packages/common/src/content/fetch.ts, packages/common/test/compose.test.ts, packages/common/test/content.test.ts, packages/content/src/enrichments.ts, packages/content/test/hub.test.ts, packages/content/test/portal.test.ts
affects: @esri/hub-common, @esri/hub-content
Part of https://devtopia.esri.com/dc/hub/issues/3512
Fixes incorrect fetching and composing of Proxied CSVs. These changes include:
- `fetchContent` sets the `item.url` of proxied csvs to point to the proxying feature service
- `fetchContent` grabs layer and server enrichments for proxied csvs
- `composeContent` sets the `hubId` of proxied csvs to the `item.id`
- `composeContent` correctly handles `extent` fallback scenarios and sets `extent` to be a bbox
=> fix(hub-common): fix issues composing proxied csvs

package-lock.json, packages/common/src/resources/_internal/_validate-url-helpers.ts, packages/common/src/resources/index.ts, packages/common/src/resources/validate-url.ts, packages/common/src/types.ts, packages/common/test/resources/_validate-url-helpers.test.ts, packages/common/test/resources/validate-url.test.ts
1. Description: Migrates validate url logic from Haoliang over from ember. Will be used by new component in hub-components.
=> feat(hub-common): migrate validateUrl function from ember application

packages/common/src/content/slugs.ts, packages/common/test/content.test.ts
- When removing context from slug, there was a very nasty edge case where slug was improperly removed if the underlying item belonged to a different org (context) and the current context and underlying context ended with the same text. This is a regex change to ensure the slug must be matched entirely
- See unit tests. Also built and resolved issue in opendata-ui
3. Closes Issues: [3470](https://devtopia.esri.com/dc/hub/issues/3470)
4. [x] ran commit script (`npm run c`)
=> fix(hub-common): fixes removeContextFromSlug to ensure entire context included

packages/discussions/src/types.ts
Reflects recent changes in hub-discussions to support spatial filtering of post geometry and new
featureGeometry field
`hub-discussions` has new `post.featureGeometry` column and both `post.geometry` and `post.featureGeometry` are *searchable* by `Geometry`.
=> feat(hub-discussions): extends post geometry support in hub-discussions

package-lock.json, packages/sites/src/convert-site-to-template.ts, packages/sites/src/pages/convert-page-to-template.ts, packages/sites/test/convert-site-to-template.test.ts, packages/sites/test/pages/convert-page-to-template.test.ts, packages/sites/test/site-responses.test.ts
Ignore draft resources when clone a site or page
Clone a site or page, you should see the cloned version doesn't have the draft resources information
1. Closes Issues: #<3546> [3546](https://zentopia.esri.com/workspaces/collaboration-sprint-board-614f9bfc0946c40011ef574e/issues/dc/hub/3546)
=> fix(hub-sites): ignore draft resources when clone a site or page

packages/common/src/search/_internal/searchContentEntities.ts, packages/common/src/search/_searchContent.ts, packages/common/src/search/_searchGroups.ts, packages/common/src/search/_searchUsers.ts, packages/common/src/search/types.ts, packages/common/test/projects/HubProjects.test.ts, packages/common/test/search/_searchContent.test.ts, packages/common/test/search/_searchGroups.test.ts, packages/common/test/search/_searchUsers.test.ts
1. Description
The IHubSearchOptions interface was tailored to the Hub V3 API, which did not allow for a start option property. It's predicted to be allowed in the Hub V4 API. This PR does not change the IHubSearchOptions interface, but allows for a valid start property for Project Search
2. See Unit Test
3. Closes Issues: N/A but unblocks [3531](https://devtopia.esri.com/dc/hub/issues/3531)
4. [x] ran commit script (`npm run c`)
=> fix(hub-common): allows start param to be passed into Project searches

packages/content/README.md
=> docs(hub-content): deprecate hub-content package

package-lock.json, packages/common/src/items/_enrichments.ts, packages/common/test/items/_enrichments.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/3861
`enrichServer` was returning the layer definition instead of the server definition for items that had a reference layer url (i.e. `.../FeatureServer/:layer`). This is because we mistakenly assumed that Rest.js' `getService` function stripped `/:layer` from the url before making the call. It does not, so we have to do it on our own.
=> fix(hub-common): fix issue where enrichServer actually fetched the layer for reference layer items

package-lock.json, packages/common/package.json
[Before](https://github.com/Esri/hub.js/runs/6395049343?check_suite_focus=true#step:5:93)
```bash
[@esri/hub-common::rollup] ┌───────────────────────────────────────────┐
[@esri/hub-common::rollup] │                                           │
[@esri/hub-common::rollup] │   Destination: ./dist/umd/common.umd.js   │
[@esri/hub-common::rollup] │   Bundle Size:  736.18 KB                 │
[@esri/hub-common::rollup] │   Minified Size:  227.17 KB               │
[@esri/hub-common::rollup] │   Gzipped Size:  74.41 KB                 │
[@esri/hub-common::rollup] │                                           │
[@esri/hub-common::rollup] └───────────────────────────────────────────┘
```
After
```bash
│ ┌───────────────────────────────────────────┐
│ │ …
```
=> chore: upgrade fast-xml-parser for 25% smaller builds of hub-common

package-lock.json, packages/initiatives/src/groups.ts, packages/initiatives/test/groups.test.ts
- adds title filter to the query used by`checkGroupExists`  function to eliminate false positives due to fuzzy agol search
=> fix(hub-initiatives): filter group search by title

packages/common/src/content/_internal.ts
1. Description: fixes a type error when checking if additional resource is an item data source
3. Closes Issues: #3860 (if appropriate)
4. [x] used semantic commit messages - ran `npm run c`
5. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation will not run!) - ran `npm run c`
=> fix(hub-common): fixes a type error when checking if additional resource is an item data source

packages/common/e2e/hub-projects.e2e.ts, packages/common/e2e/hub-sites.e2e.ts, packages/common/src/search/filter-utils.ts, packages/common/src/search/index.ts, packages/common/src/search/types/IHubSearchResponse.ts, packages/common/src/search/types/index.ts, packages/common/src/search/types/types.ts, packages/common/src/search/utils.ts, packages/common/test/projects/HubProjects.test.ts, packages/common/test/search/filter-utils.test.ts, packages/common/test/search/group-utils.test.ts, packages/common/test/search/utils.test.ts, packages/teams/e2e/create-teams.e2e.ts
Adds generic function for expanding filters `expandFilter<T>(filter: T): T` which takes the flexible Filter<T> structure and "expands" all the props into `IMatchOptions` or `IDateRange<number>` which simplifies deterministic serialization into Hub or Portal API requests.
Also adds function to serialize an array of `IFilterGroup<T>` to `ISearchOptions` for portal
`serializeFilterGroupsForPortal(filterGroups: Array<IFilterGroup<FilterType>>): ISearchOptions`
This is on-going work pulling hacked functions from a spike branch up into robust tested code.
Once everything is done, we can remove *many* of the FilterType specific functions, but we're not there yet.
- run tests
1. [x] PR title follows semantic commit …
=> feat: add FilterGroup functions

packages/initiatives/src/groups.ts
- add missing closing paren in `checkGroupExists` query
=> fix(hub-initiatives): add missing closing paren in checkGroupExists

packages/common/src/search/types/IFacet.ts
Part of https://devtopia.esri.com/dc/hub/issues/3558
=> feat(hub-common): add orderBy field to the IFacet interface

package-lock.json, packages/common/src/content/_internal.ts, packages/common/src/content/compose.ts, packages/common/src/extent.ts, packages/common/src/types.ts, packages/common/test/compose.test.ts, packages/common/test/content.test.ts, packages/common/test/content/fetch.test.ts
add some utils for working with extents, and 
also add center and spatialReference to content.boundary
also add missing content.boundary.geometry.type
1. Closes Issues: part of [2154](https://devtopia.esri.com/dc/hub/issues/2154)
=> feat: add bBoxToExtent(), extentToPolygon(), and getExtentCenter() utils

packages/common/src/search/collectionState.ts, packages/common/src/search/convertCatalog.ts, packages/common/src/search/types/ICatalog.ts, packages/common/src/search/types/ICollection.ts, packages/common/test/search/collectionState.test.ts, packages/common/test/search/convertCatalog.test.ts
For the gallery card use-case, we need `ICollection` to support an arbitrarily complex "scoping filter". However, the current `.filter` is to simple to meet this need. This, this adds `scope?: Array<IFilterGroup<FilterType>>;` to both `ICollection` and `ICatalog`. This enables the required level of complexity.
Also fixes an issue where the collection state serializer would fail if the collection did not have `.filters:[]`. 
- run tests
=> feat: add scope to ICatalog and ICollection

package-lock.json, packages/common/src/content/_internal.ts, packages/common/src/content/compose.ts, packages/common/src/core/types/IHubContent.ts, packages/common/src/index.ts, packages/common/src/items/_enrichments.ts, packages/common/src/org/fetch-org.ts, packages/common/src/org/index.ts, packages/common/test/compose.test.ts, packages/common/test/content.test.ts, packages/common/test/items/_enrichments.test.ts, packages/common/test/org/fetch-org.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/2932.
Fetch org enrichment in fetchContent and add fallback logic for publisher in composeContent
=> feat(hub-common): fetch org enrichment in fetchContent and add fallback logic for publisher in composeContent

package-lock.json, packages/common/src/search/filter-utils.ts, packages/common/src/search/types/types.ts, packages/common/test/search/filter-utils.test.ts
Some portal search api's utilize properties other than `q` for specific searches - for example, `searchUserAccess` needs to be sent as a separate parameter when doing a group search.
This PR changes FilterGroup serialization to account for this via an allow-list of properties that will be passed through to the `ISearchOptions` object.
Note: this does not address the use of `filter` for exact matching. Although useful, `filter` is an "overriding" AND with the other filter components that are in the `q` parameter. This makes it difficult to work with `filter` as part of dynamic facets which may be combined with other query components.
run tests …
=> fix: allow specific props to flow through to ISearchOptions

packages/common/src/content/_internal.ts, packages/common/src/core/types/IHubContent.ts, packages/common/test/compose.test.ts, packages/common/test/content.test.ts
Missed AC from https://github.com/ArcGIS/opendata-ui/pull/10731
Also fixes issue where I mixed up metadata.contact with metadata.resource.contact
=> feat(hub-common): add metadata.contact as a possible source for IHubContent's publisher field and add isExternal flag

packages/common/src/resources/_internal/_validate-url-helpers.ts
seems typedoc doesn't like double curlies in type comments
=> chore: fix broken docs:build script

package-lock.json, packages/common/src/content/_fetch.ts, packages/common/src/content/fetch.ts, packages/common/src/core/types/IServerEnrichments.ts, packages/common/test/content/_fetch.test.ts, packages/common/test/content/fetch.test.ts
Always fetching the live record count is proving very costly for some feature servers. In the long run, we will remove this from `fetchContent()` so that the fetch can be deferred and not block page load. For now, `fetchContent()` will still return a `recordCount`, but we'll rely on the cached value from the Hub API when it's available, which should be for any non-enterprise public layer.
1. Closes Issues:  addresses [3976](https://devtopia.esri.com/dc/hub/issues/3976)
=> perf(hub-common): fetchContent returns cached recordCount when it can

packages/common/src/search/Collection.ts, packages/common/src/search/convertCatalog.ts, packages/common/src/search/types/IHubCatalog.ts, packages/common/test/search/convertCatalog.test.ts
- update the `convertCatalog` function to return `IHubCatalog` 
- add `schemaVersion` prop to `IHubCatalog`
- add `targetEntity` to IHubCollection
- run tests
=> fix: update convertCatalog to return latest structure

packages/common/src/content/compose.ts, packages/common/test/content.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/3872
The old 'briefcase' alias seems to be broken in opendata-ui. Switching to the standard 'projects' icon name.
=> fix(hub-common): fixed icon name for hub projects

packages/common/src/search/_internal/index.ts, packages/common/src/search/_internal/portalSearchGroups.ts, packages/common/src/search/_internal/portalSearchItems.ts, packages/common/src/search/_internal/portalSearchUsers.ts, packages/common/src/search/ifilter-utils.ts, packages/common/src/search/index.ts, packages/common/test/search/ifilter-utils.test.ts
Allow export of a serializer for client use
2. [x] used semantic commit messages
3. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation will not run!)
=> fix(hub-common): fix export of a serialization function

package-lock.json, packages/common/src/search/_internal/portalSearchGroups.ts, packages/common/src/search/_internal/portalSearchItems.ts, packages/common/src/search/_internal/portalSearchUsers.ts, packages/common/src/search/index.ts, packages/common/src/search/serializeQueryForPortal.ts, packages/common/test/search/serializeQueryForPortal.test.ts
In some scenarios, the serialization of some predicates would result in having `AND AND` in the `q`. This PR resolve that problem, and renamed `ifilter-utils.ts` to `serializeQueryForPortal.ts` as that's the only exported function.
- Run tests
=> fix: resolve null predicate issue; rename file

packages/common/src/search/_internal/portalSearchItems.ts, packages/common/test/search/_internal/portalSearchItems.test.ts
While working with the `arcgis-hub-catalog` component, I noticed the `$application` well known type query was incorrect. The issue was that the `filter` needs to use the `OR` operation in order for the well-known-type predicates to work.
This simply ensures that is the case.
- run tests
1. Closes Issues: Just fixed it
=> fix: correct $application well-known-type

packages/teams/src/utils/can-user-create-team-in-product.ts, packages/teams/src/utils/can-user-create-team.ts, packages/teams/src/utils/getOrgGroupLimit.ts, packages/teams/test/utils/can-user-create-team-in-product.test.ts
Allow for customized group limits for some orgs. Hub team must be informed of group limit changes, but this enables simple per-org limit customization; includes the two initial orgs.
- run tests
1. Closes Issues: #4389 (if appropriate)
=> feat: allow custom org group limits

packages/common/src/core/types/IHubTimeline.ts
see [4362](https://devtopia.esri.com/dc/hub/issues/4362) for more details
see corresponding [PR](https://github.com/Esri/hub-components/pull/564) in `hub-components`
- update `IHubStage` to optionally include a `link` property
- update `IHubTimeline` to include a `schemaVersion` property
=> feat: update IHubStage to optionally include a link property

packages/common/e2e/entity-search.e2e.ts, packages/common/src/org/fetchOrgLimits.ts, packages/common/src/org/index.ts, packages/common/test/org/fetchOrgLimits.test.ts
Adds low-level functions to fetch org limits generally and to fetch the specific MaxNumUserGroups limit. This will be needed for upcoming work
1. Part of Issues:  https://devtopia.esri.com/dc/hub/issues/4389
=> feat: fetch org limits functions

package-lock.json, packages/teams/src/utils/getOrgGroupLimit.ts
Got additional orgids for SCE that also have group max bumped to 700
=> fix: add more orgs with 700 group max

packages/common/src/search/serializeQueryForPortal.ts, packages/common/test/search/serializeQueryForPortal.test.ts
During the last refactor I missed enabling `capabilities` as a searchable field for groups
- run tests - there is a test specifically for this property now
=> fix: enable searching groups by shared edit

demos/ember-app/README.md, demos/ember-app/ember-cli-build.js, demos/ember-app/package.json, demos/node/package.json, demos/webpack/README.md, demos/webpack/package.json, demos/webpack/webpack.config.js, package-lock.json, package.json, packages/common/package.json, packages/discussions/package.json, packages/downloads/package.json, packages/events/package.json, packages/initiatives/package.json, packages/search/package.json, packages/sites/package.json, packages/surveys/package.json, packages/teams/package.json, umd-base-profile.js
affects: ember-app, webpack-demo, @esri/hub-common, @esri/hub-discussions, @esri/hub-downloads,
@esri/hub-events, @esri/hub-initiatives, @esri/hub-search, @esri/hub-sites, @esri/hub-surveys,
@esri/hub-teams
no longer publish es5 build
no longer publish es5 build
if tests pass, let'r rip
1. Closes Issues: Part of https://devtopia.esri.com/dc/hub/issues/3851
=> chore(hub-common): no longer publish es5 build

package-lock.json, packages/downloads/package.json
affects: @esri/hub-downloads
make rest-js packages peer dependencies
1. Closes Issues: Part of https://devtopia.esri.com/dc/hub/issues/3851
=> feat(hub-downloads): make rest-js packages peer dependencies

package-lock.json, packages/common/src/search/serializeQueryForPortal.ts, packages/common/test/projects/HubProjects.test.ts, packages/common/test/search/_internal/portalSearchGroups.test.ts, packages/common/test/search/_internal/portalSearchItems.test.ts, packages/common/test/search/_internal/portalSearchUsers.test.ts, packages/common/test/search/serializeQueryForPortal.test.ts
1. Description: Fixes an issue with search. What I was seeing was that when I sent in a query that contained a filter like:
```js
{
operation: "OR",
predicates: ['$app', '$webmap']
};
```
The well known type filters would get combined in such a way that they could negate each other or otherwise produce incorrect results. What needed to happen was for each predicate to be wrapped in parens so they would be handled as a block when they were combined with others with an `AND' or an 'OR'.
1. Instructions for testing: run the tests
=> fix: predicates need to be wrapped in parens

packages/surveys/src/utils/index.ts
Some exports were mistakenly removed > year ago, but we never noticed b/c opendata-ui was not picking up later versions of `@esri/hub-surveys`. Now that we are doing a breaking chance and bumping all packages, this became a problem
- run tests
=> fix: re-export survey utils

package-lock.json, packages/common/src/core/types/IHubItemEntity.ts, packages/common/src/projects/HubProjectManager.ts, packages/common/src/projects/HubProjects.ts, packages/common/src/sites/HubSites.ts, packages/common/test/projects/HubProjectManager.test.ts
=> feat(hub-common) project access and share/unshare groups

karma.conf.js, package-lock.json, packages/common/src/items/_internal/_wait-for-item-ready.ts, packages/common/src/search/_internal/portalSearchUsers.ts, packages/common/test/items/_wait-for-item-ready.test.ts, packages/common/test/search/_internal/portalSearchUsers.test.ts
Tests now run in ~3s for me locally compared w/ ~12s before.
Also cleans up tests that were using `async` and `done()` which was causing warnings in the node output, and documents how to use the spec reported to identify slow-running tests.
1. Closes Issues: [4540](https://devtopia.esri.com/dc/hub/issues/4540)
=> chore: identify and fix slow running tests

packages/common/src/resources/_internal/_validate-url-helpers.ts, packages/common/test/ArcGISContextManager.test.ts
Also updates `isUrl()` error message to be more accurate.
=> chore(hub-common): remove some logging messages from the test results

packages/common/src/collections.ts, packages/common/src/content/get-family.ts, packages/common/test/collections.test.ts, packages/common/test/content/get-family.test.ts
[4533](https://devtopia.esri.com/dc/hub/issues/4533). Hub Site OGC APIs currently can return (and search using) user-defined collections that are scoped to the site's catalog. However, Hub also currently has "default" collections on the search route, with each collection as a bucket of different types. The story represents the effort to introduce these collections as default collections that are automatically returned from Site OGC APIs.
While the terminology of this story refers to collections (which are defined and recognized resources within the OGC spec), the _actual_ collections we plan to include are MUCH more akin to non-configurable Hub Families than configurable collections. They are more aligned with resource types that will have their …
=> feat(hub-common): introduces a getFamilyTypes function

packages/common/e2e/hub-project-class.e2e.ts, packages/common/src/core/PermissionManager.ts, packages/common/src/core/behaviors/IWithPermissionBehavior.ts, packages/common/src/core/traits/IWithCatalogDefinition.ts, packages/common/src/core/traits/IWithPermissions.ts, packages/common/src/core/types/IHubProject.ts, packages/common/src/projects/HubProject.ts, packages/common/src/projects/HubProjectManager.ts, packages/common/src/projects/HubProjects.ts, packages/common/src/projects/defaults.ts, packages/common/test/core/PermissionManager.test.ts, packages/common/test/core/behaviors/PermissionBehavior.test.ts, packages/common/test/projects/HubProject.test.ts, packages/common/test/projects/HubProjects.test.ts
- since we are not exposing the underlying entity props on the classes, we can store the catalog and permissions as `.catalog` and `.permissions`
- remove the redundant `HubPermission` param on `addPermission` method
- run tests
=> fix: rename permission, catalog props and simplify adding permission

packages/common/e2e/hub-project-class.e2e.ts, packages/common/src/core/HubItemEntity.ts, packages/common/src/core/_internal/getBasePropertyMap.ts, packages/common/src/core/behaviors/IWithThumbnailBehavior.ts, packages/common/src/core/types/IHubItemEntity.ts, packages/common/src/initiatives/HubInitiative.ts, packages/common/src/items/setItemThumbnail.ts, packages/common/src/projects/HubProject.ts, packages/common/test/core/HubItemEntity.test.ts
Add thumbnail behavior to `HubItemEntity` base class, and connect that into existing classes
See https://devtopia.esri.com/dc/hub/issues/4708 for details
This also adds getters for `id` and `owner` to `HubItemEntity` base class as those are quite useful
1. Closes Issues: #4708
=> feat: thumbnail behavior

package-lock.json, packages/common/src/content/get-family.ts, packages/common/test/content/get-family.test.ts
Discovered while working on https://devtopia.esri.com/dc/hub/issues/3904
Just returns a missing type for the `template` family
=> fix(hub-common): getFamilyTypes() now correctly returns "Hub Initiative Template" as a type of the "template" family

package-lock.json, packages/discussions/src/index.ts, packages/discussions/src/types.ts, packages/discussions/src/utils/channels/can-post-to-channel.ts, packages/discussions/src/utils/channels/index.ts, packages/discussions/src/utils/posts.ts, packages/discussions/test/utils/channels/can-post-to-channel.spec.ts, packages/discussions/test/utils/channels/index.spec.ts, packages/discussions/test/utils/posts.test.ts
* fix(): canModifyPost should match creator to username.
* feat(): canModifyPostStatus - a specific auth method for modifying a post's status
* refactor(): canPostToChannel to partially leverage channel ACL
* BREAKING CHANGE: changed signature of canModifyPost, because it no longer requires the `channel` param
* 
Run unit tests
=> fix(): update discussion auth methods

karma.conf.js, package-lock.json, packages/common/package.json, packages/common/src/core/HubItemEntity.ts, packages/common/src/core/behaviors/IWithEditorBehavior.ts, packages/common/src/core/behaviors/index.ts, packages/common/src/core/index.ts, packages/common/src/core/schemas/hubproject.ts, packages/common/src/core/schemas/index.ts, packages/common/src/core/schemas/internal/applyUiSchemaElementOptions.ts, packages/common/src/core/schemas/internal/filterSchemaToUiSchema.ts, packages/common/src/core/schemas/internal/getUiSchemaProps.ts, packages/common/src/core/schemas/internal/index.ts, packages/common/src/core/schemas/internal/subsetSchema.ts, packages/common/src/core/schemas/types.ts, packages/common/src/initiatives/HubInitiative.ts, packages/common/src/objects/deepGetPropValues.ts, packages/common/src/projects/HubProject.ts, packages/common/src/projects/HubProjects.ts, packages/common/src/projects/schemas.ts, packages/common/test/core/schemas/internal/applyUiSchemaElemetOptions.test.ts, packages/common/test/core/schemas/internal/filterSchemaToUiSchema.test.ts, packages/common/test/core/schemas/internal/getUiSchemaProps.test.ts, packages/common/test/core/schemas/internal/subsetSchema.test.ts, packages/common/test/objects/deepGetPropValues.test.ts, packages/common/test/projects/HubProject.test.ts, packages/common/test/projects/HubProjects.test.ts, tsconfig.json
Expose `.getEditorConfig(...)` as static method on Hub entity classes.
This is a rough first pass implementation to get feedback. Will polish once assumptions have been validated.
Some things to consider:
- adding schemas to hub.js required importing Ajv and json-schema-typed. Since we're just using those for types, I *hope* nothing else gets bundled into the build - @tomwayson should/could we make these devDeps?
- another solution here is to put all this into a util fn in hub-components, and fiddle with adding static methods to the classes. While nominally less ergonomic, I'm not sure it's ZOMG worse, and keeps UI layer concerns in the UI layer.
1. [ ] PR title …
=> feat: add editor config static method to HubProject class

package-lock.json, packages/common/src/extent.ts, packages/common/src/models/index.ts, packages/common/src/projects/HubProjects.ts, packages/common/test/models/models.test.ts
1. Description: project create/update call the addItem and update endpoints which both expect extent as a string, not a bbox.
=> feat: project extents are converted to strings on create/update

packages/common/src/content/HubContent.ts, packages/common/src/pages/HubPages.ts, packages/common/src/projects/HubProjects.ts, packages/common/src/search/types/IHubSearchResult.ts, packages/common/src/sites/HubSites.ts, packages/common/test/content/HubContent.test.ts, packages/common/test/pages/HubPages.test.ts, packages/common/test/projects/HubProjects.test.ts, packages/common/test/sites/HubSites.test.ts
Add tags and categories to item-backed search results and to the IHubSearchResult interfaces.
Part of [4822](https://devtopia.esri.com/dc/hub/issues/4822)
=> feat(hub-common): add tags and categories to item-backed search results and to IHubSearchResult

packages/common/src/search/_internal/expandPredicate.ts, packages/common/src/search/serializeQueryForPortal.ts, packages/common/test/search/serializeQueryForPortal.test.ts
sending a predicate with `categories` was adding that into the `q` which the portal does not respect, and thus ignores. This correctly serializes it into a separate property which is sent as a separate form field in the search request
run rests
=> feat: support serializing categories into separate param

packages/common/src/utils/index.ts, packages/common/src/utils/titleize.ts, packages/common/test/utils/titleize.test.ts
=> feat(hub-common): add titleize to utils

packages/discussions/src/utils/channels/can-post-to-channel.ts, packages/discussions/test/utils/channels/can-post-to-channel.spec.ts
Alter the canPostToDiscussion util so that during "authorization by group" (i.e. user's group matches channel group), we check that the group has not been tagged with typeKeyword `cannotDiscuss` which is a flag that users of this group are not allowed to participate in discussions.
Added units tests, so we are covered.
Doesn't fully close, but contributes to: https://zentopia.esri.com/workspaces/engagement-workspace-61508ae50946c40014ef574f/issues/dc/hub/4751
=> feat(hub-discussions): check groups for cannotDiscuss

packages/common/src/core/schemas/hubproject.ts, packages/common/src/core/types/IHubProject.ts, packages/common/src/projects/defaults.ts, packages/common/test/projects/HubProjects.test.ts
update Hub Project status defaults and interface enum values
=> fix: project status defaults

package-lock.json, packages/common/src/projects/defaults.ts
For https://devtopia.esri.com/dc/hub/issues/4906
New projects should not have a default description.
=> fix: projects do not have a default description

packages/common/e2e/deep-contains.e2e.ts, packages/common/e2e/hub-sites-contains.e2e.ts, packages/common/src/core/types/IHubProject.ts, packages/common/src/core/types/IHubSite.ts, packages/common/src/sites/HubSite.ts, packages/common/src/sites/HubSites.ts, packages/common/src/sites/defaults.ts, packages/common/test/sites/HubSite.test.ts, packages/common/test/sites/HubSites.test.ts
Implement just enough of HubSite class so we can create an instance in the app, and use the `.contains(...)` method on the content routes. 
Issue: [4869](https://devtopia.esri.com/dc/hub/issues/4869)
- run tests and/or `hub-sites-contains.e2e.ts`
=> feat: add HubSite class with .contains

packages/common/src/sites/HubSites.ts
This extracts part of the `HubSites::fetch` fn into a separate fn that will just convert a IModel into an IHubSite. This greatly streamlines usage in OpenData-ui
=> fix: refactor so conversion of model to ihubsite is separate fn

package-lock.json, packages/common/package.json
Description:
- bumps adlib in hub-common to fix issue where leading 0s are removed
=> fix(hub-common): bumps adlib to fix leading 0 removal issue

packages/common/src/core/types/IHubTimeline.ts
Add a new collapse prop to IHubTimeline, so we could sync its value between the timeline and timeline editor. Issue: [4747](https://zentopia.esri.com/workspaces/collaboration-sprint-board-614f9bfc0946c40011ef574e/issues/dc/hub/4747)
=> feat(hub-common): add collapse to IHubTimeline

packages/common/src/core/schemas/hubproject.ts
remove references to `subtype` in project schema. See [refactor PR](https://github.com/Esri/hub-components/pull/755) in `hub-components` for more details
=> fix: remove all references to subtype in project schema

packages/sites/src/drafts/site-draft-include-list.ts
- allows `headContent` to be saved in site drafts
=> feat: adds headContent to draft allow list

packages/common/src/core/types/IHubTimeline.ts
rename collapse to isCollapsible in IHubTimeline
=> fix(hub-common): rename collapse to canCollapse in IHubTimeline

packages/common/src/core/types/IHubTimeline.ts
Rename stage description to stageDescription so it doesn't cause an error when adding a timeline to project (having the same same as project's description)
1. Closes Issues: #<5083> (if appropriate)
=> fix: rename stage description to stageDescription

packages/discussions/src/channels.ts, packages/discussions/src/types.ts, packages/discussions/test/channels.test.ts
Description: Adds methods for channel opt out and activity routes.
=> feat(hub-discussions): create methods for notifications opt out

package-lock.json, packages/common/src/core/_internal/getBasePropertyMap.ts, packages/common/src/models/index.ts, packages/common/test/models/models.test.ts
1. Description: Adds `clearEmptyFields` to `getBasePropertyMap` so that empty fields can be cleared.
=> fix: allows for project fields to be cleared out

package-lock.json, packages/common/src/core/HubItemEntity.ts, packages/common/src/core/_internal/getBasePropertyMap.ts, packages/common/src/core/schemas/hubproject.ts, packages/common/src/core/traits/IWithViewSettings.ts, packages/common/src/core/traits/index.ts, packages/common/src/core/types/IHubItemEntity.ts, packages/common/src/core/types/IHubProject.ts, packages/common/src/core/types/index.ts, packages/common/test/core/HubItemEntity.test.ts
1. Description: expands project edit schema with featuredImage support. Adds featuredImageUrl to getBasePropertyMap bc I forgot about it.
=> feat: project edit schema supports featured image

package-lock.json, packages/common/src/util.ts, packages/common/test/util.test.ts
1. Description: cloneObject thusfar has not supported Blob's. This adds that support.
=> fix: cloneObject supports blobs

packages/common/src/ArcGISContext.ts, packages/common/src/permissions/_internal/checkAlphaGating.ts, packages/common/src/permissions/_internal/getPolicyResponseCode.ts, packages/common/src/permissions/types/IPermissionPolicy.ts, packages/common/src/permissions/types/PolicyResponse.ts, packages/common/src/projects/defaults.ts, packages/common/src/sites/HubSites.ts, packages/common/src/sites/_internal/applyPermissionMigration.ts, packages/common/test/ArcGISContextManager.test.ts, packages/common/test/permissions/_internal/checkAlphaGating.test.ts, packages/common/test/permissions/_internal/getPolicyResponseCode.test.ts, packages/common/test/sites/_internal/applyPermissionMigration.test.ts
- add a proto-migration that derives site's permissions hash for `hub:project:create` based on the contentGroupId stored on the site. Currently, this is always applied when an `IModel` is transformed into an `IHubSite`. Once we have a UX for permission management, we will run this one can bump the schema version when complete.
- adds support for `alpha` in the `IPerissionPolicy` structure, allowing us to gate access to alpha orgs, and creating a pattern for other flagging
1. Instructions for testing: Run tests
=> refactor: site permission migration and alpha org

package-lock.json, packages/discussions/src/types.ts, packages/discussions/src/utils/channels/can-post-to-channel.ts
- rename existing `IChannelAcl` => `IChannelAclObject`
- create interface `IChannelAcl` with new permissions structure
- add `channelAcl` property to interface `IChannel`
=> feat(hub-discussions): add type IChannelAcl

packages/discussions/src/types.ts
- add interface for channel-acl update definition
- remove channelId from channel-acl definition interface
=> feat(hub-discussions): add channel-acl update definition

packages/discussions/src/types.ts
1. Description: change type for `restrictedBefore` from Date to string
=> fix(hub-discussions): change restrictedBefore type to string

packages/discussions/src/utils/channel-permission.ts, packages/discussions/src/utils/channels/can-create-channel.ts, packages/discussions/src/utils/channels/can-post-to-channel.ts, packages/discussions/src/utils/platform.ts, packages/discussions/test/utils/channel-permission.test.ts, packages/discussions/test/utils/channels/can-create-channel.test.ts, packages/discussions/test/utils/channels/can-post-to-channel.test.ts
1. Description: check permissions for canPostToChannel by `channel.channelAcl` if it's available
=> feat(hub-discussions): add channelAcl support to canPostToChannel

packages/common/src/core/schemas/hubproject.ts
1. Description: adds a maxHeight to the edit project schema for the image picker. The component in question distorts images if you do not provide both a maxWidth and a maxHeight
=> fix: project edit schema image picker config has a maxHeight

packages/common/src/content/_internal.ts, packages/common/src/content/compose.ts, packages/common/src/content/index.ts, packages/common/test/content.test.ts
Moves isSiteType from _internal to index to allow for consumables to use it.
2. Works on issue [5348](https://zentopia.esri.com/workspaces/polaris-sprint-board-614a18b38a61a3001196c48d/issues/dc/hub/5348). 
=> feat(): move isSiteType to index to allow consumables to use

package-lock.json, packages/common/src/core/schemas/hubproject.ts
Simply bumps the stepper header size.
=> fix: update stepper scale to l

packages/discussions/src/types.ts
1. Description: add `channelAcl` to the ChannelRelation enum, which can be used to optionally include `channelAcl` permissions on the channel reponse
=> feat(hub-discussions): add channelAcl as a possible channel relation

packages/common/src/core/schemas/hubproject.ts, packages/common/src/core/traits/IWithViewSettings.ts
Rename relatedItem to featuredContent in all project related files
1. Closes Issues: 
Partial [5681](https://zentopia.esri.com/workspaces/collaboration-sprint-board-614f9bfc0946c40011ef574e/issues/dc/hub/5681)
=> fix: rename relatedItem to featuredContent in project

packages/common/src/core/schemas/hubproject.ts, packages/common/src/core/traits/IWithViewSettings.ts, packages/common/src/projects/_internal/getPropertyMap.ts, packages/common/src/projects/defaults.ts, packages/common/src/projects/edit.ts
- [5633](https://devtopia.esri.com/dc/hub/issues/5633): Store UX/UI related properties (properties directly consumed by the Project view) on `item.data.view` and `project.view` rather than directly on `item.data` and at the top-level of the project entity
- update the project entity and model defaults
- update the model <> entity mappings
- update relevant properties in the project `schema`/`uiSchema`
- [5730](https://devtopia.esri.com/dc/hub/issues/5730): While I was already in here, I decided to refine the styling/structure of the project create/edit forms by updating the relevant `schema`/`uiSchema` properties
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation …
=> fix(hub-common): update project property mappings and schemas

packages/common/src/search/wellKnownCatalog.ts, packages/common/test/search/wellKnownCatalog.test.ts
- Take care when i18nScope is undefined case in dotifyString
- Pluralize "documents" in translation path
- Remove an extra line in test I forgot to remove in my previous PR
=> fix(hub-common): take care when i18nScope is undefined case in dotifyString

packages/common/src/search/wellKnownCatalog.ts, packages/common/test/search/wellKnownCatalog.test.ts
In `getWellKnownCatalog`, when the `i18nScope` is defined and ending with '.', we are returning "" now, but for cases like when the `i18nScope` is `catalog.`, we will want to return that instead of "". 
=> fix(hub-common): fix what dotifyString returns when i18nScope is defined and ending with '.'

.gitignore, package-lock.json, package.json, packages/common/e2e/catalog-collection.e2e.ts, packages/common/e2e/deep-contains.e2e.ts, packages/common/e2e/hub-project-class.e2e.ts, packages/common/e2e/hub-sites-contains.e2e.ts, packages/common/e2e/permissions.e2e.ts, packages/common/src/ArcGISContext.ts, packages/common/src/capabilities/checkCapability.ts, packages/common/src/content/_fetch.ts, packages/common/src/content/compose.ts, packages/common/src/core/_internal/deepContains.ts, packages/common/src/core/fetchHubEntity.ts, packages/common/src/core/getTypeFromEntity.ts, packages/common/src/core/types/IHubProject.ts, packages/common/src/initiatives/HubInitiative.ts, packages/common/src/initiatives/HubInitiatives.ts, packages/common/src/initiatives/index.ts, packages/common/src/projects/HubProject.ts, packages/common/src/projects/edit.ts, packages/common/src/projects/fetch.ts, packages/common/src/sites/HubSites.ts, packages/common/test/capabilities/checkCapability.test.ts, packages/common/test/core/fetchHubEntity.test.ts, packages/common/test/initiatives/HubInitiatives.test.ts, packages/common/test/sites/HubSites.test.ts, support/graph.js
The e2e tests stopped working, complaining about functions not existing. After a lot of digging around, it was determined that the use if `from "../../index"` type imports were the cause.
This PR resolves the imports which were causing the e2es to fail, and also addressed some snarly imports related to projects and sites.
It also adds `madge` and a script for generating dependency tree svgs. This is really rough tooling at this point, and requires  installing graphviz on the machine running this. More info -> https://github.com/pahen/madge
Madge was used to locate a few circular deps - I resolved two of them, and assigned the third to @sonofflynn89 
At this point, all tests pass in node & browser, and all e2e's pass.
run all tests
1. Closes …
=> chore: fix imports so e2e tests pass 

packages/common/src/models/index.ts, packages/common/test/models/models.test.ts, packages/common/test/projects/projects.test.ts
1. Description: Resolves issue where if resource didn't exist during project fetch it would hard fail. Also no longer refetches resource during creation/edit and instead opts with the resources passed into the func.
=> fix: refactor fetchModelResources to failSafe

packages/common/src/content/get-family.ts, packages/common/test/content/get-family.test.ts, packages/common/test/search/wellKnownCatalog.test.ts
Issue: [5582](https://devtopia.esri.com/dc/hub/issues/5582)
This was changed as part of https://confluencewikidev.esri.com/x/KYJuDg. `getFamilyTypes` now returns "Feature Service" as part of the "Dataset" family. As a result, `getFamilyTypes` is now temporarily out of sync with `getFamily`. …
=> feat(hub-common): modify getFamilyTypes to return "Feature Service" as part of the "Dataset" family

package-lock.json, packages/common/src/versioning/updateVersion.ts, packages/common/src/versioning/utils.ts, packages/common/test/versioning/updateVersion.test.ts
1. Description: Proposed approach for checking for stale versions on update.
1. Instructions for testing: Looking for input on the general approach and naming.
=> feat: throw error when attempting to update a stale version

packages/common/src/items/slugs.ts, packages/common/test/items/slugs.test.ts
Search results return a subset of properties, e.g. `orgId` is returned on results from `getItem` but not `searchItems`. This PR refactors `getItemBySlug` method to issue a subsequent `getItem` request so we get the full AGO item + props.
1. Closes Issues: [5906](https://devtopia.esri.com/dc/hub/issues/5906) …
=> fix(): getItemBySlug returns full item via getItem

docs/src/guides/advanced/queries-and-filters.md, packages/common/src/search/_internal/commonHelpers/getTopLevelPredicate.ts, packages/common/src/search/_internal/expandPredicate.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/getQQueryParam.ts, packages/common/src/search/serializeQueryForPortal.ts, packages/common/test/search/_internal/getTopLevelPredicate.test.ts, packages/common/test/search/_internal/hubSearchItems.test.ts, packages/common/test/search/_internal/portalSearchItems.test.ts
Adds `bbox` as a valid parameter for portal-based item searches of `hubSearch`.
There are some special rules for using a `bbox` predicate within an `IQuery`:
- Only ONE filter can have a predicate with the target field
- Only ONE predicate with the target field can exist
- The predicate can only be ANDed to other predicates
- The predicate value must be a string representation of a bbox (i.e. `"1,2,3,4") …
=> feat(hub-common): add bbox search to portal-based item searches

.github/pull_request_template.md
Updates PR to remind devs to add TSDoc to methods
None
[#5436](https://devtopia.esri.com/dc/hub/issues/5436)
=> chore(hub-common): added pr action to update tsdoc

packages/common/src/versioning/_internal/constants.ts, packages/common/src/versioning/createVersion.ts, packages/common/src/versioning/types/ICreateVersionOptions.ts, packages/common/src/versioning/types/IVersionMetadata.ts, packages/common/test/mocks/versioning/resources.json, packages/common/test/versioning/createVersion.test.ts, packages/common/test/versioning/searchVersions.test.ts, packages/common/test/versioning/versionMetadataFromResource.test.ts
1. Description: entity versions now have descriptions
1. Closes Issues: #6340 (if appropriate)
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release …
=> feat: versions have descriptions

docs/src/guides/functional/versioning.md, packages/common/src/core/behaviors/IWithVersioningBehavior.ts, packages/common/src/sites/HubSite.ts, packages/common/src/versioning/index.ts, packages/common/src/versioning/updateVersionMetadata.ts, packages/common/test/sites/HubSite.test.ts, packages/common/test/versioning/updateVersionMetadata.test.ts
1. Description: adds updateVersionMetadata function and class method for updating only the version's metadata (primarily name and description). This is because you might want to do that at a time when all you have is an `IVersionMetadata`.
1. Instructions for testing: Run the tests?
1. Closes Issues: [5447](https://devtopia.esri.com/dc/hub/issues/5447a)
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated …
=> feat: updateVersionMetadata

packages/common/src/core/types/IHubItemEntity.ts, packages/common/src/projects/_internal/ProjectSchema.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts
- Add an optional `categories` prop in `IHubItemEntity`, this is needed for the Categories field on Project and will be useful for future item related features.
- Add "Tags" and "Categories" to ProjectSchema and ProjectUiSchemaEdit so we can add those two comboxbox fields to Project
After testing them in hub-components:
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation will …
=> feat(hub-common): add optional categories prop to IHubItemEntity

package-lock.json, packages/common/src/sites/_internal/_migrate-event-list-card-configs.ts, packages/common/test/sites/_internal/_migrate-event-list-card-configs.test.ts
1. Description: Fixes a bug where hub.py sites were failing to load.
1. Closes Issues: #6404
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release instructions …
=> fix(hub-common): adjust event list card migration to work with alternative site models

packages/common/package.json, packages/common/src/core/_internal/configureBaseResources.ts, packages/common/src/projects/_internal/ProjectSchema.ts, packages/common/src/projects/_internal/ProjectUiSchemaCreate.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts, packages/common/src/projects/_internal/getPropertyMap.ts, packages/common/src/projects/edit.ts, packages/common/src/projects/fetch.ts, packages/common/test/models/models.test.ts, packages/common/test/projects/projects.test.ts
1. Description: Project.location is stored in item.properties.location. rolls back resources behaviors in projects for the time being. …
=> feat: project.location is stored in item.properties.location

package-lock.json, packages/discussions/src/types.ts
settings is no longer an available ChannelRelation
1. Description: Remove `settings` from enum ChannelRelation. This service will be updated to return the channel settings fields by default, without having to specify the `relations` query parameter
1. [x] updated `peerDependencies` as needed. **CRITICAL** …
=> feat(hub-discussions): remove settings from ChannelRelation

packages/common/src/core/_internal/PropertyMapper.ts, packages/common/src/objects/deep-set.ts, packages/common/src/objects/set-prop.ts, packages/common/test/objects/set-prop.test.ts, packages/common/test/projects/projects.test.ts, packages/common/test/utils/deep-set.test.ts
1. Description: deepSet previously did a merge of old/new, rather than a replace. That's fine for non-object values, but cases where we might want to go from a fleshed out object to it's 'null' equivalent need a replace path.
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update …
=> feat: deepSet and setProp support replace for objects

packages/common/src/projects/_internal/ProjectBusinessRules.ts
Because we wanted to add a gating to non project owners for project settings panel, we would need to add a new project owner permission so the workspace link definitions can filter it out before rendering the navigation
1. Closes Issues: [5790](https://zentopia.esri.com/workspaces/collaboration-sprint-board-614f9bfc0946c40011ef574e/issues/dc/hub/5790)
1. …
=> feat: add new hub:project:owner permission and update project settings with it

packages/common/src/versioning/updateVersionMetadata.ts, packages/common/test/versioning/updateVersionMetadata.test.ts
1. Description: adds owner param to updateItemResource call in updateVersionMetadata
1. Closes Issues: [6540](https://devtopia.esri.com/dc/hub/issues/6540) …
=> fix: updateVersionMetadata sends owner param

package-lock.json, packages/discussions/src/posts/posts.ts, packages/discussions/test/posts.test.ts
- `searchPosts` needs to serialize the `geometry` parameter before issuing the `GET /v1/posts` request since so it gets encoded correctly. …
=> fix(): serialize geometry parameter for searchPosts call

packages/discussions/src/posts/posts.ts, packages/discussions/test/posts.test.ts
[1034](https://github.com/Esri/hub.js/pull/1034) introduced a regression. Using `cloneObject` had an unanticipated side-effect of converting `UserSession` instances to POJOs which caused issues when `searchPosts` was called. This takes a slightly different approach to not mutating the provided `options` argument and fixes the auth issue. I used `yalc` to link this branch into `hub-components` and verified everything now works as expected with these changes. …
=> fix(): auth issue in searchPosts

packages/common/src/search/_internal/commonHelpers/getApi.ts, packages/common/src/search/_internal/commonHelpers/shouldUseOgcApi.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/getOgcCollectionUrl.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/searchOgcAggregations.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/searchOgcItems.ts, packages/common/src/search/_internal/portalSearchItems.ts, packages/common/src/search/hubSearch.ts, packages/common/src/search/types/IHubCatalog.ts, packages/common/src/search/types/IHubSearchOptions.ts, packages/common/src/search/utils.ts, packages/common/test/search/_internal/getApi.test.ts, packages/common/test/search/_internal/hubSearchItems.test.ts, packages/common/test/search/_internal/portalSearchItems.test.ts, packages/common/test/search/_internal/shouldUseOgcApi.test.ts, packages/common/test/search/hubSearch.test.ts, packages/common/test/search/utils.test.ts
Description:
Part of https://devtopia.esri.com/dc/hub/issues/5748
This PR consists of two parts:
- Users of `hubSearch` no longer have to explicitly pass an API object. The target API can derived from the requestOptions and a new `site` option. If a `site` is passed and the OGC API is available, it will be targeted. Otherwise, the portal API will be targeted
- Users of `hubSearch` can now append a `collection` to `Query`. This will automatically append the filters from a well known collection to the existing query filters. If targeting the Portal API, the filters will be populated using `getWellKnownCollection`. If targeting the OGC API, those filters are populated server-side as we target a corresponding collection endpoint.
1. [x] Updated meaningful TSDoc to methods including Parameters …
=> feat(hub-common): add automatic api detection and wellKnownCollections to hubSearch

packages/common/src/search/hubSearch.ts, packages/common/test/search/hubSearch.test.ts
Fixes a bug introduced in https://github.com/Esri/hub.js/pull/1036. It turns out that when you clone a `UserSession` object, member functions like `getToken` are omitted from the clone.
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the …
=> fix(hub-common): stop cloning authentication object in hubSearch as it breaks downstream functions

packages/common/src/search/wellKnownCatalog.ts, packages/common/test/search/wellKnownCatalog.test.ts, packages/common/test/test-helpers/fake-user.ts
…
- add getWellknownGroupCatalog function to get eidt-groups and all-groups catalogs
- a few pameter name changes that should effect current use cases …
=> feat(hub-common): add getWellknownGroupCatalog function to get well known group catalogs

packages/common/src/search/wellKnownCatalog.ts, packages/common/test/search/wellKnownCatalog.test.ts
Add viewGroups handling in getWellknownGroupCatalog so we can obtain its catalogs …
=> feat(hub-common): handle viewGroups in getWellknownGroupCatalog

packages/common/src/core/schemas/shared/subschemas.ts, packages/common/src/projects/_internal/ProjectSchema.ts, packages/common/src/projects/_internal/ProjectUiSchemaCreate.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts
- update the project `schema` to include access and groups
- update the project create `uiSchema` to include access and groups
- general project schemas cleanup
- remove description from "Details" step of project creation and replace with status
- remove timeline from project creation all-together and replace with access and group sharing
- move some non-dynamic parts of the `uiSchemas` out of `hub-components` and into the static definitions here
N/A
N/A …
=> feat: add access and groups to project schema

packages/common/src/versioning/createVersion.ts, packages/common/src/versioning/updateVersion.ts, packages/common/src/versioning/updateVersionMetadata.ts, packages/common/test/versioning/createVersion.test.ts, packages/common/test/versioning/updateVersion.test.ts, packages/common/test/versioning/updateVersionMetadata.test.ts
1. Description: Fixes an issue i discovered with the updateVersionMetadata implementation.
1. Instructions for testing: Run tests?
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release …
=> fix: problem with updateVersionMetadata implementation

packages/common/e2e/metrics.e2e.ts, packages/common/src/core/behaviors/IWithMetricsBehavior.ts, packages/common/src/core/types/Metrics.ts, packages/common/src/initiatives/HubInitiative.ts, packages/common/src/metrics/resolveMetric.ts, packages/common/src/projects/HubProject.ts, packages/common/test/initiatives/HubInitiative.test.ts, packages/common/test/metrics/resolveMetric.test.ts, packages/common/test/projects/HubProject.test.ts
To be more aligned with the rest of the platform, and allow for additional debugging information to be returned (not included yet), this PR changes the return type of `resolveMetric` to `IResolvedMetric`. 
While technically a **Breaking Change,** the only devs working with this are aware of this incoming change, and we already have a `-next` branch in flight, which is super messy to deal with when a breaking change is shipped on `master` while that exists. TLDR; we're not being perfect semver citizens, "for reasons"
1. Closes Issues: #6638
1. …
=> fix: update resolveMetric to return IResolvedMetric

packages/common/src/search/_internal/expandPredicate.ts, packages/common/src/search/serializeQueryForPortal.ts
We need to use `isviewonly` to determine whether a group member is able to share items with certain groups. This PR is to enable `isviewonly` to be added to the `q` param in the `serializePredicate` fn. 
1. Closes Issues: #<6463> …
=> feat(hub-common): enable isviewonly to be able to added to the q for portal

packages/common/src/projects/_internal/ProjectSchema.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts
remove the `showMap` property from the project `schema` and edit `uiSchema`. I've left the `showMap` property on the entity itself as I'm unsure if we will leverage it in the future. …
=> fix: remove showMap from project schema/uiSchema

packages/common/src/projects/_internal/setStatusKeyword.ts, packages/common/src/projects/edit.ts, packages/common/test/projects/_internal/setStatusKeyword.test.ts, packages/common/test/projects/projects.test.ts
[6560](https://devtopia.esri.com/dc/hub/issues/6560)
- add project's status as a typekeyword (`status|<project.status>`) on project creation
- update typekeyword when project status is updated
--- …
=> feat: add status as a typekeyword on projects

packages/common/src/items/unshare-item-from-groups.ts, packages/common/test/items/unshare-item-from-groups.test.ts
When unshare an item from groups, because we are using Promise.all, we need to mark the callback fn as async and wrap each individual call in another try/catch block to make sure it catches before all promises finish
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can …
=> fix(hub-common): make sure error gets caught when unshare an item from groups

packages/common/src/projects/_internal/ProjectUiSchemaCreate.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts
[6714](https://devtopia.esri.com/dc/hub/issues/6714)
update project create and edit `uiSchema`s for translation purposes …
=> fix: update project uiSchemas for translation purposes

package-lock.json, packages/sites/src/share-items-to-site-groups.ts
Solution.js relies on `_shareItemToSiteGroups` which we'd removed (dropped the `_`) on the `-next` branch. To avoid having to orchestrate an update of solution.js AND hub.js, we are temporarily re-exporting that function.
run tests
1. [ ] n/a updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update …
=> fix: re-export _shareItemsToSiteGroups to avoid update to solution.js

packages/common/src/search/_internal/hubSearchItemsHelpers/getBboxQueryParam.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/getFilterQueryParam.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/getOgcItemQueryParams.ts, packages/common/test/search/_internal/hubSearchItems.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/6733
Introduces the same bbox serialization logic for the OGC API that currently exists for portal (hubSearch subsystem)
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so …
=> feat(hub-common): support bbox serialization when querying the OGC API via hubSearch

packages/common/e2e/helpers/Artifactory.ts, packages/common/e2e/helpers/config.ts, packages/common/e2e/metrics.e2e.ts, packages/common/e2e/verify-domains.e2e.ts, packages/common/src/sites/HubSite.ts, packages/common/src/sites/HubSites.ts
Also adds an e2e harness and devext config to verify domain service correctly updates the backing app registration re-direct uris …
=> fix: use correct prop for clientKey, send correct options

packages/common/src/ArcGISContext.ts, packages/common/src/core/schemas/getEntityEditorSchemas.ts, packages/common/src/core/types/IHubItemEntity.ts, packages/common/src/core/types/IHubSite.ts, packages/common/src/initiatives/_internal/InitiativeSchema.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts, packages/common/src/initiatives/_internal/getPropertyMap.ts, packages/common/src/projects/fetch.ts, packages/common/src/sites/HubSite.ts, packages/common/src/sites/HubSites.ts, packages/common/src/sites/_internal/SiteSchema.ts, packages/common/src/sites/_internal/SiteUiSchemaCreate.ts, packages/common/src/sites/_internal/SiteUiSchemaEdit.ts, packages/common/src/sites/_internal/getPropertyMap.ts, packages/common/test/ArcGISContextManager.test.ts, packages/common/test/core/schemas/getEntityEditorSchema.test.ts, packages/common/test/projects/projects.test.ts, packages/common/test/sites/HubSites.test.ts, packages/common/test/sites/fixtures/expected-model.jsonc, packages/common/test/sites/fixtures/mapped-model.jsonc
- adds just enough Site Schema to enable loading a Site into the Configuration Editor. The schema is incomplete, and the config editor can not actually save the site because mapping from `IHubSite` -> `IModel` does not include all the necessary information required to actually update a Site item. Additional work is necessary.
- Also adds more props to the Initiative editor schema - title, desc, snippet, location etc
1. Instructions for testing: run-tests
1. Related to Issues: #[6789](https://devtopia.esri.com/dc/hub/issues/6789) …
=> feat: add Site Edit Schema

package-lock.json, packages/common/src/core/traits/IWithViewSettings.ts, packages/common/src/projects/_internal/ProjectSchema.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts
1. Description: Added featured image alt text support for projects. …
=> feat: project featured image alt text

packages/common/src/items/index.ts, packages/common/src/items/registerBrowserApp.ts, packages/common/src/sites/HubSites.ts, packages/common/src/sites/index.ts, packages/common/src/sites/registerSiteAsApplication.ts, packages/common/src/types.ts, packages/common/test/items/registerBrowserApp.test.ts, packages/common/test/sites/HubSites.test.ts, packages/common/test/sites/registerBrowserApp.test.ts, packages/common/test/sites/registerSiteAsApplication.test.ts, packages/discussions/package.json, packages/downloads/package.json, packages/events/package.json, packages/initiatives/package.json, packages/search/package.json, packages/sites/package.json, packages/sites/src/create-site.ts, packages/sites/src/update-site-application-uris.ts, packages/sites/test/create-site.test.ts, packages/sites/test/update-app-redirect-uris.test.ts, packages/sites/test/update-site-application-uris.test.ts, packages/surveys/package.json, packages/teams/package.json
Remove calls to /registerApp or /updateApp for Hub Sites, and rely on Hub Domain service to do that work. This code was previously validated on the `next` branch and deployed to DEVEXT. However, that branch also included a lot of other changes related to deprecating additional functions, which created a very messy rebase which we could not resolve in a timely manner.
affects: @esri/hub-common, @esri/hub-sites
Client code no longer makes calls to
register site as application or to update application redirect uris. This is all expected to be handled server-side by the Hub Domain service.
remove deprecated destroySite()
1. Closes Issues: #6390
1. [x] Updated meaningful TSDoc to methods including …
=> feat: remove calls to register or update app

packages/common/src/initiatives/HubInitiatives.ts, packages/common/src/items/_internal/slugConverters.ts, packages/common/src/items/getItemIdentifier.ts, packages/common/src/items/index.ts, packages/common/src/items/slugs.ts, packages/common/src/projects/fetch.ts, packages/common/test/initiatives/HubInitiatives.test.ts, packages/common/test/items/_internal/slugConverters.test.ts, packages/common/test/items/getItemIdentifier.test.ts, packages/common/test/items/slugs.test.ts
- add helper functions that convert to / from uri slugs (`myorg::the-slug`) to (`myorg|the-slug`) and back
- use functions in entity functions that convert items to search results
- use function in `getItemBySlug` (lowest level function for fetching) so the uri slugs can be passed waaaay down, ensuring all upstream fns can handle the uri slugs cleanly.
1. Closes Issues: #6932
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation will not …
=> feat: add slug uri conversion functions and use in getItemBySlug

packages/discussions/src/utils/posts/index.ts
ISSUES CLOSED: 6883
1. Description: Expands isDiscussable so it can be used to determine IHubEntity discussability. …
=> feat(hub-discussions): expand isDiscussable

package-lock.json, packages/discussions/src/utils/channel-permission.ts, packages/discussions/src/utils/channels/can-create-channel.ts, packages/discussions/src/utils/channels/can-post-to-channel.ts, packages/discussions/src/utils/channels/index.ts, packages/discussions/src/utils/posts/can-modify-post-status.ts, packages/discussions/src/utils/posts/can-modify-post.ts, packages/discussions/src/utils/posts/index.ts, packages/discussions/test/utils/channels/can-create-channel.test.ts, packages/discussions/test/utils/channels/can-post-to-channel.test.ts, packages/discussions/test/utils/channels/index.test.ts, packages/discussions/test/utils/posts/can-modify-post-status.test.ts, packages/discussions/test/utils/posts/can-modify-post.test.ts, packages/discussions/test/utils/posts/index.test.ts
Issue [6820](https://zentopia.esri.com/workspaces/engagement-workspace-61508ae50946c40014ef574f/issues/dc/hub/6820)
1. Description: Audit the channel and post permission checks for mixed access channels (org and public channels can now also have groups) and handle `undefined` user case for all access util functions
`canPostToChannel`
- no changes
`canCreateChannel`
- org and public channels now require the user to be a member of every provided group (and channel org admin)
`canReadFromChannel`
- org channels now allow reads from channel group members OR channel org members
`canModifyChannel`
- org channels now allow modification from channel group owner/admins OR channel org admins
`canModifyPost`
- posts in org channels now require that user created the post AND (user is member of …
=> feat(hub-discussions): legacy permission checks mixed channels

package-lock.json, packages/common/src/core/schemas/getEntityEditorSchemas.ts, packages/common/src/core/types/HubEntity.ts, packages/common/src/discussions/_internal/DiscussionSchema.ts, packages/common/src/discussions/_internal/DiscussionUiSchemaCreate.ts, packages/common/src/discussions/_internal/DiscussionUiSchemaEdit.ts, packages/common/test/core/schemas/getEntityEditorSchema.test.ts
1. Description: Adds `create` uiSchema for Discussions for 'new' discussion board workflow. (includes `cherry-picked` commits from [1080](https://github.com/Esri/hub.js/pull/1080).
1. Closes Issues: Part of #6876 …
=> feat(): adds discussion create ui schema

packages/common/src/sites/HubSites.ts, packages/common/src/sites/domains/addSiteDomains.ts, packages/common/test/sites/HubSites.test.ts, packages/common/test/sites/domains/addSiteDomains.test.ts, packages/sites/src/create-site.ts
Solutions team was testing on ArcGIS Enterprise, and noted an issue connected to recent changes to that were ArcGIS Online specific, but caused a regression for portal.
This changes how `addSiteDomains(..)` works in Portal, so that it returns a single "domain record" that includes the portal `clientKey`. This ensures that in all cased, at least one entry is returned from `addSiteDomains`
1. Instructions for testing - run tests
1. Closes Issues: For expediency, no bug was logged
1. [x] PR title follows semantic commit format (**CRITICAL** if the …
=> fix: address issue creating sites on portal

packages/common/src/util.ts, packages/common/src/utils/titleize.ts, packages/common/test/utils/titleize.test.ts
Fixes https://devtopia.esri.com/dc/hub/issues/6999
=> fix(hub-common): have capitalize() handle the empty string, change titlelize() to stop stripping white space

package-lock.json, packages/common/src/discussions/_internal/DiscussionSchema.ts, packages/common/src/discussions/defaults.ts
remove required property prompt from discussions schema
ISSUES CLOSED: 6876
1. Description: Removes `prompt` as a required property from the Discussions schema.  Adds a default value for `prompt` . 
1. Closes Issues: #6876 …
=> feat(hub-common): remove required property prompt

docs/src/guides/classes/arcgiscontext.md, package-lock.json, packages/common/e2e/context-manager.e2e.ts, packages/common/src/ArcGISContextManager.ts, packages/common/src/utils/sessionLocalStorage.ts, packages/common/test/ArcGISContextManager.test.ts
Add serialize and deserialize for ArcGISContextManager:
```
const serialized = ctxMgr.serialize();
// store in localStorage...
// load from localStorage
// create new contextManager
const newCtxMgr = await ArcGISContextManager.deserialize(serialized);
```
1. Closes Issues: #7053 (if appropriate) …
=> feat: context manager serialize / deserialize

packages/common/src/core/schemas/shared/subschemas.ts, packages/common/src/projects/_internal/ProjectSchema.ts
[7066](https://devtopia.esri.com/dc/hub/issues/7066)
- limit project summary (purpose) to 2048 characters
- abstract this field schema as a reusable entity subschema …
=> fix: limit project summary (purpose) to 2048 chars

packages/common/src/core/HubItemEntity.ts, packages/common/src/discussions/_internal/DiscussionSchema.ts, packages/common/src/discussions/_internal/DiscussionUiSchemaEdit.ts, packages/common/src/discussions/_internal/computeProps.ts, packages/common/src/discussions/edit.ts, packages/common/src/discussions/utils.ts, packages/common/src/initiatives/HubInitiatives.ts, packages/common/src/initiatives/_internal/computeProps.ts, packages/common/src/projects/_internal/computeProps.ts, packages/common/src/projects/edit.ts, packages/common/src/sites/HubSites.ts, packages/common/src/sites/_internal/computeProps.ts, packages/common/test/discussions/edit.test.ts, packages/common/test/discussions/utils.test.ts, packages/common/test/initiatives/HubInitiatives.test.ts, packages/common/test/projects/projects.test.ts, packages/common/test/sites/HubSites.test.ts
1. Description: Allows isDiscussable property on entities to be updated.
1. Instructions for testing: Can be tested in the hub-components workspace harness. Note: there is a known bug in the radio buttons where they do not reflect the current value of isDiscussable, this is known and being fixed in a separate PR.
1. Closes Issues: 6883
1. [x] updated `peerDependencies` as needed. **CRITICAL** our …
=> feat(hub-common): add isDiscussable mapping

packages/common/src/projects/_internal/ProjectSchema.ts
[7034](https://devtopia.esri.com/dc/hub/issues/7034)
Add a default value, `{ type: "none" }`, to the location property on the project schema
---
2. [x] used semantic commit messages
3. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation will not run!)
4. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the …
=> fix: add default to project schema for location

packages/common/e2e/helpers/Artifactory.ts, packages/common/e2e/hub-user-search.e2e.ts, packages/common/src/core/types/MaybeTranslate.ts, packages/common/src/core/types/index.ts, packages/common/src/objects/index.ts, packages/common/src/objects/pickProps.ts, packages/common/src/search/_internal/expandPredicate.ts, packages/common/src/search/_internal/portalSearchGroupMembers.ts, packages/common/src/search/_internal/portalSearchUsers.ts, packages/common/src/search/hubSearch.ts, packages/common/src/search/serializeQueryForPortal.ts, packages/common/src/search/utils.ts, packages/common/src/users/HubUsers.ts, packages/common/src/users/_internal/enrichments.ts, packages/common/test/objects/pickProps.test.ts, packages/common/test/search/_internal/portalSearchGroupMembers.test.ts, packages/common/test/users/HubUsers.test.ts
Finalize search for `targetEntity: "user"` and `targetEntity: "groupMember"`
There are also some e2e's that verify this against the actual portal api - the groups involved are not durable, but work as of this writing
1. Closes Issues: [#7164](https://devtopia.esri.com/dc/hub/issues/7164)
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release …
=> feat: hubSearch supports groupMember entity type

packages/common/src/core/schemas/types.ts
Allows for rule scopes in UiSchema's to be optional. This allows for multiple conditions on one rule. 
1. Closes Issues: helps to close #6356 …
=> fix(): make scope optional for IUiSchemaRule

packages/common/src/content/edit.ts, packages/common/src/content/fetch.ts, packages/common/src/core/_internal/PropertyMapper.ts, packages/common/src/discussions/edit.ts, packages/common/src/discussions/fetch.ts, packages/common/src/initiatives/HubInitiatives.ts, packages/common/src/projects/edit.ts, packages/common/src/projects/fetch.ts, packages/common/src/sites/HubSite.ts, packages/common/src/sites/HubSites.ts, packages/common/test/content/edit.test.ts, packages/common/test/core/helpers/PropertyMapper.test.ts
The `PropertyMapper` class accepted a Type for the Entity (object) side, but assumed `IModel` for the "model" side.
This change allows the user to specify the "model" side as well, and propagates that through the helper functions
e.g.
`new PropertyMapper<Partial<IHubEditableContent>, IModel>()`
`new PropertyMapper<IHubGroup, IGroup>()`
- Methods are now `.storeToEntity` and `.entityToStore` 
Please leave feelings / ideas
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a …
=> feat: make propertyMapper more generic

packages/common/src/content/_internal/getPropertyMap.ts, packages/common/src/content/edit.ts, packages/common/src/content/fetch.ts, packages/common/src/core/_internal/PropertyMapper.ts, packages/common/src/core/_internal/getBasePropertyMap.ts, packages/common/src/discussions/_internal/getPropertyMap.ts, packages/common/src/discussions/edit.ts, packages/common/src/discussions/fetch.ts, packages/common/src/initiatives/HubInitiatives.ts, packages/common/src/initiatives/_internal/getPropertyMap.ts, packages/common/src/projects/_internal/getPropertyMap.ts, packages/common/src/projects/edit.ts, packages/common/src/projects/fetch.ts, packages/common/src/sites/HubSite.ts, packages/common/src/sites/HubSites.ts, packages/common/src/sites/_internal/getPropertyMap.ts, packages/common/test/content/edit.test.ts, packages/common/test/core/helpers/PropertyMapper.test.ts
The `PropertyMapper` class accepted a Type for the Entity (object) side, but assumed `IModel` for the "model" side.
This change allows the user to specify the "model" side as well, and propagates that through the helper functions
e.g.
`new PropertyMapper<Partial<IHubEditableContent>, IModel>()`
`new PropertyMapper<IHubGroup, IGroup>()`
- Methods are now `.storeToEntity` and `.entityToStore` 
Please leave feelings / ideas
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a …
=> feat: Generic property mapper 

package-lock.json, packages/common/src/sites/_internal/handleDomainChanges.ts, packages/common/test/sites/_internal/handleDomainChanges.test.ts
1. Description: Fixes a small issue with editing customHostname and defaultHostname
1. Instructions for testing: well, you can't easily. You'd have to add the appropriate schemas to SiteSchema.ts and SiteUiShcemaEdit.ts and we don't want to do that yet.
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in …
=> fix: defaultHostname and customHostname editing on site entity

packages/common/src/core/schemas/shared/HubItemEntitySchema.ts, packages/common/src/core/schemas/shared/HubItemEntitySubschema.ts, packages/common/src/core/schemas/shared/subschemas.ts, packages/common/src/core/traits/IWithViewSettings.ts, packages/common/src/discussions/_internal/DiscussionSchema.ts, packages/common/src/initiatives/_internal/InitiativeSchema.ts, packages/common/src/projects/_internal/ProjectSchema.ts, packages/common/src/sites/_internal/SiteSchema.ts
[7094](https://devtopia.esri.com/dc/hub/issues/7094)
- add a shared `HubItemEntitySchema` that all item entities can "extend"
- update all existing item entity schemas to leverage the `HubItemEntitySchema` …
=> feat: add a base item entity schema

packages/common/src/core/behaviors/IWithCardBehavior.ts, packages/common/src/core/types/IHubCardViewModel.ts, packages/common/src/projects/HubProject.ts, packages/common/src/projects/view.ts, packages/common/test/projects/HubProject.test.ts, packages/common/test/projects/view.test.ts
[7161](https://devtopia.esri.com/dc/hub/issues/7161)
- add `actionLinks` arg to `convertToCardViewModel` in `IWithCardBehavior` interface
- add `actionLinks` arg to all project card view model functions to be injected into the `IHubCardViewModel` …
=> fix: add actionLinks arg to project view model functions

package-lock.json, packages/common/e2e/hub-user-search.e2e.ts, packages/common/src/search/_internal/portalSearchGroupMembers.ts, packages/common/test/search/_internal/portalSearchGroupMembers.test.ts
Swap `groupMember` search to pull the `groupId` from a `group` predicate vs `query.properties.group` …
=> fix: get group from predicate not query.properties

packages/common/src/search/_internal/portalSearchGroupMembers.ts, packages/common/test/search/_internal/portalSearchGroupMembers.test.ts
Last minor change needed for `groupMember` search. This remaps the `term` predicate to `name`. Previous prototype work had done this in the gallery, but there's no reason not to do this in hub.js.
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in …
=> fix: rename term to name for groupMember queries

package-lock.json, packages/discussions/src/utils/channel-permission.ts, packages/discussions/src/utils/channels/can-create-channel.ts, packages/discussions/src/utils/channels/can-modify-channel.ts, packages/discussions/src/utils/channels/can-post-to-channel.ts, packages/discussions/src/utils/posts/can-delete-post.ts, packages/discussions/src/utils/posts/can-modify-post-status.ts, packages/discussions/src/utils/posts/can-modify-post.ts, packages/discussions/src/utils/posts/index.ts, packages/discussions/test/utils/channel-permission.test.ts, packages/discussions/test/utils/channels/can-modify-channel.test.ts, packages/discussions/test/utils/posts/can-delete-post.test.ts, packages/discussions/test/utils/posts/can-modify-post-status.test.ts, packages/discussions/test/utils/posts/can-modify-post.test.ts, packages/discussions/test/utils/posts/index.test.ts
- Add ACL checks on the can-modify-post, can-modify-post-status, and can-delete-post utils.
- Refactor channel-permissions class a bit …
=> refactor: post-mod and post-delete utils for ACL

packages/discussions/src/utils/channel-permission.ts, packages/discussions/src/utils/channels/can-create-channel.ts, packages/discussions/src/utils/channels/can-modify-channel.ts, packages/discussions/src/utils/channels/can-post-to-channel.ts, packages/discussions/src/utils/posts/can-delete-post.ts, packages/discussions/src/utils/posts/can-modify-post-status.ts, packages/discussions/src/utils/posts/can-modify-post.ts, packages/discussions/src/utils/posts/index.ts, packages/discussions/test/utils/channel-permission.test.ts, packages/discussions/test/utils/channels/can-modify-channel.test.ts, packages/discussions/test/utils/posts/can-delete-post.test.ts, packages/discussions/test/utils/posts/can-modify-post-status.test.ts, packages/discussions/test/utils/posts/can-modify-post.test.ts, packages/discussions/test/utils/posts/index.test.ts
- Add ACL checks on the can-modify-post, can-modify-post-status, and can-delete-post utils.
- Refactor channel-permissions class a bit …
=> feat: post-mod and post-delete utils for ACL

package-lock.json, packages/common/src/content/get-family.ts, packages/common/src/initiatives/HubInitiative.ts, packages/common/src/initiatives/HubInitiatives.ts, packages/common/src/initiatives/index.ts, packages/common/src/initiatives/view.ts, packages/common/test/content/get-family.test.ts, packages/common/test/initiatives/HubInitiative.test.ts, packages/common/test/initiatives/fixtures.ts, packages/common/test/initiatives/view.test.ts
1. Description: adds conversion functions for converting initiative/initiative search resutls to card view model …
=> feat: 7162 initiative card funcs

package-lock.json, packages/common/e2e/context-manager.e2e.ts, packages/common/e2e/hub-page.e2e.ts, packages/common/package-lock.json, packages/common/src/capabilities/_internal/checkCapabilityAccess.ts, packages/common/src/capabilities/checkCapability.ts, packages/common/src/core/HubItemEntity.ts, packages/common/src/core/fetchHubEntity.ts, packages/common/src/core/getTypeFromEntity.ts, packages/common/src/core/schemas/getEntityEditorSchemas.ts, packages/common/src/core/types/IHubPage.ts, packages/common/src/core/updateHubEntity.ts, packages/common/src/pages/HubPage.ts, packages/common/src/pages/HubPages.ts, packages/common/src/pages/_internal/PageBusinessRules.ts, packages/common/src/pages/_internal/PageSchema.ts, packages/common/src/pages/_internal/PageUiSchemaEdit.ts, packages/common/src/pages/_internal/computeProps.ts, packages/common/src/pages/_internal/getPropertyMap.ts, packages/common/src/pages/defaults.ts, packages/common/src/pages/index.ts, packages/common/src/permissions/types/Permission.ts, packages/common/test/core/fetchHubEntity.test.ts, packages/common/test/core/schemas/getEntityEditorSchema.test.ts, packages/common/test/core/updateHubEntity.test.ts, packages/common/test/pages/HubPage.test.ts, packages/common/test/pages/HubPages.test.ts, packages/common/test/pages/_internal/computeProps.test.ts
1. Description: First pass at minimum viable Page entity
1. Instructions for testing: run the e2es and the specs
1. Closes Issues: [7121](https://devtopia.esri.com/dc/hub/issues/7121) …
=> feat: page entity

packages/common/src/content/_internal/ContentBusinessRules.ts, packages/common/src/discussions/_internal/DiscussionBusinessRules.ts, packages/common/src/initiatives/_internal/InitiativeBusinessRules.ts
Adds dashboard capability to content, discussions, and initiatives workspaces
1. Closes Issues: [#7362](https://zentopia.esri.com/workspaces/sites-sprint-board-614a18b38a61a3001196c48d/issues/dc/hub/7326)
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our …
=> feat(): add dashboard capability to content, discussions,initiatives

packages/common/src/sites/_internal/applyDefaultCollectionMigration.ts, packages/common/test/sites/HubSites.test.ts
Main fix for [this issue](https://devtopia.esri.com/dc/hub/issues/7419) discovered by product (NOTE: this is not the hotfix) …
=> fix(hub-common): have convertModelToSite handle invalid search categories

package-lock.json, packages/common/src/discussions/api/types.ts, packages/discussions/src/discussion-settings/discussion-settings.ts, packages/discussions/src/types.ts, packages/discussions/test/discussion-settings.test.ts
1. Description: add function `updateDiscussionSetting` in the hub-discussions package and supporting interfaces in hub-common package …
=> feat(hub-discussions): add function updateDiscussionSetting

packages/common/src/discussions/api/types.ts
1. Description: Add optional filter parameter `name` to discussions ISearchChannels interface …
=> feat(hub-common): add name to interface ISearchChannels

package-lock.json, packages/common/src/sites/HubSite.ts, packages/common/test/sites/HubSite.test.ts
- updates `applyDefaults` in `hub-sites` to handle cases where the portal prop doesn't exist on the context object
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/7316 …
=> fix(): gracefully handles cases where portal prop might not exist on

package-lock.json, packages/common/src/users/view.ts, packages/common/test/users/fixtures.ts, packages/common/test/users/view.test.ts
1. Description: Adds a conversion function for a user search result to card model. …
=> feat: user card result to card

packages/common/src/sites/HubSites.ts, packages/common/src/sites/_internal/applyDefaultCollectionMigration.ts, packages/common/src/sites/_internal/reflectCollectionsToSearchCategories.ts, packages/common/src/sites/_internal/types.ts, packages/common/test/sites/HubSites.test.ts, packages/common/test/sites/_internal/applyDefaultCollectionMigration.test.ts, packages/common/test/sites/_internal/reflectCollectionsToSearchCategories.test.ts
Persisting logic for configuring site collections in workspaces, part of [7181](https://devtopia.esri.com/dc/hub/issues/7181)
Implements the site saving portion of [this ADR](https://confluencewikidev.esri.com/pages/viewpage.action?pageId=272826648) …
=> feat(hub-common): persist modifications to site collections via updateSite

packages/common/src/projects/defaults.ts
1. Description: With Dave's work we are now properly? using project defaults as we had them outlined. However this means we are inserting in a string in the project name that we don't want. This removes that.
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so …
=> fix: remove name/title string as it is not wanted

package-lock.json, packages/common/src/content/compose.ts, packages/common/src/core/fetchHubEntity.ts, packages/common/src/core/getTypeFromEntity.ts, packages/common/src/core/types/HubEntity.ts, packages/common/src/core/types/IHubGroup.ts, packages/common/src/groups/_internal/GroupBusinessRules.ts, packages/common/src/groups/_internal/computeProps.ts, packages/common/test/core/fetchHubEntity.test.ts, packages/common/test/core/getTypeFromEntity.test.ts, packages/common/test/groups/HubGroups.test.ts, packages/common/test/groups/_internal/computeProps.test.ts
Add more support and props for Hub Group including:
- Add fetchHubGroup to fetchHubEntity so we can fetch groups
- ... (to be added)
1. Closes Issues: [7169](https://zentopia.esri.com/workspaces/collaboration-sprint-board-614f9bfc0946c40011ef574e/issues/dc/hub/7169)
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to …
=> feat: add more support and props for Hub Group

package-lock.json, packages/common/src/discussions/HubDiscussion.ts
Fixes bug that was introduced on this [commit](https://github.com/Esri/hub.js/commit/0ea3d9229ef9f3f3a7ede7651244941f51265998) that prohibited new Discussion Board items to be created. 
Updates to use existing `save()` method which will handle both `create` and `update`.
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` …
=> fix(): handle new discussion entity

package-lock.json, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts
1. Description: Move Thumbnail, categories, and tags into their own section.
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section …
=> fix: reshuffle project edit schema

package-lock.json, packages/common/src/content/HubContent.ts, packages/common/src/content/_internal/ContentUiSchemaEdit.ts, packages/common/src/content/_internal/getPropertyMap.ts, packages/common/src/content/edit.ts
OD-UI PR: https://github.com/ArcGIS/opendata-ui/pull/12342
1. Description: Adds location picker to workspace content details
1. Closes Issues: [#7208 ](https://devtopia.esri.com/dc/hub/issues/7208) …
=> feat: added location picker to content details

packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/_internal/checkAssertion.ts, packages/common/src/permissions/types/IPermissionPolicy.ts, packages/common/src/permissions/types/Permission.ts, packages/common/src/projects/_internal/ProjectBusinessRules.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts, packages/common/test/permissions/_internal/checkAssertion.test.ts
1. Description: Proposed interim approach for gating workspaces.
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the …
=> feat: workspace gating

packages/common/src/permissions/HubPermissionPolicies.ts
No issue. Further constrains `temp:workspace:released` permission to alpha orgs.
=> feat: constrain temp:workspace:released permission to alpha orgs

packages/common/src/sites/domains/add-domain.ts, packages/common/src/sites/domains/update-domain.ts, packages/common/test/sites/domains/add-domain.test.ts, packages/common/test/sites/domains/update-domain.test.ts
Updates the client key to an empty string before calling add or update domain. 
1. Closes Issues: works to close 7460 and 7559 …
=> fix(): update clientKey to empty string in updateDomain/addDomain

package-lock.json, packages/common/src/content/edit.ts, packages/common/src/core/getTypeFromEntity.ts, packages/common/src/core/schemas/internal/getLocationOptions.ts, packages/common/test/content/edit.test.ts, packages/common/test/core/schemas/internal/getLocationOptions.test.ts
Make sure you have your opendata-ui set to https://github.com/ArcGIS/opendata-ui/pull/12378 until it merges, I added a new translation this morning.
1. Description: 
- If a user selects "none" in the location picker, it no longer appears in the /about view
- Location picker options in workspace content now properly shows two options
- This will be further built off of in future issues and PRs that allow for a bounding box option as discussed with Tom, Dave, and Ben on Aug 10, 2023
- Clone this PR and PR with updated translations: https://github.com/ArcGIS/opendata-ui/pull/12378 
- Copy the hubjs dist folder over
- `yarn hc start` -- switch back and forth between "none" and "Item's Current Extent" in content's location picker
- Double check that I haven't …
=> fix: user selects none; location disappears correctly

package-lock.json, packages/common/src/core/EntityEditor.ts, packages/common/src/core/schemas/getEntityEditorSchemas.ts, packages/common/src/core/schemas/internal/getEditorConfigOptions.ts, packages/common/src/core/schemas/internal/getEntityEditorSchemas.ts, packages/common/src/core/schemas/types.ts, packages/common/src/core/types/IHubGroup.ts, packages/common/src/groups/HubGroup.ts, packages/common/src/groups/HubGroups.ts, packages/common/src/groups/_internal/GroupBusinessRules.ts, packages/common/src/groups/_internal/GroupSchema.ts, packages/common/src/groups/_internal/GroupUiSchemaEdit.ts, packages/common/src/groups/_internal/convertGroupToHubGroup.ts, packages/common/src/groups/_internal/convertHubGroupToGroup.ts, packages/common/src/groups/deleteGroupThumbnail.ts, packages/common/src/groups/setGroupThumbnail.ts, packages/common/test/core/EntityEditor.test.ts, packages/common/test/core/schemas/getEntityEditorSchema.test.ts, packages/common/test/core/schemas/internal/getEntityEditorSchemas.test.ts, packages/common/test/groups/HubGroup.test.ts, packages/common/test/groups/_internal/convertGroupToHubGroup.test.ts, packages/common/test/groups/_internal/convertHubGroupToGroup.test.ts, packages/common/test/groups/deleteGroupThumbnail.test.ts, packages/common/test/groups/setGroupThumbnail.test.ts
Add GroupSchema, GroupUiSchema and other support for Hub Groups so the group workspace details pane could be set up …
=> fix: add GroupSchema, GroupUiSchema and other support for groups details pane

package-lock.json, packages/common/src/core/types/index.ts
1. Description: We need to properly export IHubGroup. …
=> fix: export ihubgroup

package-lock.json, packages/common/src/users/view.ts, packages/common/test/users/view.test.ts
1. Description: removes additionalInfo from the user search result to card model conversion as it was erroneously added. …
=> fix: remove additionalInfo from userResultToCardModel

packages/common/src/search/utils.ts, packages/common/test/search/utils.test.ts
Underlying issue is inconsistencies between the params for various rest-js calls, which necessitated the `request` which is passed into `getNextFunction(...)`, also have both  `.authentication` AND `.requestOptions` properties. In the `getNextFunction(..)` we cloned the request, and then did some additional acrobatics to ensure that `.authentication` on the clone was a reference to the original `UserSession` object. This PR ensures that `.requestOptions` gets that same treatment.
- pull, run a build, copy into -ui, run harnesses and validate that you can fetch additional pages of items, org users, groups and group members.
1. Closes Issues: #7575 (if appropriate)
1. [x] Updated meaningful TSDoc to methods including Parameters and Returns, see …
=> fix: ensure requestOptions.authentication is UserSession instance in next()

packages/common/src/search/_internal/portalSearchGroupMembers.ts, packages/common/src/search/serializeQueryForPortal.ts, packages/common/test/search/serializeQueryForPortal.test.ts
Add support for group members "joined" field so we can sort/search by the joined dates …
=> fix: add support for group members "joined" field

packages/common/src/permissions/checkPermission.ts, packages/common/test/permissions/checkPermission.test.ts
Outcome of Permission call w/ PEs was a request to log the output of failed calls to `checkPermission(...)` …
=> fix: log checkPermission output if access not granted

package-lock.json, packages/common/src/groups/_internal/GroupSchema.ts, packages/common/src/groups/_internal/GroupUiSchemaEdit.ts
[7275](https://devtopia.esri.com/dc/hub/issues/7275)
updates the group details (edit) `schema`/`uiSchema` with a couple minor changes
- changes aspect ratio of thumbnail to 1
- removes helper text from the summary field
- adds a size description to the thumbnail
- constrains the summary field to 250 chars …
=> fix: small updates to group details schemas

packages/common/src/content/_internal/ContentBusinessRules.ts, packages/common/src/groups/_internal/GroupBusinessRules.ts, packages/common/src/initiatives/_internal/InitiativeBusinessRules.ts, packages/common/src/pages/_internal/PageBusinessRules.ts, packages/common/src/projects/_internal/ProjectBusinessRules.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts
1. Description: 
Adding permissions like hub:<entity>:workspace:<pane> into hub.js. These will "delegate" (via dependencies) to the same permission checks used today (hub:<entity>:edit etc) but allow us the option to apply per-pane gating (qa vs dev, alpha, beta etc)
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/7624
1. [ ] updated `peerDependencies` as needed. **CRITICAL** …
=> feat: add workspace pane permissions for all entities

packages/common/src/content/HubContent.ts, packages/common/src/groups/HubGroup.ts, packages/common/src/initiatives/HubInitiative.ts, packages/common/src/pages/HubPage.ts, packages/common/src/projects/HubProject.ts, packages/common/src/sites/HubSite.ts
@sonofflynn89 pointed out that my refactor a few weeks back missed the need for an `await` on the `this.save()` call in the `fromEditor(..)` method.
This PR simply adds that, and in doing so, resolves an issue in the workspaces where edit state was not synced between the panes.
- run tests …
=> fix: await save in classes

packages/common/src/discussions/_internal/DiscussionBusinessRules.ts, packages/common/src/pages/_internal/PageBusinessRules.ts, packages/common/src/projects/_internal/ProjectBusinessRules.ts
Previous PR missed a few permissions, which came up as I verified the changes to the WorkspaceLinks in hub-components. …
=> fix: add missing permissions

packages/common/src/content/_internal/internalContentUtils.ts, packages/common/src/content/get-family.ts, packages/common/src/types.ts, packages/common/test/content/content.test.ts, packages/common/test/content/get-family.test.ts
1. Description: Updates to allow Discussion Boards `type: Discussion` to use `/discussions/:id` route.
1. Closes Issues: 7623 …
=> feat(): include discussion routes

packages/common/src/search/utils.ts, packages/common/test/search/utils.test.ts
`getNextFunction` needed to be tweaked to work correctly for `searchGroupMembers`
- run tests
1. Closes Issues: n/a - came up when helping @vivzhang debug an issue …
=> fix: ensure getNextFunction handles requestOptions.authentication

packages/common/src/search/types/types.ts
Add new `SortOption` type
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the …
=> fix: add new SortOption type

packages/common/src/search/types/types.ts
add memberType to SortOption
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the …
=> fix: add memberType to SortOption

packages/common/src/search/_internal/hubSearchChannels.ts, packages/common/test/search/_internal/hubSearchChannels.test.ts
ISSUES CLOSED: #7405
1. Description: Enriches channel result from hubSearch with group information when `include: ['groups']` is requested from `options: IHubSearchOptions`.
1. Instructions for testing: `hubSearchChannels.test.ts`
1. Closes Issues: #7405 …
=> feat(hub-common): enriches channel with groups via hub search includes

packages/common/src/core/types/Metrics.ts, packages/common/src/sites/_internal/_migrate-summary-stat-card-configs.ts, packages/common/src/sites/index.ts, packages/common/src/sites/site-schema-version.ts, packages/common/src/sites/upgrade-site-schema.ts, packages/common/test/sites/_internal/_migrateSummaryStatCardConfig.test.ts, packages/common/test/sites/upgrade-site-schema.test.ts, packages/sites/src/drafts/upgrade-draft-schema.ts, packages/sites/test/drafts/upgrade-draft-schema.test.ts
TODO:
- This PR:
- Next PR:
Introduces a migration for the site model/draft schema for the summary stat card updates.
1. Closes Issues: #7158 (if appropriate) …
=> feat(): migrate summary stat function

packages/common/src/groups/_internal/GroupUiSchemaSettings.ts
1. Description: Previously the labels weren't be translated, they were missing `:translate` and needed angle brackets. Previously the paths were being dropped into the ui. …
=> fix: properly translate radio button labels

package-lock.json, packages/common/src/core/traits/IWithFollowers.ts, packages/common/src/core/types/IHubSite.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts, packages/common/src/sites/_internal/getPropertyMap.ts
[7620](https://devtopia.esri.com/dc/hub/issues/7620)
- adds a new `IWithFollowers` trait with a `followersGroupId` property for entities to extend if they support followers
- extends the `IHubSite` with `IWithFollowers`
- adds business rules for site's followers pane  
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do …
=> feat: site's followers pane permissions

packages/common/src/projects/_internal/ProjectBusinessRules.ts
Ungates the dashboard pane from the Projects workspace. 
1. Closes Issues: works to close [7658](https://zentopia.esri.com/workspaces/collaboration-sprint-board-614f9bfc0946c40011ef574e/issues/dc/hub/7658) …
=> feat(): ungate dashboard from projects workspace

docs/build-typedoc.js, docs/src/api/_declaration.html, docs/src/api/index.html, packages/common/src/content/_internal/ContentUiSchemaEdit.ts, packages/common/src/discussions/_internal/DiscussionUiSchemaCreate.ts, packages/common/src/discussions/_internal/DiscussionUiSchemaEdit.ts, packages/common/src/groups/_internal/GroupUiSchemaEdit.ts, packages/common/src/groups/_internal/GroupUiSchemaSettings.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaCreate.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts, packages/common/src/pages/_internal/PageUiSchemaEdit.ts, packages/common/src/projects/_internal/ProjectUiSchemaCreate.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts, packages/common/src/sites/_internal/SiteUiSchemaCreate.ts, packages/common/src/sites/_internal/SiteUiSchemaEdit.ts
Acetate was silently failing due to some `{{{{...}}}}` stuff in the Ui Schema files.
This PR marks all those as `@private`, AND filters out `uiSchema` & `UiSchema` files from the tsdoc.json before getting into acetate.
Also adds the package version to the TOC as a means to help know when the doc is stale
build docs?
1. [ ] updated `peerDependencies` as needed. …
=> docs: keep all uiSchemas @private to avoid issues generating docs

packages/common/src/core/types/IHubCardViewModel.ts, packages/common/src/search/_internal/portalSearchGroupMembers.ts, packages/common/src/users/HubUsers.ts, packages/common/src/users/view.ts, packages/common/test/users/view.test.ts
[7654](https://devtopia.esri.com/dc/hub/issues/7654)
- add `isGroupOwner` property to group member results
- add tooltip configuration to the `IBadgeConfig` interface
- conditionally add member type badges to the user card model …
=> feat: add member role badges to user card model

packages/common/src/initiatives/view.ts, packages/common/src/projects/view.ts, packages/common/src/users/view.ts
Currently if a search result has an index of 0, it doesn't get added to the card view model because 0 is a `falsey` value. Instead of checking the truthiness of `searchResult.index`, we need to check whether `searchResult.index` is a number. If it is, we add it to the view model.  …
=> fix: account for index values that are 0 in card view models

packages/common/src/models/index.ts
OD-UI PR: https://github.com/ArcGIS/opendata-ui/pull/12472
1. Description: Quick bug fix for clearing the license field where it would only clear if one of the other text fields was empty.
- Open a content item
- Set the license and add content to all fields
- Save
- Refresh
- Clear the license
- Refresh => the license should now disappear correctly, regardless of other fields
1. Closes Issues: [#https://devtopia.esri.com/dc/hub/issues/7209](https://devtopia.esri.com/dc/hub/issues/7209)
1. [x] PR title follows semantic commit format …
=> fix: shouldClearEmptyFields now accounts for licenseInfo

packages/common/src/content/_internal/computeProps.ts, packages/common/src/core/types/IHubEntityBase.ts, packages/common/src/core/types/IHubItemEntity.ts, packages/common/src/pages/_internal/computeProps.ts, packages/common/src/search/types/IHubSearchResult.ts, packages/common/src/sites/_internal/computeProps.ts, packages/common/test/content/computeProps.test.ts, packages/common/test/content/fetch.test.ts, packages/common/test/pages/_internal/computeProps.test.ts, packages/common/test/sites/_internal/computeProps.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/7521
Moves the "links" property into IHubEntityBase and adds "layoutRelative" as an option.
Before this PR,  "links" was part of IHubSearchResult. Since IHubSearchResult extends IHubEntityBase, no
change is needed on the search side. However, by moving "links" to IHubEntityBase, we are laying the
foundation for IHubSearchResults and IHubEntitys to have the same link structure.
I started by implementing basic links for IHubPage, IHubSite and IHubEditableContent.
Longer term, we'll want to figure out some basic questions like:
- should thumbnail have the token appended?
- should link generation be abstracted into a function or be created ad-hoc in each entity's `computeProps` function?
- should IHubSearchResults always populate …
=> feat(hub-common): add unified "links" hash as an optional property for all entities

package-lock.json, packages/common/src/content/_internal/ContentBusinessRules.ts, packages/common/src/discussions/_internal/DiscussionBusinessRules.ts, packages/common/src/groups/_internal/GroupBusinessRules.ts, packages/common/src/initiatives/_internal/InitiativeBusinessRules.ts, packages/common/src/pages/_internal/PageBusinessRules.ts, packages/common/src/projects/_internal/ProjectBusinessRules.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts
=> feat(hub-common): add hub:[entity]:manage permission for all entities

packages/common/src/content/_internal/computeProps.ts
1. Description: When loading content that has a licenseInfo set to `null`, the save button will show a validation error but without any description. To avoid this, I just added a pair of default empty quotes which is what the licenseInfo would be set to if the user previously cleared a selected license.
1. Instructions for testing: Try this item out before and after this PR -- 
- `yarn hc start`: http://localhost:3333/html/arcgis-hub-workspace/entity-workspace-harness.html?identifier=cd0d468f480244339b894ae2b65705b8&type=content
- `yarn start`: https://download-test-qa-pre-a-hub.hubqa.arcgis.com:4200/workspace/content/cd0d468f480244339b894ae2b65705b8/details
1. Closes Issues: [#7721](https://devtopia.esri.com/dc/hub/issues/7721)
1. [ ] Updated meaningful TSDoc to methods including …
=> fix: added default empty quotes for computeProps

package-lock.json, packages/common/src/groups/HubGroups.ts
1. Description: We weren't determining the workspaceRelative link for groups. This implements that. …
=> feat: add workspaceRelative to enrichGroupSearchResult

packages/common/src/core/schemas/internal/getFeaturedContentCatalogs.ts, packages/common/test/core/schemas/internal/getFeaturedContentCatalogs.test.ts
The internal function `getFeaturedContentCatalogs` should return an array of `IHubCatalogs`. It was previously implemented to return `{ catalogs }` to support the old implementation of `getEntityEditorOptions` which has since been refactored …
=> fix: ensure featured content catalogs are returned as an array

packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts, packages/common/src/initiatives/defaults.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts
- Add featured content to initiatives edit …
=> fix: add featured content to initiatives edit

package-lock.json, package.json, packages/common/package.json, packages/common/src/content/_internal/ContentSchema.ts, packages/common/src/content/_internal/ContentUiSchemaEdit.ts, packages/common/src/content/_internal/ContentUiSchemaSettings.ts, packages/common/src/content/_internal/computeProps.ts, packages/common/src/content/_internal/getPropertyMap.ts, packages/common/src/content/_internal/hostedServiceUtils.ts, packages/common/src/content/edit.ts, packages/common/src/content/fetch.ts, packages/common/src/content/hostedServiceUtils.ts, packages/common/src/content/index.ts, packages/common/src/core/schemas/internal/getEntityEditorSchemas.ts, packages/common/src/core/types/IHubEditableContent.ts, packages/common/src/items/_enrichments.ts, packages/common/test/content/_internal/ContentUiSchemaSettings.test.ts, packages/common/test/content/computeProps.test.ts, packages/common/test/content/edit.test.ts, packages/common/test/content/fetch.test.ts, packages/common/test/content/fixtures.ts, packages/common/test/content/hostedServiceUtils.test.ts, packages/common/test/core/schemas/internal/getEntityEditorSchemas.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/7210
Adds the content settings schema. This included adding the ability to fetch / update the underlying service definition for items that represent hosted feature services. All work was done within the `fetchHubEntity` and `updateHubEntity` flows
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to …
=> feat(hub-common): add content settings schemas and derive props from server definitions

package-lock.json, packages/common/src/content/fetch.ts, packages/common/test/content/fixtures.ts
=> fix(hub-common): fix fetchHubContent does not support slugs

package-lock.json, packages/common/src/ArcGISContext.ts, packages/common/src/ArcGISContextManager.ts, packages/common/src/types.ts, packages/common/test/ArcGISContextManager.test.ts
1. Description: adds partneredOrgs and partneredOrgIds to context. …
=> feat: partnered orgs added to context

packages/common/src/content/_internal/computeProps.ts, packages/common/src/content/edit.ts, packages/common/src/core/getTypeFromEntity.ts, packages/common/src/core/schemas/internal/getLocationExtent.ts, packages/common/src/core/schemas/internal/getLocationOptions.ts, packages/common/src/extent.ts, packages/common/test/content/computeProps.test.ts, packages/common/test/content/edit.test.ts, packages/common/test/core/schemas/internal/getLocationExtent.test.ts, packages/common/test/core/schemas/internal/getLocationOptions.test.ts, packages/common/test/extent/get-geographic-org-extent.test.ts, packages/common/test/extent/get-org-extent-as-bbox.test.ts
WIP
OD-UI: https://github.com/ArcGIS/opendata-ui/pull/12520
1. Description: Item extent now selectable in location picker for content items only.
- Test saving and refreshing for items in old view
- Test saving and refresh for items in new view
- Test item never saved in new view before properly loads in as "none" or "item"
- Test item saved in new view translates correctly to "none" or "item" when in old view
- Test item saved in new view and then in old view ports item back in correctly in new view
- i.e. save a custom location -- view it as a bbox in old view -- edit bbox in old view -- check that it is now saved as item extent with that bbox in new view
Test saving:
- Workspaces: http://localhost:3333/html/arcgis-hub-workspace/entity-workspace-harness.html? …
=> feat: item extent now selectable, savable, and reflects in old and new view

package-lock.json, packages/common/src/discussions/api/types.ts
1. Description: Adding `groups` to `IUpdateChannelPermissions` to allow for updating a channel's groups
1. Closes Issues: [#7572](https://zentopia.esri.com/workspaces/engagement-workspace-61508ae50946c40014ef574f/issues/dc/hub/7572) with hub-discussions [pr-428](https://devtopia.esri.com/dc/hub-discussions/pull/428) …
=> feat(hub-discussions): adding ability to update the groups of a channel

.github/workflows/deploy-docs.yml, .github/workflows/release.yml, docs/build-typedoc.js, docs/src/_layout.html
- Change GH actions so the deploy-docs workflow fires _after_ the release workflow. This should ensure that the latest package version number is in the docs, vs the previous version as it is now.
- also inject a date into a meta tag in the page so we can get a better idea when pages were updated
`<meta name="date" content="2023-09-18T19:57:15.426Z">`
1. [ …
=> docs: add timestamp into html as meta header

packages/common/src/content/HubContent.ts, packages/common/src/core/EntityEditor.ts, packages/common/src/core/behaviors/IWithEditorBehavior.ts, packages/common/src/core/enrichEntity.ts, packages/common/src/core/schemas/internal/enrichEntity.ts, packages/common/src/core/types/IHubDiscussion.ts, packages/common/src/core/types/IHubEditableContent.ts, packages/common/src/core/types/IHubInitiative.ts, packages/common/src/core/types/IHubItemEntity.ts, packages/common/src/core/types/IHubPage.ts, packages/common/src/core/types/IHubProject.ts, packages/common/src/discussions/HubDiscussion.ts, packages/common/src/groups/HubGroup.ts, packages/common/src/initiatives/HubInitiative.ts, packages/common/src/pages/HubPage.ts, packages/common/src/projects/HubProject.ts, packages/common/src/sites/HubSite.ts, packages/common/test/content/HubContent.test.ts, packages/common/test/core/EntityEditor.test.ts, packages/common/test/core/enrichEntity.test.ts, packages/common/test/core/schemas/internal/enrichEntity.test.ts, packages/common/test/discussions/HubDiscussion.test.ts, packages/common/test/groups/HubGroup.test.ts, packages/common/test/initiatives/HubInitiative.test.ts, packages/common/test/pages/HubPage.test.ts, packages/common/test/projects/HubProject.test.ts, packages/common/test/sites/HubSite.test.ts
[7621](https://devtopia.esri.com/dc/hub/issues/7621)
- make `toEditor` in `IWithEditorBehavior` and all associated class methods async
- add new arg, `include`, to the `toEditor` class method
- add `enrichEntity` util that delegates to helper functions to add async enrichments to the entity. For now, only a followers group enrichment is supported. `enrichEntity` gets called from all `toEditor` class methods with the array of `include` strings provided
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release …
=> feat: add option to enrich an entity 

packages/common/src/initiatives/_internal/InitiativeUiSchemaCreate.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts, packages/common/src/projects/_internal/ProjectUiSchemaCreate.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts, packages/common/src/sites/_internal/SiteUiSchemaCreate.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaCreate.test.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts, packages/common/test/projects/_internal/ProjectUiSchemaCreate.test.ts, packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts, packages/common/test/sites/_internal/SiteUiSchemaCreate.test.ts
[7926](https://devtopia.esri.com/dc/hub/issues/7926)
when transitioning `uiSchemas` to export a function rather than a `const`, I missed a few "}" in the `uiSchema` translation keys …
=> fix: uiSchema translation keys

packages/common/src/discussions/api/types.ts
=> feat(hub-common): add blocked as a possible PostStatus

packages/common/src/projects/HubProject.ts, packages/common/test/projects/HubProject.test.ts
[7937](https://devtopia.esri.com/dc/hub/issues/7937)
currently we _always_ pre-populate the "Share with..." field on project creation with the site's content and collaboration group IDs. If the current user isn't a member of these groups/doesn't have the ability to share with these groups, this results in a console error because we still try sharing the project with these groups. This PR adds additional checks to avoid this issue.
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release …
=> fix: auto-populating groups in project creation

package-lock.json, packages/common/src/permissions/_internal/checkOwner.ts, packages/common/src/permissions/_internal/checkPrivileges.ts, packages/common/test/permissions/_internal/checkOwner.test.ts, packages/common/test/permissions/_internal/checkPrivileges.test.ts
1. Description: checkPrivileges can throw if called when unauthenticated.
1. Closes Issues: No issue, just something i noticed. …
=> fix: checkPermission and checkPrivileges first check isAuthenticated

package-lock.json, packages/common/src/content/_internal/computeProps.ts, packages/common/src/core/types/IHubLocation.ts
also relax IHubLocation.geometries to accept POJOs …
=> fix(hub-common): content location should be of type extent, not polygon

package-lock.json, packages/common/src/sites/HubSite.ts, packages/common/test/sites/HubSite.test.ts
1. Description: handle undefined context.portal
1. Related: https://devtopia.esri.com/dc/hub/issues/7975
=> fix: handle undefined context.portal

.github/workflows/release.yml, package-lock.json, packages/common/src/sites/HubSite.ts, packages/common/test/sites/HubSite.test.ts
=> Revert "13.17.x patch"

.github/workflows/release.yml, package.json, packages/common/src/sites/HubSite.ts, packages/common/test/sites/HubSite.test.ts
=> fix(hub-common): handle undefined context.portal

.github/workflows/release.yml, package.json
_May_ allow for maintenance releases on old channels under some circumstances. This did not work for my specific scenario but may work for others.
My scenario would not work because I wanted to release hub-common 13.17.4 based on @esri/hub-common@13.17.3 but the git history of that tag contains discussions releases in the 25.x range.
=> chore: allow for maintenance releases

package-lock.json, packages/common/src/core/getRelativeWorkspaceUrl.ts, packages/common/test/core/getRelativeWorkspaceUrl.test.ts
1. Description: workspace route for content is /workspace/content/:id not /workspace/contents/:id
1. Related: [7992](https://devtopia.esri.com/dc/hub/issues/7992) …
=> fix(hub-common): properly compute workspace route for content

packages/common/src/core/types/IHubEntityBase.ts, packages/common/src/groups/HubGroups.ts, packages/common/src/groups/_internal/computeLinks.ts, packages/common/src/groups/_internal/computeProps.ts, packages/common/src/initiatives/HubInitiatives.ts, packages/common/src/initiatives/_internal/computeLinks.ts, packages/common/src/initiatives/_internal/computeProps.ts, packages/common/src/projects/_internal/computeLinks.ts, packages/common/src/projects/_internal/computeProps.ts, packages/common/src/projects/fetch.ts, packages/common/test/groups/_internal/computeLinks.test.ts, packages/common/test/groups/_internal/computeProps.test.ts, packages/common/test/initiatives/_internal/computeLinks.test.ts, packages/common/test/initiatives/_internal/computeProps.test.ts, packages/common/test/projects/_internal/computeLinks.test.ts, packages/common/test/projects/_internal/computeProps.test.ts
- centralize link logic for project, initiative, and group entities by adding an internal `computeLinks` util for each
- call `computeLinks` form `computeProps` and `enrich<Entity>SearchResult` to generate a links hash for project, initiative and group entities/search results …
=> feat: add links hash for project, initiative, and group entities

packages/common/src/search/wellKnownCatalog.ts, packages/common/test/search/wellKnownCatalog.test.ts
Add Project to wellKnownCatalogs and add Projects to default collections in wellKnownColletions. Issue [8052](https://zentopia.esri.com/workspaces/collaboration-sprint-board-614f9bfc0946c40011ef574e/issues/dc/hub/8052)
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can …
=> fix: add Project to wellKnownCatalogs

package-lock.json, packages/common/src/ArcGISContextManager.ts, packages/common/test/ArcGISContextManager.test.ts
1. Description: We weren't properly deserializing trustedOrgs/trustedOrgIds from the context so issues were occurring in the app like "refreshing the page wasn't properly fleshing out the context so there were issues in some components" 
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to …
=> fix: properly deserialize trustedOrgs from context

packages/common/src/discussions/api/types.ts
1. Description: Added `author` and `editor` params to `ISearchChannels` interface
2. Related Issues: #<9781> ([if appropriate](https://zentopia.esri.com/workspaces/engagement-workspace-61508ae50946c40014ef574f/issues/dc/hub/7981))
3. [ ] Updated meaningful TSDoc to methods including Parameters and Returns, see [Documentation Guide](https://esri.github.io/hub-components/storybook/?path=/story/guides-documentation--page)
4. [X] used semantic commit messages
5. [X] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation will not run!)
6. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See …
=> fix(hub-discussions): add author and editor to isearchchannels

packages/common/src/content/_internal/ContentBusinessRules.ts
OD-UI: https://github.com/ArcGIS/opendata-ui/pull/12617
1. Description: Added a collaborators pane to the content workspace. Has the same features as the collaborators pane in the site workspace.
- Open the content workspace for a content item
- View the collaborators tab
- Make changes to the `Groups that can edit` and `Groups that can view`
- Feel free to test with my content item: `88b077a232224e52b684eacd2ecdda5f`
1. Closes Issues: [7942](https://devtopia.esri.com/dc/hub/issues/7942)
1. [x] PR title follows semantic commit format …
=> feat: collaborator pane for content workspace

packages/common/src/groups/_internal/computeLinks.ts, packages/common/test/groups/HubGroups.test.ts, packages/common/test/groups/_internal/computeLinks.test.ts
Update groups link from teams/:id to groups/:id
1. Closes Issues: #<8043> (if appropriate) …
=> fix: update groups link from teams to groups

packages/common/src/utils/index.ts, packages/common/src/utils/poll.ts, packages/common/test/utils/poll.test.ts
[8012](https://devtopia.esri.com/dc/hub/issues/8012)
There have been a couple of instances lately where we've observed a slight delay between creating, sharing, etc. using the rest API and the information registering on a subsequent fetch of the item. Rather than setting a random timeout, the better approach is to poll the API. 
This PR adds a new `poll` util which accepts a generic request and validation function and will execute the request until the validation condition(s) have been met or a timeout is reached.  
1. [x] PR title follows semantic commit format …
=> feat: add new polling util

package-lock.json, packages/common/e2e/associations.e2e.ts, packages/common/e2e/context-manager.e2e.ts, packages/common/e2e/hub-user-search.e2e.ts, packages/common/e2e/user-app-resources.e2e.ts, packages/common/src/ArcGISContext.ts, packages/common/src/ArcGISContextManager.ts, packages/common/src/utils/getObjectSize.ts, packages/common/src/utils/hubUserAppResources.ts, packages/common/src/utils/index.ts, packages/common/src/utils/internal/clearUserHubSettings.ts, packages/common/src/utils/internal/clearUserSiteSettings.ts, packages/common/src/utils/internal/siteSettingsMigrations.ts, packages/common/src/utils/internal/userAppResources.ts, packages/common/src/utils/userAppResources.ts, packages/common/test/ArcGISContextManager.test.ts, packages/common/test/utils/getObjectSize.test.ts, packages/common/test/utils/hubUserAppResources.test.ts, packages/common/test/utils/internal/clearUserHubSettings.test.ts, packages/common/test/utils/internal/clearUserSiteSettings.test.ts, packages/common/test/utils/internal/userAppResources.test.ts
- Adds low-level functions for user app resources 
```
export function setUserResource(
resource: IAddUserResource,
username: string,
portalUrl: string,
token: string,
replace: boolean = false
): Promise<void> {...}
export function getUserResource(
username: string,
key: string,
portalUrl: string,
token: string
): Promise<Record<string, any>> {...}
export function removeUserResource(
username: string,
key: string,
portalUrl: string,
token: string
): Promise<Record<string, any>> {...}
export function listUserResources(
username: string,
portalUrl: string,
token: string,
returnAllApps: boolean = false
): Promise<IUserResourceListResponse> {...}
```
- Adds abstraction functions for Site level settings
```
export function setUserSiteSettings(
settings: IUserSiteSettings, …
```
=> feat: support for Site and Hub user app resources

packages/common/src/sites/_internal/SiteUiSchemaEdit.ts, packages/common/test/sites/_internal/SiteUiSchemaEdit.test.ts
OD-UI: https://github.com/ArcGIS/opendata-ui/pull/12633
**Note**: A tech ticket for the other portions of #7730 is slated to be done soon. This is what we can accomplish with what is currently available.
1. Description: Polishing the details pane for site workspace. More coming post-tech ticket.
- Open the site workspace
- Visit my fake site: 8e67c41951804ef9965e290b3d83c182
- Open the details pane
- Confirm "Basic Info" is now "Basic Information"
- Confirm Description section now uses CK5 editor and saves different HTML properly
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/7730
1. [ ] Updated meaningful TSDoc to methods including Parameters and Returns, see [Documentation Guide](https://esri.github.io/hub-components/storybook/?path=/story/guides- …
=> feat: polishing details pane for site workspace

packages/common/src/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.ts, packages/common/src/templates/_internal/TemplateUiSchemaEdit.ts, packages/common/test/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.test.ts, packages/common/test/templates/_internal/TemplateUiSchemaEdit.test.ts
[7732](https://devtopia.esri.com/dc/hub/issues/7732)
update the `uiSchema` for templates and initiative templates for string purposes …
=> fix: template workspace strings

packages/common/src/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.ts, packages/common/test/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.test.ts
1. Description: Follow up to previous PR to ensure consistency across all details panes
1. Instructions for testing: Converted initiative template details pane to use a "Section" and added label on OD-UI
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/7730 …
=> feat(hub-common): add section heading for template ui schemas

packages/common/src/templates/_internal/computeLinks.ts, packages/common/test/templates/_internal/computeLinks.test.ts
[7735](https://devtopia.esri.com/dc/hub/issues/7735)
- add `advancedEditRelative` url to template links hash
- update relevant tests …
=> feat: add advancedEditRelative to template links hash

packages/common/src/sites/index.ts, packages/common/src/sites/reharvestSiteCatalog.ts, packages/common/test/sites/reharvestSiteCatalog.test.ts
=> feat(hub-common): add "reharvestSiteCatalog" util

package-lock.json, packages/common/src/discussions/api/types.ts
1. Description: added paging params to `IFetchPost`
1. Related Issue: [#6172](https://zentopia.esri.com/workspaces/engagement-workspace-61508ae50946c40014ef574f/issues/dc/hub/6172) …
=> feat(hub-discussions): added paging params to IFetchPost

packages/common/src/content/_internal/ContentUiSchemaEdit.ts, packages/common/src/discussions/_internal/DiscussionUiSchemaEdit.ts, packages/common/src/groups/_internal/GroupUiSchemaEdit.ts, packages/common/src/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaCreate.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts, packages/common/src/pages/_internal/PageUiSchemaEdit.ts, packages/common/src/projects/_internal/ProjectUiSchemaCreate.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts, packages/common/src/sites/_internal/SiteUiSchemaCreate.ts, packages/common/src/sites/_internal/SiteUiSchemaEdit.ts, packages/common/src/templates/_internal/TemplateUiSchemaEdit.ts, packages/common/test/content/_internal/ContentUiSchemaEdit.test.ts, packages/common/test/discussions/_internal/DiscussionUiSchemaEdit.test.ts, packages/common/test/groups/_internal/GroupUiSchemaEdit.test.ts, packages/common/test/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.test.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaCreate.test.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts, packages/common/test/pages/_internal/PageUiSchemaEdit.test.ts, packages/common/test/projects/_internal/ProjectUiSchemaCreate.test.ts, packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts, packages/common/test/sites/_internal/SiteUiSchemaCreate.test.ts, packages/common/test/sites/_internal/SiteUiSchemaEdit.test.ts, packages/common/test/templates/_internal/TemplateUiSchemaEdit.test.ts
1. Description: OD-UI PR: https://github.com/ArcGIS/opendata-ui/pull/12664
- calcite input --> calcite text area
- rows can now be used for textarea types
- vertical + none now used for textarea types
1. Instructions for testing: Confirm each workspace details pane has a summary textarea input with 4 rows
1. Closes Issues: [#8125](https://devtopia.esri.com/dc/hub/issues/8125)
1. [ ] updated `peerDependencies` as needed. …
=> refactor: rows with new calcite text area for details summary

packages/common/e2e/reset-users.e2e.ts
Address this issue, which may be causing problems with release
=> fix: address issue importing from a file thats not checked in

packages/common/src/core/traits/IWithViewSettings.ts, packages/common/src/core/types/Metrics.ts, packages/common/src/projects/defaults.ts
Adds the metric display configuration interface to hub.js. Called `IMetricDisplayConfig`. 
1. Closes Issues: [#6614](https://zentopia.esri.com/workspaces/collaboration-sprint-board-614f9bfc0946c40011ef574e/issues/dc/hub/6614)
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do …
=> feat(hub-common): add metric display config to hub.js

packages/common/src/content/_internal/ContentBusinessRules.ts, packages/common/src/groups/_internal/GroupBusinessRules.ts, packages/common/src/initiative-templates/_internal/InitiativeTemplateBusinessRules.ts, packages/common/src/initiatives/_internal/InitiativeBusinessRules.ts, packages/common/src/pages/_internal/PageBusinessRules.ts, packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/types/Permission.ts, packages/common/src/projects/_internal/ProjectBusinessRules.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts, packages/common/src/templates/_internal/TemplateBusinessRules.ts
This PR makes changes to the permissions to address two issues:
- Control the "Privacy Mode" (Tracking Consent - how it works today, vs Privacy Consent - new UX)
- Setup Permissions to enable customers to opt into "Workspace Preview" 
To address this, I added 
```
const SystemPermissionPolicies: IPermissionPolicy[] = [
{
permission: "hub:feature:privacy", 
availability: ["alpha"],
environments: ["qaext"],
},
{
permission: "hub:feature:workspace",  // also replaces temp:workspace:released
availability: ["alpha"],
environments: ["devext", "qaext"],
},
];
```
In addition, for all Entities (other than Projects), I created a new permission `hub:<entity>:workspace`, which depends on `hub:feature:workspace`, centralizing access to all un-released workspaces behind a single …
=> feat: add permission for privacy; refactor workspace permissions

packages/common/src/search/_internal/commonHelpers/getTopLevelPredicate.ts, packages/common/src/search/_internal/commonHelpers/isNilOrEmptyString.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/getFilterQueryParam.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/getOgcAggregationQueryParams.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/getOpenDataQueryParam.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/getQueryString.ts, packages/common/test/search/_internal/getTopLevelPredicate.test.ts, packages/common/test/search/_internal/hubSearchItems.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/5706
This PR facilitates using the new search logic on umbrella search pages, which makes use of the boolean `openData` queryable on the OGC API
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. …
=> feat(hub-common): allow boolean predicates for OGC searches, openData flag for OGC aggs requests

packages/common/src/pages/_internal/PageSchema.ts
1. Description: Changed PageSchema to include _thumbnail like the other Schemas!
- Go to Page workspace
- open details pane
- confirm all inputs are there and console is clear of errors
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/8123
Before:
After:
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update …
=> fix(hub-common): page schema missing _thumbnail; caused details pane to crash

packages/common/src/core/schemas/internal/getCardEditorSchemas.ts, packages/common/src/core/schemas/internal/metrics/StatCardUiSchema.ts, packages/common/test/core/schemas/internal/metrics/StatCardUiSchema.test.ts
Removes the i18nscope from the stat card uiSchema to allow for no scope to be passed in. …
=> fix(): remove scope from uiSchema for stat card

packages/common/src/search/upgradeCatalogSchema.ts, packages/common/test/search/upgradeCatalogSchema.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/7187
=> feat(hub-common): upgradeCatalogSchema handles "orgId" field in legacy catalogs

packages/common/src/objects/deepFilter.ts, packages/common/src/objects/deepFind.ts, packages/common/src/objects/index.ts, packages/common/src/objects/internal/isFindable.ts, packages/common/test/objects/deepFilter.test.ts
[4980](https://devtopia.esri.com/dc/hub/issues/4980)
Adds a new `deepFilter` util that traverses a graph and filters out entries that do not pass a provided predicate. This is needed for work being done in the UI involving nested action links, but is generally a helpful and reusable util.  …
=> feat: add new deepFilter util

packages/common/src/search/upgradeCatalogSchema.ts, packages/common/test/search/upgradeCatalogSchema.test.ts
1. Description: This PR fixes catalog query filter.
1. Closes Issues: #[8262](https://devtopia.esri.com/dc/hub/issues/8262#)(if appropriate) …
=> fix(hub-common): fix catalog filter query

packages/common/src/sites/_internal/_migrate-telemetry-config.ts, packages/common/src/sites/site-schema-version.ts, packages/common/test/sites/_internal/_migrate-telemetry-config.test.ts, packages/sites/src/drafts/site-draft-include-list.ts
affects: @esri/hub-common, @esri/hub-sites
1. Description: Adds data.telemetry to site draft include list; redo telemetry migration because I failed to get the ui in sync with the migration last release. …
=> fix: add data.telemetry to site draft include list; redo telemetry config migration

packages/common/src/core/schemas/internal/metrics/setMetricAndDisplay.ts, packages/common/src/projects/HubProject.ts, packages/common/test/projects/HubProject.test.ts
Fixes an issue where if metricDisplays was undefined, the operation would not complete correctly. 
Fixes hub-components failed test from entit-editor in testing suite with preview version: 
1. Closes Issues: No issue -- discovered as a blocker to hub-components. 
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to …
=> fix(): update check for metricDisplays to have default

packages/common/src/permissions/HubPermissionPolicies.ts
We noticed that the gating of hub:feature:privacy does not really work the way we intended and that it can't really work the way we intended. So we now gate that feature to devext. Which means it is off in qaext and prod unless you provide `?pe=hub:feature:privacy`
=> fix: hub:feature:privacy is gated to devext

packages/common/src/content/_internal/ContentUiSchemaEdit.ts, packages/common/src/core/schemas/internal/EditorOptions.ts, packages/common/src/core/schemas/internal/getAuthedImageUrl.ts, packages/common/src/core/schemas/internal/getFeaturedImageUrl.ts, packages/common/src/core/schemas/internal/getLocationExtent.ts, packages/common/src/core/schemas/internal/getLocationOptions.ts, packages/common/src/core/schemas/internal/getTagItems.ts, packages/common/src/core/schemas/internal/getThumbnailUiSchemaElement.ts, packages/common/src/discussions/_internal/DiscussionUiSchemaEdit.ts, packages/common/src/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaCreate.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts, packages/common/src/pages/_internal/PageUiSchemaEdit.ts, packages/common/src/projects/_internal/ProjectUiSchemaCreate.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts, packages/common/src/sites/_internal/SiteUiSchemaCreate.ts, packages/common/src/sites/_internal/SiteUiSchemaEdit.ts, packages/common/src/templates/_internal/TemplateUiSchemaEdit.ts, packages/common/test/core/schemas/internal/getAuthedImageUrl.test.ts, packages/common/test/core/schemas/internal/getFeaturedImageUrl.test.ts, packages/common/test/core/schemas/internal/getLocationExtent.test.ts, packages/common/test/core/schemas/internal/getLocationOptions.test.ts, packages/common/test/core/schemas/internal/getTagItems.test.ts, packages/common/test/core/schemas/internal/getThumbnailUiSchemaElement.test.ts, packages/common/test/discussions/_internal/DiscussionUiSchemaEdit.test.ts, packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts
Refactors the utils in buildUiSchema to take specific props rather than the entire entity, allowing EntityEditorOptions to be strongly typed. 
1. Closes Issues: [8221](https://zentopia.esri.com/workspaces/collaboration-sprint-board-614f9bfc0946c40011ef574e/issues/dc/hub/8221)
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be …
=> tech(): refactor buildUiSchema Utils to not take EntityEditorOptions

packages/common/src/discussions/api/types.ts
1. Description: Updated `ICreatePost` param `parentId` to be string or null instead of optional
1. Closes Issues: [7408](https://zentopia.esri.com/workspaces/engagement-workspace-61508ae50946c40014ef574f/issues/dc/hub/7408) …
=> feat(hub-discussions): post parentId required

package-lock.json, packages/common/src/groups/_internal/convertHubGroupToGroup.ts, packages/common/test/groups/HubGroups.test.ts
1. Description: request, from arcgis-rest-request, does not allow one to use null/undefined's as empty vals. An empty string needs to be sent. ( https://github.com/Esri/arcgis-rest-js/blob/main/packages/arcgis-rest-request/src/utils/process-params.ts#L72-L75 ).
In this particular case membershipAccess was being stripped from the update call altogether when set to 'anyone'
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release …
=> fix: switch null to empty string for membershipAccess

packages/common/src/projects/_internal/ProjectBusinessRules.ts
Adds a metrics-coming-soon permission to project business rules to allow for a metrics pane to be developed without interrupting the coming-soon metrics pane.
1. Closes Issues: [#6661](https://zentopia.esri.com/workspaces/collaboration-sprint-board-614f9bfc0946c40011ef574e/issues/dc/hub/6661)
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can …
=> fix(): add metrics-coming-soon permission

packages/common/src/core/types/Metrics.ts, packages/common/src/projects/_internal/ProjectBusinessRules.ts
Adds the optional `visibility` prop to IMetricDisplayConfig.
=> feat(): allow metrics visibility

package-lock.json, packages/common/src/core/schemas/internal/metrics/editorToMetric.ts, packages/common/src/util.ts, packages/common/test/core/schemas/internal/metrics/editorToMetric.test.ts, packages/common/test/util.test.ts
This addresses some issues we ran into helping support debug issues with a DC site in PROD. We are unclear how they got the site into a state where the values array in the Expression for a Stat card had an entry that was an `{}`, but they did, and it caused an exception, which was uncaught, and ember went into a death spiral.
This PR simply adds a guard to make sure `.replace` method exists on the object passed into the `escape` predicate. The tests flex invalid-but-somehow-occured configurations.
1. [x] used semantic commit …
=> fix: add guards around excape predicate to avoid exceptions

packages/common/src/ArcGISContext.ts, packages/common/test/ArcGISContextManager.test.ts
adds `context.OGCApiUrl` for use in `hubSearch` or other parts of the app. 
1. Closes Issues: #[8461](https://devtopia.esri.com/dc/hub/issues/8461)
1. [ x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation will not run!) …
=> feat: add context.OGCApiUrl

packages/common/src/core/types/ActionLinks.ts, packages/common/src/core/types/index.ts
[8466](https://devtopia.esri.com/dc/hub/issues/8466)
introduce a new `HubActionLink` type that is a discriminated union of action link interfaces (external, content, well-known, section) …
=> feat: add generic action link interfaces/types

package-lock.json, packages/common/src/ArcGISContext.ts, packages/common/test/ArcGISContextManager.test.ts
Adds `context.refreshUser():Promise<void>` which can be used to force context to update it's cached version of the user, and their groups. This should be called by apps when the current user creates or removes groups, or when they join/leave groups.
1. Closes Issues: #8455
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** …
=> feat: add refreshUser method to context

packages/common/src/core/schemas/internal/metrics/setMetricAndDisplay.ts, packages/common/src/core/types/Metrics.ts
Changes the maximum amount of metrics allowed on an entity to 24. 
1. Closes Issues: #6633<number> (if appropriate)
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) …
=> fix(): update max size of metrics on an entity to 24

packages/common/src/core/index.ts, packages/common/src/core/processActionLinks.ts, packages/common/test/core/processActionLinks.test.ts
[8466](https://devtopia.esri.com/dc/hub/issues/8466)
adds new `processActionLink` and `processActionLinks` utils to "pre-process" a single `HubActionLink` or an array of `HubActionLinks`. For now, this involves transforming action links of `kind = "content"` into action links with an `href` that can be easily consumed in the UI. We can theoretically add additional "pre-processing" transforms to this util as they become necessary.
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation will not …
=> feat: add new processActionLinks utils

package-lock.json, packages/common/src/core/getEntityDefaultWorkspacePane.ts, packages/common/src/core/getRelativeWorkspaceUrl.ts, packages/common/src/core/index.ts, packages/common/test/core/getEntityDefaultWorkspacePane.test.ts, packages/common/test/core/getRelativeWorkspaceUrl.test.ts
ISSUES CLOSED: 8529, 8527
1. Description: Allows workspaces to route to specific panes.
1. Closes Issues: #8529, #8527 …
=> feat(hub-common): allow workspaces to route to specific panes

packages/common/src/core/types/Metrics.ts
Adds a constant for the limit of the number of featured metrics allowed on an entity. 
1. Closes Issues: #8181 (if appropriate) …
=> feat(): add featured metrics limit

packages/common/src/content/search.ts, packages/common/src/groups/HubGroups.ts, packages/common/src/initiative-templates/fetch.ts, packages/common/src/initiatives/HubInitiatives.ts, packages/common/src/pages/HubPages.ts, packages/common/src/projects/fetch.ts, packages/common/src/search/_internal/hubSearchChannels.ts, packages/common/src/search/types/IHubSearchResult.ts, packages/common/src/sites/HubSites.ts, packages/common/src/templates/fetch.ts, packages/common/src/users/HubUsers.ts, packages/common/test/initiative-templates/fixtures.ts, packages/common/test/initiatives/fixtures.ts, packages/common/test/projects/fixtures.ts, packages/common/test/search/_internal/hubSearchItems.test.ts, packages/common/test/templates/fixtures.ts, packages/common/test/users/fixtures.ts
Add `rawResult:  IItem | IGroup | IUser | IOgcItem | IChannel;` to `IHubSearchResult` and ensured it's set in all the places where a result is constructed, or used in a fixture. This sets things up for the next block of work where we have type specific functions that convert `IHubSearchResult` -> `IHubCardViewModel`, and a callback from gallery which would allow for custom logic for a specific gallery instance.
1. [x] PR title follows semantic commit format (**CRITICAL** if …
=> feat: search result has rawResult prop

packages/common/src/discussions/_internal/DiscussionSchema.ts, packages/common/src/discussions/_internal/DiscussionUiSchemaCreate.ts, packages/common/src/discussions/_internal/DiscussionUiSchemaEdit.ts, packages/common/test/discussions/_internal/DiscussionUiSchemaCreate.test.ts, packages/common/test/discussions/_internal/DiscussionUiSchemaEdit.test.ts
ISSUES CLOSED: 8534
1. Description: Removes prompt requirement.
1. Closes Issues: #8534 …
=> fix(hub-common): prompt no longer required

packages/common/src/core/schemas/internal/getEditorSchemas.ts, packages/common/src/groups/HubGroup.ts, packages/common/src/groups/HubGroups.ts, packages/common/src/groups/_internal/GroupBusinessRules.ts, packages/common/src/groups/_internal/GroupSchema.ts, packages/common/src/groups/_internal/GroupUiSchemaCreateFollowers.ts, packages/common/src/groups/_internal/getUniqueGroupTitle.ts, packages/common/src/permissions/_internal/checkAssertion.ts, packages/common/src/permissions/types/IPermissionPolicy.ts, packages/common/src/permissions/types/PolicyResponse.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts, packages/common/test/core/schemas/internal/getEditorSchemas.test.ts, packages/common/test/groups/HubGroup.test.ts, packages/common/test/groups/HubGroups.test.ts, packages/common/test/groups/_internal/GroupUiSchemaCreateFollowers.test.ts, packages/common/test/groups/_internal/getUniqueGroupTitle.test.ts, packages/common/test/permissions/_internal/checkAssertion.test.ts
[8257](https://devtopia.esri.com/dc/hub/issues/8257)
- add a new `uiSchema` to create followers groups
- hoist `getUniqueGroupTitle` util from `hub-teams` into `hub-common/groups` and leverage in group creation workflow
- gate followers pane on sites to premium licenses
- add permission for creating followers group
- add two new assertion types (`lenght-gt` and `length-lt`)
1. [x] updated `peerDependencies` as needed. …
=> feat: add logic/schema to allow follower group creation

packages/common/src/sites/reharvestSiteCatalog.ts, packages/common/test/sites/reharvestSiteCatalog.test.ts
1. Description: This PR fixes interface of the response returned by catalog re-harvest function `reharvestSiteCatalog()`. 
Indexer's harvest endpoint `/harvest` sample response on successfuly initiating re-harvest job: 
```
{
groups: [
{
"groupId":"430bd4970f4a4d9d886f966e1aa6eaa9",
"status":202,
"jobId":"c30af92d-661f-4ba4-9b77-93b69d57066a"
},
...
]
}
```
Response when continuously re-attempting to re-harvest in short period of time.
```
{
"message": "site has been harvested too recently",
"cause": "TIME_LOCK"
}
```
After updating the interface response, `cause` property of the response,  can be used to notify user know that re-harvest is already in progress on opendata-ui.
1. Closes Issues: [#8185](https://devtopia.esri.com/dc/hub/issues/8185)
1. [ ] …
=> fix(hub-common): fix reharvest site catalog response interface

packages/common/src/core/types/IItemEnrichments.ts, packages/common/src/items/_enrichments.ts, packages/common/src/search/_internal/portalSearchItems.ts, packages/common/test/items/_enrichments.test.ts
Add support of `include: ["item.itemControl"]` which requires re-fetching of the item to get this additional property that's not present on an item search result.
Also fixes a typo which was preventing includes from working.
1. Closes Issues: n/a - side effect of 8462 (gallery callback)
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can …
=> feat: add enrichement to refetch item with additional props

packages/common/src/content/edit.ts, packages/common/test/content/edit.test.ts
…ty service definition
1. Description: This PR fixes `updateServiceDefinition` payload when saving extract capability option to include only `capabilities` key as required instead of passing the whole service definition. This will prevent errors like [#7010](https://devtopia.esri.com/dc/hub/issues/7010)
1. Closes Issues: [#7010](https://devtopia.esri.com/dc/hub/issues/7010)
1. [x] updated …
=> fix(hub-common): use only capabilities key to update extract capability service definition

packages/common/src/utils/hubUserAppResources.ts
Add `.notices.dismissed: string[]` to `IUserHubSettings`
1. Instructions for testing: n/a - just a type change
1. Part of Issues: #8605
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section …
=> feat: add notices to IUserHubSettings

.github/workflows/release.yml
Update the GitHub token used in release to be a personal access token from Hub's GitHub service account. This will enable the implementation of the branch protection but allow the service account to bypass protection rules during the release (direct push to the master branch).
The secret has been created.
1. [ ] updated …
=> chore: update github token for release

packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts, packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts
1. Description: Changes project/initiative ui edit schemas to use rich text with provided toolbar. …
=> feat: initiative/project description fields are rich text

package-lock.json, packages/common/src/core/schemas/shared/HubItemEntitySchema.ts, packages/common/src/core/traits/IWithViewSettings.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts, packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts
- updates project ui schema to support action links
- will be included in opendata-ui pr
- [3630](https://devtopia.esri.com/dc/hub/issues/3630)
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. …
=> feat(): update projects schema

packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/checkPermission.ts, packages/common/src/permissions/types/Permission.ts, packages/common/test/permissions/checkPermission.test.ts
`checkPermission` integrates preview flags from `context.userHubSettings.preview`
1. Closes Issues: associated with #8495 …
=> fix: checkPermission uses userHubSettings.preview flags

packages/common/src/core/schemas/types.ts
[8280](https://devtopia.esri.com/dc/hub/issues/8280)
adds a "Deprecated" notice to the `IValidationResult` interface that shouldn't have been hoisted to `hub.js`. It is now duplicated in `opendata-ui` and should be used from there. We should remove this and `ajv` during the next breaking change …
=> chore: add deprecated notice to config editor interface

package-lock.json, packages/common/src/sites/_internal/SiteUiSchemaSettings.ts, packages/common/test/sites/_internal/SiteuUiSchemaTelemetry.test.ts
1. Description: adds label to site telemetry ui schema section
1. Related Issues: [8676](https://devtopia.esri.com/dc/hub/issues/8676) …
=> fix: adds label to site telemetry ui schema section

packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts
Reorder fields in initiative editor in below order, hide featured content for MVP
- Basic Information
- Name
- Purpose
- Description
- Hero
- Location
- Search & discoverability
- Tags
- Categories
- Thumbnail
- Status
- Featured Content …
=> fix: reorder fields in initiative editor, hide featured content for MVP

.github/workflows/release.yml
Update the GitHub token used in release to be a personal access token from Hub's GitHub service account. This will enable the implementation of the branch protection but allow the service account to bypass protection rules during the release (direct push to the master branch).
Compared to the original PR https://github.com/Esri/hub.js/pull/1349, this new PR adds a necessary parameter for the `checkout` action. It makes sure the `somatic-release` would use the provided token (not the one in the environment) for release. See discussion at https://github.com/semantic-release/semantic-release/issues/2636.
The secret has been created.
=> chore: re-enable branch protection

package-lock.json, packages/common/src/content/_internal/ContentUiSchemaEdit.ts, packages/common/src/discussions/_internal/DiscussionUiSchemaEdit.ts, packages/common/src/groups/_internal/GroupSchema.ts, packages/common/src/groups/_internal/GroupUiSchemaEdit.ts, packages/common/src/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts, packages/common/src/pages/_internal/PageUiSchemaEdit.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts, packages/common/src/templates/_internal/TemplateUiSchemaEdit.ts, packages/common/test/content/_internal/ContentUiSchemaEdit.test.ts, packages/common/test/discussions/_internal/DiscussionUiSchemaEdit.test.ts, packages/common/test/groups/_internal/GroupUiSchemaEdit.test.ts, packages/common/test/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.test.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts, packages/common/test/pages/_internal/PageUiSchemaEdit.test.ts, packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts, packages/common/test/templates/_internal/TemplateUiSchemaEdit.test.ts
1. Description: Transitions all description fields for workspace entities to be rich text fields …
=> feat: description fields to rich text

packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts, packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts
[3630](https://devtopia.esri.com/dc/hub/issues/3630)
Commenting out the CTA field on the project edit `uiSchema` until the `opendata-ui` side of changes are ready to be merged.  …
=> fix: tempoarily remove call to action from project edit uiSchema

packages/common/src/content/_internal/ContentBusinessRules.ts
Part of https://devtopia.esri.com/dc/hub/issues/2872
=> feat(hub-common): enable content settings for admins and add content delete permission

package-lock.json, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts, packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts
- updates project ui schema to support action links
- will be included in opendata-ui pr
- [3630](https://devtopia.esri.com/dc/hub/issues/3630)
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. …
=> fix(): add call to action to project edit uiSchema

packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts
Issue [9007](https://zentopia.esri.com/workspaces/collaboration-sprint-board-614f9bfc0946c40011ef574e/issues/gh/dc/hub/9007)
Fix the image description in initiative edit hero title select, it was previously set the same as the map mistakenly.
1. [x] updated `peerDependencies` as needed. **CRITICAL** our …
=> fix: image description in hero title select

packages/common/src/sites/HubSites.ts, packages/common/src/sites/_internal/migrateBadBasemap.ts, packages/common/src/sites/index.ts, packages/common/src/sites/upgrade-site-schema.ts, packages/common/test/sites/HubSites.test.ts, packages/common/test/sites/_internal/migrateBadBasemaps.test.ts, packages/common/test/sites/upgrade-site-schema.test.ts, packages/sites/src/drafts/upgrade-draft-schema.ts, packages/sites/test/drafts/upgrade-draft-schema.test.ts
Add "versonless" migration that looks for this the condition described in the issue, and resolving it.
1. Closes Issues: #[9049](https://devtopia.esri.com/dc/hub/issues/9049) …
=> fix: migrate malformed basemap hash resulting from hub.py bug

packages/common/src/core/schemas/internal/metrics/StatCardUiSchema.ts, packages/common/src/core/schemas/types.ts, packages/common/src/groups/_internal/GroupUiSchemaCreateFollowers.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaCreate.ts, packages/common/src/projects/_internal/ProjectUiSchemaCreate.ts, packages/common/src/sites/_internal/SiteUiSchemaCreate.ts, packages/common/test/core/schemas/internal/filterSchemaToUiSchema.test.ts, packages/common/test/core/schemas/internal/getUiSchemaProps.test.ts, packages/common/test/core/schemas/internal/metrics/StatCardUiSchema.test.ts, packages/common/test/core/schemas/internal/subsetSchema.test.ts, packages/common/test/groups/_internal/GroupUiSchemaCreateFollowers.test.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaCreate.test.ts, packages/common/test/projects/_internal/ProjectUiSchemaCreate.test.ts, packages/common/test/sites/_internal/SiteUiSchemaCreate.test.ts
[9010](https://devtopia.esri.com/dc/hub/issues/9010)
We're doing a refactor of our section implementation in the configuration editor over in `opendata-ui`. We need to update relevant `schemas`/`uiSchemas` accommodate these changes …
=> fix: config editor cleanup - update schemas

packages/common/src/core/schemas/internal/metrics/ProjectUiSchemaMetrics.ts, packages/common/src/core/schemas/types.ts, packages/common/test/core/schemas/internal/metrics/ProjectUiSchemaMetrics.test.ts
1. Closes Issues: [#9074](https://zentopia.esri.com/workspaces/sprint-board-60340b9721bc3a4ab6367db5/issues/gh/dc/hub/9074) …
=> fix(): add clearOnHidden to values in metrics

packages/common/src/objects/deepDeletePropByValue.ts, packages/common/src/objects/deepEqual.ts, packages/common/src/objects/index.ts, packages/common/test/objects/deepDeletePropByValue.test.ts, packages/common/test/objects/deepEqual.test.ts
Add `deepDeletePropByValue(obj, value):obj` and `deepEqual(a,b):boolean` util functions
Hub commonly applies migrations to entities on load. During those migrations, often we want to delete properties to clean things up. However, during the save process, we typically fetch the entity from it's backing store and spread the migrated entity over the top of the fetched entity. This results in the deleted props being re-added.
To avoid this, instead of deleting the props in the migration, we can set them to a specific value (e.g. `remove-this-prop`) and then use `deepDeletePropByValue` function to remove them, after the merge.
`deepEquals` was a useful side-effect of building this function.
This is a precursor to changes in some migrations.
1. Instructions for testing: run …
=> feat: add deepDeletePropByValue and deepEqual util functions

packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/types/Permission.ts
- add `hub:feature:workspace:umbrella` which is enabled for qa-alpha
- in UI (separate PR to follow), when this is enabled, the manage (⚙️) link will open the entity on the umbrella site for that env.
1. Closes Issues: #9260
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we …
=> feat: add permission to manage on umbrella

package-lock.json, packages/common/src/discussions/utils.ts, packages/common/src/search/_internal/hubSearchChannels.ts, packages/common/test/search/_internal/hubSearchChannels.test.ts
ISSUES CLOSED: 8922
1. Description: Refactors hubSearchChannels for more general use.
1. Closes Issues: #8922 …
=> fix(hub-common): refactor hubSearchChannels for more general use

packages/common/src/core/schemas/internal/follow/FollowCardUiSchema.ts, packages/common/src/core/schemas/internal/follow/FollowSchema.ts, packages/common/test/core/schemas/internal/follow/FollowCardUiSchema.test.ts
Update some follow card schema and UiSchema to better align with the design
1. Closes Issues: [9161](https://zentopia.esri.com/workspaces/sprint-board-60340b9721bc3a4ab6367db5/issues/gh/dc/hub/9161) …
=> feat: 9161 follow card schema update

packages/common/src/projects/_internal/ProjectBusinessRules.ts
[8968](https://devtopia.esri.com/dc/hub/issues/8968)
- add new `"hub:project:associations"` permission that gates associations to alpha dev/QA orgs
- update the existing `"hub:project:workspace:initiatives"` permission to depend on the new `"hub:project:associations"`
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it …
=> fix: add permission for project associations

package-lock.json, packages/common/src/discussions/_internal/DiscussionBusinessRules.ts
- [9265](https://devtopia.esri.com/dc/hub/issues/9265)
1. Closes Issues: #<9265> (if appropriate) …
=> feat(): remove temp discussions gating permission

package-lock.json, packages/common/src/permissions/HubPermissionPolicies.ts
1. Description: Adds permission for keyboard shortcuts
1. Related Issues: [9286](https://devtopia.esri.com/dc/hub/issues/9286)
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section …
=> feat: add system permission for keyboard shortcuts

packages/common/src/permissions/types/Permission.ts
1. Description: Ugh i forgot something with the last pr …
=> fix: fix the keyboard permission!

package-lock.json, packages/common/src/items/slugs.ts, packages/common/test/items/slugs.test.ts
[9306](https://devtopia.esri.com/dc/hub/issues/9306)
- Refactors `constructSlug` to take into account that individual typeKeywords have a max length of 256 characters
1. Closes Issues: #9306 (if appropriate)
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our …
=> fix(): constructSlug accounts for typekeyword max length of 256 chars

packages/common/src/ArcGISContext.ts, packages/common/src/core/hubHistory.ts, packages/common/src/core/index.ts, packages/common/src/index.ts, packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/checkPermission.ts, packages/common/src/permissions/types/Permission.ts, packages/common/src/utils/hubUserAppResources.ts, packages/common/test/ArcGISContext.test.ts, packages/common/test/ArcGISContextManager.test.ts, packages/common/test/core/hubHistory.test.ts, packages/common/test/mocks/mock-auth.ts
Add methods to context to add and removed entries from the auth'd users history, as well as option to clear the entire history. Also adds `updateUserHubSettings(...)` method as it was needed for the other methods, and streamlines some other use-cases
1. Closes Issues: #9265
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** …
=> feat: context has user history

packages/common/src/groups/_internal/GroupBusinessRules.ts
=> fix: remove group sharing

packages/common/src/permissions/checkPermission.ts, packages/common/test/permissions/checkPermission.test.ts
Since we don't enforce the passing of an `ArcGISContext` instance into `checkPermission`, we need to be tolerate of a context that does not have `userHubSettings` property.
- run tests …
=> fix: checkPermission tolerates context without userHubSettings

packages/common/src/groups/getWellKnownGroup.ts, packages/common/test/groups/getWellKnownGroup.test.ts
1. Description: Per Jay we want to default to isViewOnly: false for view/edit groups. …
=> fix: view edit isviewonly

packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/_internal/checkAvailability.ts, packages/common/src/permissions/types/IPermissionPolicy.ts, packages/common/src/permissions/types/PolicyResponse.ts, packages/common/test/permissions/_internal/checkAvailability.test.ts
Add a 'flag' option to `HubAvailability` and gate the new follow card behind the feature flag (?pe=hub:card:follow)
https://github.com/Esri/hub.js/assets/16672774/717667ac-cbe5-4953-8793-9cc45e5fa01b
1. Closes Issues: [9161](https://zentopia.esri.com/workspaces/sprint-board-60340b9721bc3a4ab6367db5/issues/gh/dc/hub/9161)
1. [x] updated `peerDependencies` …
=> fix: gate the new follow card behind the feature flag

package-lock.json, packages/common/src/items/slugs.ts, packages/common/test/items/slugs.test.ts
[9306](https://devtopia.esri.com/dc/hub/issues/9306)
- Fixes regression related to searching for items by slug when the provided slug is falsey
1. Closes Issues: #9306 …
=> fix(): findItemsBySlug short-circuits to resolve empty array when slug is falsey

packages/common/src/events/api/orval/api/orval-events.ts, packages/common/test/events/api/events.test.ts
1. Description: Type updates for new events schema (event.onlineMeetings) …
=> feat(hub-common): update events schema for onlineMeetings

packages/common/src/permissions/HubPermissionPolicies.ts
Adds prod alpha orgs to `hub:feature:workspace`. This will be connected to draft PR -> https://github.com/ArcGIS/opendata-ui/pull/13197, where I've verified behavior against PROD
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs …
=> fix: add prod alpha orgs to hub:feature:workspace

packages/common/src/groups/_internal/GroupBusinessRules.ts, packages/common/src/permissions/_internal/checkAssertions.ts, packages/common/src/permissions/types/IPermissionPolicy.ts, packages/common/test/permissions/_internal/checkAssertions.test.ts
Adds conditions to assertion logic. A condition dictates if an assertion should be checked or not. If the condition evaluates to false, the assertion can be ignored. 
We implement this logic at the checkAssertions level, as we want to determine if an assertion is relevant first before evaluating it. 
Use case: Groups with `isViewOnly: false` allow any group member to share content; groups with `isViewOnly: true` allow only group admins to share content. To use just one permission for sharing content, we use a condition on `entity.isViewOnly` to understand which assertion currently applies: `is-group-member` or `is-group-admin`. 
1. Closes Issues: #9090 (if appropriate)
1. [X] Updated meaningful TSDoc to methods including Parameters and Returns, …
=> feat(): implement assertion conditions

package-lock.json, packages/common/src/ArcGISContext.ts, packages/common/src/resources/get-org-thumbnail-url.ts, packages/common/src/resources/get-portal-thumbnail-url.ts, packages/common/src/resources/index.ts, packages/common/test/ArcGISContextManager.test.ts, packages/common/test/resources/get-portal-thumbnail-url.test.ts
- adds getOrgThumbnailUrl function
- adds orgThumbnailUrl to IArcGISContext
1. Instructions for testing: run the tests
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release …
=> feat: org thumbnail

packages/common/src/core/schemas/internal/metrics/StatCardUiSchema.ts, packages/common/test/core/schemas/internal/metrics/StatCardUiSchema.test.ts
[9537](https://devtopia.esri.com/dc/hub/issues/9537)
Removes the unused `scope` on the `subblock` section in the stat card editor `uiSchema`.  …
=> fix: remove unused scope on subblock section in stat card editor uiSchema

package-lock.json, packages/common/src/events/api/orval/api/orval-events.ts, packages/common/src/events/api/types.ts, packages/common/test/events/api/events.test.ts
=> feat(hub-common): update events types

packages/common/src/core/types/IHubGroup.ts, packages/common/src/groups/_internal/getPropertyMap.ts, packages/common/test/groups/HubGroups.test.ts
Needed so we can send telemetry with `orgId`
1. Part of Issues: #9254 (if appropriate) …
=> feat: add orgId to IHubGroup

packages/common/src/ArcGISContext.ts, packages/common/src/surveys/utils/get-s123-share-url.ts, packages/common/src/surveys/utils/index.ts, packages/common/test/ArcGISContextManager.test.ts, packages/common/test/surveys/edit.test.ts, packages/common/test/surveys/utils/get-s123-share-url.test.ts
=> feat(hub-common): add s123 url to context

packages/common/src/content/_internal/ContentBusinessRules.ts, packages/common/src/discussions/_internal/DiscussionBusinessRules.ts, packages/common/src/groups/_internal/GroupBusinessRules.ts, packages/common/src/initiative-templates/_internal/InitiativeTemplateBusinessRules.ts, packages/common/src/initiatives/_internal/InitiativeBusinessRules.ts, packages/common/src/pages/_internal/PageBusinessRules.ts, packages/common/src/permissions/_internal/checkAssertion.ts, packages/common/src/permissions/types/IPermissionPolicy.ts, packages/common/src/permissions/types/PolicyResponse.ts, packages/common/src/projects/_internal/ProjectBusinessRules.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts, packages/common/src/surveys/_internal/SurveyBusinessRules.ts, packages/common/src/templates/_internal/TemplateBusinessRules.ts, packages/common/test/permissions/_internal/checkAssertion.test.ts
[9580](https://devtopia.esri.com/dc/hub/issues/9580)
- extends the permission assertion types to support "contains-some"
- adds a new `hub:{entity}:canChangeAccess` to all entities based on the following logic to determine whether the current user can edit the access of the entity:
**For item entities:**
1. user has the (`portal:admin:shareToOrg` OR `portal:admin:shareToPublic`) OR (`portal:user:shareToOrg` OR `portal:user:shareToPublic`) privileges
AND
3. user has admin privileges over the item (`itemControl:admin`)
**For group entities:**
1. user has the `portal:admin:updateGroups` privilege
OR
4. user has admin or owner membership in the group
1. [x] Updated meaningful TSDoc to methods including Parameters and Returns, see [Documentation …
=> feat: add canEditAccess permission to all entities

packages/common/src/discussions/_internal/DiscussionBusinessRules.ts, packages/common/src/surveys/_internal/SurveyBusinessRules.ts
Fixes issues with Survey & Discussion Board permissions
1. Closes Issues: [9924](https://devtopia.esri.com/dc/hub/issues/9924) & [9925](https://devtopia.esri.com/dc/hub/issues/9925)
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the …
=> fix(hub-common): fix discussion board and survey permissions

package-lock.json, packages/common/src/initiatives/_internal/InitiativeBusinessRules.ts
1. Description: We needed to expand edit permissions for initiatives to allow for hub basic.  …
=> fix: initiatives can be edited by premium and basic users

packages/common/src/events/api/orval/api/orval-events.ts, packages/common/src/events/api/types.ts
- Add tags and categories to events. (`IEvent`, `ICreateEvent`, `IUpdateEvent`, `GetEventsParams`)
- Add events enums `SortOrder` and `EventSort`
- Add `sortBy` and `sortOrder` to `GetEventsParams`
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to …
=> fix(hub-common): add tags and categories to events

packages/common/src/content/_internal/ContentBusinessRules.ts
This PR adds a permission to enable recording of download errors from hosted download cards for only DEV and QA environments.
1. Closes Issues: [#9591 ](https://devtopia.esri.com/dc/hub/issues/9591)
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when …
=> feat(hub-common): add permission to capture download errors

package-lock.json, packages/common/src/core/schemas/internal/metrics/MetricSchema.ts
1. Description: Adds url validation to stat card schema for sourceLink …
=> fix: metric/stat card schema sourceLink does url validation

packages/common/src/core/schemas/internal/follow/FollowSchema.ts
update unfollow button to from outline to outline-fill …
=> fix: update unfollow button to outline-fill

packages/common/src/content/compose.ts
ISSUES CLOSED: 9318
- Adds `event` icon to `getContentTypeIcon` method
1. Closes Issues: #9318 …
=> fix(hub-common): add event icon to getContentTypeIcon method

packages/common/src/content/_internal/ContentBusinessRules.ts
Adding permission for errors that we want to display in accordions in opendata-ui
**confirmed with Dave that this is the permission structure he wanted**
1. Closes Issues: #[1522](https://devtopia.esri.com/dc/hub/issues/1522)
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do …
=> feat: added permission for download errors

packages/common/src/events/api/orval/api/orval-events.ts
1. Description: add `status` to `IUpdateEvent`
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of …
=> fix(hub-common): add status to IUpdateEvent

package-lock.json, packages/common/src/permissions/HubPermissionPolicies.ts
1. Description: opens `hub:feature:user:preferences` to all of dev and qa (not just alpha orgs).
=> feat: loosen hub:feature:user:preferences permission 

packages/common/src/content/_internal/internalContentUtils.ts, packages/common/src/initiatives/HubInitiatives.ts, packages/common/src/initiatives/_internal/computeLinks.ts, packages/common/src/search/_internal/portalSearchItems.ts, packages/common/test/content/content.test.ts, packages/common/test/initiatives/HubInitiatives.test.ts, packages/common/test/initiatives/_internal/computeLinks.test.ts
Hooks up initiative enrichment on search results, and updates computeLinks so that we link to `/initiatives/:id` and not `/content/:id` or `/initiatives2/:id`.  …
=> feat(): enrich initiatives with correct links

packages/common/src/access/can-edit-event.ts, packages/common/test/access/can-edit-event.test.ts
[10051](https://devtopia.esri.com/dc/hub/issues/10051)
update the `can-edit-event` util to fallback to the `collaborationGroupId` stored on the `site.properties` …
=> fix: update can-edit-event to work in cases where initiative is deleted

package.json, packages/common/src/core/traits/ICapabilityConfig.ts, packages/common/src/core/traits/index.ts, packages/common/src/core/types/IHubProject.ts, packages/common/src/events/_internal/EventBusinessRules.ts, packages/common/src/initiatives/_internal/InitiativeBusinessRules.ts, packages/common/src/initiatives/_internal/getPropertyMap.ts, packages/common/src/projects/_internal/ProjectBusinessRules.ts, packages/common/src/projects/_internal/getPropertyMap.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts, packages/common/src/sites/_internal/getPropertyMap.ts
- Adds types for the entity-view system (see https://confluencewikidev.esri.com/display/Hub/UI+Architecture%3A+Views%2C+Workspaces+and+Layouts)
- Add permissions to enable `events` for all the entities (other than... events)
1. Instructions for testing: n/a 
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ …
=> feat: types for entity views

packages/common/src/core/schemas/internal/follow/FollowCardUiSchema.ts
- add helper texts for follow card editor
- remove "Favorite" filter …
=> fix: add helper texts and remove "Favorite" filter in follow card editor

packages/common/src/core/types/index.ts
1. Description: exports the interfaces used by the scheduler component from the types file and allows for cleaner imports from hub-common in other repos/packages
1. Closes Issues: [2068](https://devtopia.esri.com/dc/hub/issues/2068)
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. …
=> fix: proper export path for schedule interfaces

packages/common/src/content/_internal/getSchedulerApiUrl.ts, packages/common/src/content/manageSchedule.ts, packages/common/test/content/manageSchedule.test.ts
Adds check in `getSchedulerApiUrl` to remove the occasional `/api/v3` path from `requestOptions.hubApiUrl`. This was resulting in incorrect urls such as:
https://opendataqa.arcgis.com/api/v3/api/download/v1/items/f4bcc1035b7d46cba95e977f4affb6be/schedule
=> fix(hub-common): fix the target api url in getSchedule(), setSchedule(), etc

packages/common/src/discussions/utils.ts, packages/common/src/sites/HubSite.ts, packages/common/test/sites/HubSite.test.ts
affects: @esri/hub-common, @esri/hub-sites
ISSUES CLOSED: 10185
1. Closes Issues: [#<number> (if appropriate)](https://devtopia.esri.com/dc/hub/issues/10185) …
=> fix: isDiscussable handles undefined subject

packages/common/src/sites/HubSite.ts
ISSUES CLOSED: 10185
1. Description: broaden check for isDiscussable to handle faley, not just undefined
1. Closes Issues: 10185 …
=> fix: broaden check for isDiscussable to handle falsey, not just undefined

packages/common/e2e/hub-groups.e2e.ts, packages/common/src/core/fetchHubEntity.ts, packages/common/src/groups/HubGroup.ts, packages/common/src/groups/HubGroups.ts, packages/common/src/groups/_internal/convertGroupToHubGroup.ts, packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/test/core/fetchHubEntity.test.ts
- change the ro parameter that `fetchHubGroup` takes from `userRequestOptions` to `hubRequestOptions`, so anonymous users can fetch public groups from public sites
- add "hub-basic" license to follow card permission so hub basic users have access to follow cards …
=> fix: update fetchHubGroup ro and follow card permission

package-lock.json, packages/common/src/initiatives/_internal/InitiativeBusinessRules.ts
1. Description: Minor tweak to allow for initiatives workspace editing on prod (but still alpha gated) …
=> feat: initiative workspace gated to alpha, but open to prod

packages/common/src/initiatives/_internal/InitiativeUiSchemaCreate.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaCreate.test.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts
Adds helper text to the featured image flow.  …
=> feat(): add helper text to image

packages/common/src/core/traits/index.ts
Export `IWithFollowers` so we can assign it to certain hub entities as only entities extend `IWithFollowers` have access to the `followersGroupId` …
=> fix: export IWithFollowers

packages/common/src/content/_internal/ContentBusinessRules.ts
Part of [9627](https://devtopia.esri.com/dc/hub/issues/9627), missed in the initial PR …
=> fix(hub-common): restrict temp:hub:content:downloads:unifiedList to be behind a feature flag

packages/common/src/content/_internal/ContentBusinessRules.ts, packages/common/src/content/fetch.ts, packages/common/src/downloads/_internal/_types.ts, packages/common/src/downloads/_internal/format-fetchers/getCreateReplicaFormats.ts, packages/common/test/downloads/_internal/format-fetchers/getCreateReplicaFormats.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/9543
Addresses a number of small bugs that appeared in the first iteration of the new unified download utils …
=> fix(hub-common): fix unified list feature flag, format order, and additional resource calculation

packages/common/src/content/_internal/internalContentUtils.ts, packages/common/src/content/fetch.ts, packages/common/src/content/manageSchedule.ts, packages/common/test/content/manageSchedule.test.ts
1. Description: This PR adds  authenticated user `token` to content update schedule API endpoint. Soon, the schedule API will only accept request that have valid token in query parameter. PR implementing token in API endpoint is [here](https://github.com/ArcGIS/hub-download-api/pull/36). This PR has to be merged before the backend API PR. 
1. Closes Issues: #[9348](https://devtopia.esri.com/dc/hub/issues/9348)
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation …
=> feat(hub-common): add token to schedule api endpoints

package-lock.json, packages/common/src/search/_internal/portalSearchItems.ts
- updates hub Initiative query to include  `typekeyword: hubInitiativeV2` 
1. Closes Issues: #[10065](https://devtopia.esri.com/dc/hub/issues/10065) (if appropriate)
=> fix: updates well known types to fix gallery query

package-lock.json
- This PR updates the package-lock (pulled master and ran `npm i`) to correct a package-lock version change that was checked in. This doesn't need a new release.
=> revert: corrected package-lock by running npm i

packages/common/src/content/manageSchedule.ts, packages/common/test/content/fetch.test.ts
1. Description: My bad! I missed this in my previous [PR](https://github.com/Esri/hub.js/pull/1505). Sometimes `authentication` key of `requestOptions` could be `undefined` so `token` need to be retrieved using optional operator to avoid error.
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted …
=> fix(hub-common): fix undefined token when getting schedule

packages/common/src/events/api/orval/api/orval-events.ts
…dd entityIds and entityTypes to
1. Description: Updated `get-events-dto`'s parameters that are arrays based on enums to include their enum types …
=> fix(hub-common): get-events dto enum array types

packages/common/src/core/traits/ICapabilityConfig.ts, packages/common/src/sites/_internal/getPropertyMap.ts
Small changes to enable prototyping of capability config …
=> fix: add content to site propertyMap, allow more props on ICapabilityConfig

packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/types/Permission.ts
Removes hub:feature:gallery:map permission policy in preparation to ungate the gallery map layout option on /search.
ISSUES CLOSED: 10118
Removes permission policy …
=> feat(hub-common): removes hub:feature:gallery:map permission policy

packages/common/src/events/api/orval/api/orval-events.ts
…dd entityIds and entityTypes to
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release instructions …
=> fix(hub-common): get events by groupid types

package-lock.json, packages/common/src/search/wellKnownCatalog.ts
1. Description: Adds a new projectAndInitiative collection …
=> feat: add projectAndInitiative as a new collection

packages/common/src/initiative-templates/_internal/InitiativeTemplateBusinessRules.ts, packages/common/src/templates/_internal/TemplateBusinessRules.ts
[10435](https://devtopia.esri.com/dc/hub/issues/10435)
- removed `alpha` gating from initiative templates
- removed `alpha` gating from solution templates  …
=> fix: remove alpha gating from templates

packages/common/src/content/_internal/ContentUiSchemaSettings.ts, packages/common/test/content/_internal/ContentUiSchemaSettings.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/10170
=> feat(hub-common): show disabled scheduler setting with advisory notice for private items

packages/sites/src/drafts/page-draft-include-list.ts, packages/sites/src/drafts/site-draft-include-list.ts
1. Description: Removes most props from site and page draft whitelists. …
=> feat: remove props from site and page draft whitelists

packages/common/src/core/types/IHubSite.ts, packages/common/src/sites/_internal/computeProps.ts, packages/common/src/sites/_internal/getPropertyMap.ts
1. Description: Adds the isHubHome prop so we can determine if a site is an org site or not.
1. Closes Issues: #10379 …
=> feat(hub-common): add isHubHome prop

packages/common/src/events/_internal/EventSchemaEdit.ts, packages/common/src/events/_internal/EventUiSchemaEdit.ts, packages/common/test/events/_internal/EventSchemaEdit.test.ts, packages/common/test/events/_internal/EventUiSchemaEdit.test.ts
1. Description: Removes minimum start date so that past events can be edited.
1. Closes Issues: #10549 …
=> fix(hub-common): enable editing for past events

packages/common/src/templates/_internal/TemplateBusinessRules.ts
[10489](https://devtopia.esri.com/dc/hub/issues/10489)
Remove the `entityOwner` check from the `hub:template:workspace:settings` permission …
=> fix: remove entityOwner check from template settings permission

package-lock.json, packages/common/src/objects/deepFilter.ts, packages/common/test/objects/deepFilter.test.ts
1. Description: Resolves issue where deepFilter was traversing into Blobs and clearing out the stuff we'd want to keep in a Blob. …
=> fix: deepFilter allows for blobs to pass through

package-lock.json, packages/common/src/ArcGISContext.ts, packages/common/src/associations/wellKnownAssociationCatalogs.ts, packages/common/src/search/_internal/buildCatalog.ts, packages/common/src/search/wellKnownCatalog.ts, packages/common/test/ArcGISContextManager.test.ts, packages/common/test/associations/wellKnownAssociationCatalogs.test.ts, packages/common/test/search/wellKnownCatalog.test.ts
1. Description: Adds a partners case to wellKnownItemCatalog and uses it over in getAvailableToRequestAssociationCatalogs …
=> feat: add a partners case to well known item catalog

packages/common/src/core/schemas/types.ts
Adds the `conditions` field to `IUiSchemaRule` to allow for multiple conditions on a rule as well as simple booleans as a possible condition.
1. Closes Issues: [#10480](https://zentopia.esri.com/workspaces/sprint-board-60340b9721bc3a4ab6367db5/issues/gh/dc/hub/10480)
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to …
=> feat(): update IUiSchemaRule def

packages/common/src/surveys/_internal/computeProps.ts, packages/common/src/surveys/utils/get-form-json.ts, packages/common/src/surveys/utils/index.ts, packages/common/src/surveys/utils/is-draft.ts, packages/common/test/surveys/_internal/computeProps.test.ts, packages/common/test/surveys/utils/get-form-json.test.ts, packages/common/test/surveys/utils/is-draft.test.ts, packages/common/test/surveys/utils/is-survey123-connect.test.ts, packages/surveys/src/utils/index.ts, packages/surveys/src/utils/is-published.ts, packages/surveys/test/utils/is-published.test.ts
1. Description: Fixes bug where survey workspace would fail to open for draft surveys.
1. Closes Issues: #10594 …
=> fix(hub-common): survey workspace handles draft surveys

packages/common/src/events/HubEvent.ts, packages/common/test/events/HubEvent.test.ts
1. Description: Events can be viewed by anon user
1. Closes Issues: #9320
=> fix(hub-common): events can be viewed by anon user

packages/common/src/core/schemas/types.ts
[9417](https://devtopia.esri.com/dc/hub/issues/9417)
add `rules` to `IUiSchemaElement` and add note to deprecate `rule` …
=> feat: update IUiSchemaElement interface to include rules

packages/common/src/events/api/orval/api/orval-events.ts
1. Description: Add new filter parameter `canEdit` to `GetEventsParams` …
=> fix(hub-common): add canEdit to GetEventsParams

package-lock.json, packages/common/src/permissions/HubPermissionPolicies.ts
1. Description: opens hub:feature:user:preferences to production.
1. Closes Issues: [8858](https://devtopia.esri.com/dc/hub/issues/8858) …
=> feat: expose hub:feature:user:preferences to production

package-lock.json, packages/common/src/sites/_internal/_migrate-link-underlines-capability.ts, packages/common/src/sites/index.ts, packages/common/src/sites/upgrade-site-schema.ts, packages/common/test/sites/_internal/_migrate-link-underlines-capability.test.ts, packages/common/test/sites/upgrade-site-schema.test.ts
ISSUES CLOSED: 10599
1. Description: Removes underlindLinks capability
=> feat: remove underlinedLinks capability

packages/common/src/permissions/HubPermissionPolicies.ts
ISSUES CLOSED: 10750
1. Description: adds hub:feature:workspace:user permission to gate the user workspace
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release …
=> feat: hub:feature:workspace:user permission

packages/common/src/core/schemas/internal/getEditorSchemas.ts, packages/common/src/core/schemas/internal/metrics/InitiativeUiSchemaMetrics.ts, packages/common/src/core/schemas/internal/metrics/ProjectUiSchemaMetrics.ts, packages/common/test/core/schemas/internal/metrics/InitiativeUiSchemaMetrics.test.ts, packages/common/test/core/schemas/internal/metrics/ProjectUiSchemaMetrics.test.ts
=> feat(): add buildDefaults for metrics

packages/common/src/permissions/types/Permission.ts
ISSUES CLOSED: 10750
1. Description: Actually exposes hub:feature:workspace:user
=> fix: actually makes hub:feature:workspace:user a valid permission

packages/common/src/content/fetch.ts, packages/common/test/content/fetch.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/10523. Prevents errors from being thrown when trying to fetch enrichments for hub content. This is important as many items in ArcGIS online reference servers that are non-operational.
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ …
=> fix(hub-common): swallow errors when trying to fetch enrichments in fetchHubContent

packages/common/test/projects/_internal/ProjectUiSchemaSettings.test.ts
1. Description: PR just to trigger release via semantic commit message …
=> feat(hub-common): release project map settings

packages/common/src/content/_internal/ContentUiSchemaEdit.ts, packages/common/src/core/schemas/internal/fetchCategoriesUiSchemaElement.ts, packages/common/src/core/schemas/internal/fetchCategoryItems.ts, packages/common/src/core/schemas/types.ts, packages/common/src/discussions/_internal/DiscussionUiSchemaEdit.ts, packages/common/src/events/_internal/EventUiSchemaEdit.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts, packages/common/src/pages/_internal/PageUiSchemaEdit.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts, packages/common/src/sites/_internal/SiteUiSchemaEdit.ts, packages/common/src/surveys/_internal/SurveyUiSchemaEdit.ts, packages/common/test/content/_internal/ContentUiSchemaEdit.test.ts, packages/common/test/core/schemas/internal/fetchCategoriesUiSchemaElement.test.ts, packages/common/test/core/schemas/internal/fetchCategoryItems.test.ts, packages/common/test/discussions/_internal/DiscussionUiSchemaEdit.test.ts, packages/common/test/events/_internal/EventUiSchemaEdit.test.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts, packages/common/test/pages/_internal/PageUiSchemaEdit.test.ts, packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts, packages/common/test/sites/_internal/SiteUiSchemaEdit.test.ts, packages/common/test/surveys/_internal/SurveyUiSchemaEdit.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/10382
Highlights:
- Abstracts the creation of the categories ui schema field into a helper function to maintain consistency.
- Adds a notice to all categories schema fields when no categories are available within the user's org
- Adds a `link` configuration object to `IUiSchemaMessage` that can only be used when rendering notices
=> feat(hub-common): disable categories field and provide notice when no options are available

package-lock.json, packages/common/src/discussions/_internal/DiscussionUiSchemaSettings.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaSettings.ts, packages/common/src/projects/_internal/ProjectUiSchemaSettings.ts, packages/common/test/discussions/_internal/DiscussionUiSchemaSettings.test.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaSettings.test.ts, packages/common/test/projects/_internal/ProjectUiSchemaSettings.test.ts
ISSUES CLOSED: #10461
1. Description: Adds map settings to Discussion Boards UI Schema …
=> feat(hub-common): adds map settings to discussion board settings schema

packages/common/src/core/schemas/internal/metrics/InitiativeUiSchemaMetrics.ts, packages/common/src/core/schemas/internal/metrics/ProjectUiSchemaMetrics.ts, packages/common/test/core/schemas/internal/metrics/InitiativeUiSchemaMetrics.test.ts, packages/common/test/core/schemas/internal/metrics/ProjectUiSchemaMetrics.test.ts
2. 
Removed sharing section on metric pane for initiative and project entities
1. Closes Issues: [10737](https://zentopia.esri.com/workspaces/sprint-board-60340b9721bc3a4ab6367db5/issues/gh/dc/hub/10737) …
=> feat: Removed sharing section on metric pane in initiative and project entities

packages/sites/src/create-site-model-from-template.ts, packages/sites/test/create-site-model-from-template.test.ts
[10005](https://devtopia.esri.com/dc/hub/issues/10005)
**BREAKING CHANGE**: removes logic to automatically create an initiative during the site creation process …
=> feat(hub-sites): initiatives are no longer created during site creation

package-lock.json, packages/common/src/projects/_internal/ProjectBusinessRules.ts
1. Description: hub:project:edit allowed on both prem and basic licenses …
=> fix: hub:project:edit allowed on both prem and basic licenses

package-lock.json, packages/common/src/projects/_internal/ProjectBusinessRules.ts
1. Description: Ungates the project workspace initiative association pane from qa …
=> feat: ungate project workspace initiatives association

packages/common/src/associations/internal/getIncludesAndReferencesQuery.ts, packages/common/test/associations/internal/getIncludesAndReferencesQuery.test.ts
[10863](https://devtopia.esri.com/dc/hub/issues/10863)
updates the `getIncludesAndReferencesQuery` to account for a parent that doesn't yet have an association group. In this case, no full associations could have been formed, and we should exit early with a `null` query. 
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ …
=> fix: getIncludesAndReferencesQuery accounts for no association group

packages/common/src/downloads/_internal/_types.ts, packages/common/src/downloads/_internal/format-fetchers/getCreateReplicaFormats.ts, packages/common/test/downloads/_internal/format-fetchers/getCreateReplicaFormats.test.ts
1. Description: Add KML format for create replica.
1. Closes Issues: #[10390](https://devtopia.esri.com/dc/hub/issues/10390) …
=> feat(hub-common): support KML format for create replica

packages/common/src/events/_internal/EventUiSchemaEdit.ts, packages/common/test/events/_internal/EventUiSchemaEdit.test.ts
ISSUES CLOSED: 10850
1. Closes Issues: #10850 …
=> fix(hub-common): event location picker uses all draw tools

packages/common/src/events/api/orval/api/orval-events.ts, packages/common/src/events/api/types.ts
1. Description: add registration count to `IEvent`
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section …
=> feat(hub-common): add IEventRegistrationCount to IEvent

packages/common/src/events/api/orval/api/orval-events.ts, packages/common/src/events/api/types.ts, packages/common/src/events/edit.ts, packages/common/test/events/api/registrations.test.ts, packages/common/test/events/edit.test.ts, packages/common/test/search/_internal/hubEventsHelpers/eventAttendeeToSearchResult.test.ts, packages/common/test/search/_internal/hubSearchEventAttendees.test.ts, packages/common/test/search/_internal/hubSearchEvents.test.ts
=> feat(hub-common): change public int ids to cuids

packages/common/src/downloads/_internal/_types.ts
1. Description: This PR changes the position of KML download button for updated download card as suggested [here](https://devtopia.esri.com/dc/hub/issues/10390#issuecomment-4874200).
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/10390 …
=> feat(hub-common): change order of download button for KML format

package-lock.json, packages/common/src/core/types/IHubEvent.ts, packages/common/src/events/_internal/PropertyMapper.ts, packages/common/src/events/_internal/getPropertyMap.ts, packages/common/test/events/_internal/PropertyMapper.test.ts
- Adds `inPersonCapacityType` to `IHubEvent` pojo …
=> fix(hub-common): add inPersonCapacityType to IHubEvent

packages/common/src/core/traits/IWithViewSettings.ts, packages/common/src/core/types/Embeds.ts, packages/common/src/core/types/index.ts
[10885](https://devtopia.esri.com/dc/hub/issues/10885)
Scaffolds a new `HubEmbed` type for use within the entity class system as well as our frontend view/configuration components …
=> feat: add embed types/interfaces

packages/common/src/events/api/orval/api/orval-events.ts
…dd entityIds and entityTypes to
1. Description: Allow filtering by `orgId` for `GET /events`
=> fix(hub-common): added orgId filter to GetEventsParams

packages/discussions/src/utils/reactions/can-create-reaction.ts, packages/discussions/test/utils/reactions/can-create-reaction.test.ts
1. Description: Revert breaking change
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the …
=> fix(hub-discussions): revert breaking change

package-lock.json, packages/discussions/src/utils/reactions/can-create-reaction.ts
adds user parameter to function canCreateReaction
ISSUES CLOSED: 10700 …
=> feat(hub-discussions): add user argument to canCreateReaction method

packages/common/src/groups/_internal/GroupSchema.ts, packages/common/src/groups/_internal/GroupUiSchemaCreate.ts, packages/common/src/groups/_internal/GroupUiSchemaCreateAssociation.ts, packages/common/src/groups/_internal/GroupUiSchemaCreateFollowers.ts, packages/common/src/groups/_internal/GroupUiSchemaSettings.ts, packages/common/test/groups/_internal/GroupUiSchemaCreate.test.ts, packages/common/test/groups/_internal/GroupUiSchemaCreateAssociation.test.ts, packages/common/test/groups/_internal/GroupUiSchemaCreateFollowers.test.ts, packages/common/test/groups/_internal/GroupUiSchemaSettings.test.ts
=> fix: update groups uiSchemas

packages/common/src/downloads/fetchDownloadFormats.ts, packages/common/src/downloads/types.ts, packages/common/test/downloads/fetchDownloadFormats.test.ts
- copy to opendata-ui w/ this PR: https://github.com/ArcGIS/opendata-ui/pull/13869
- visit this link: https://download-test-qa-pre-a-hub.hubqa.arcgis.com:4200/datasets/qa-pre-a-hub::qa-data-simple-point-100-hosted-service/about?pe=temp:hub:content:downloads:unifiedList
- open the download panel
- confirm the Data Source title is applied
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/10824
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release …
=> feat: extend static download formats to support additional resources

package-lock.json, package.json, packages/common/package.json
@esri/hub-common was missing a dependency on @types/arcgis-js-api which would cause build failures when used in a TS project
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/7246
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually …
=> fix(hub-common): hub-common missing @types/arcgis-js-api dependency

packages/common/src/events/_internal/EventSchemaEdit.ts, packages/common/src/events/_internal/EventUiSchemaEdit.ts, packages/common/test/events/_internal/EventSchemaEdit.test.ts, packages/common/test/events/_internal/EventUiSchemaEdit.test.ts
1. Description: Sets Events description prop to optional.
1. Closes Issues: #11034 …
=> feat(hub-common): set description to optional

package-lock.json, packages/common/src/core/types/IHubSite.ts, packages/common/src/groups/index.ts, packages/common/src/groups/isOpenDataGroup.ts, packages/common/src/sites/_internal/getPropertyMap.ts, packages/common/test/groups/isOpenDataGroup.test.ts
=> feat(hub-common): add HubSite.isUmbrella() and isOpenDataGroup()

packages/common/src/content/_internal/ContentUiSchemaEdit.ts, packages/common/src/core/schemas/internal/getThumbnailUiSchemaElement.ts, packages/common/src/discussions/_internal/DiscussionUiSchemaEdit.ts, packages/common/src/groups/_internal/GroupUiSchemaEdit.ts, packages/common/src/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.ts, packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts, packages/common/src/pages/_internal/PageUiSchemaEdit.ts, packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts, packages/common/src/sites/_internal/SiteUiSchemaEdit.ts, packages/common/src/surveys/_internal/SurveyUiSchemaEdit.ts, packages/common/src/templates/_internal/TemplateUiSchemaEdit.ts, packages/common/src/urls/get-cdn-asset-url.ts, packages/common/src/urls/index.ts, packages/common/test/content/_internal/ContentUiSchemaEdit.test.ts, packages/common/test/core/schemas/internal/getThumbnailUiSchemaElement.test.ts, packages/common/test/discussions/_internal/DiscussionUiSchemaEdit.test.ts, packages/common/test/groups/_internal/GroupUiSchemaEdit.test.ts, packages/common/test/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.test.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts, packages/common/test/mocks/mock-auth.ts, packages/common/test/pages/_internal/PageUiSchemaEdit.test.ts, packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts, packages/common/test/sites/_internal/SiteUiSchemaEdit.test.ts, packages/common/test/surveys/_internal/SurveyUiSchemaEdit.test.ts, packages/common/test/templates/_internal/TemplateUiSchemaEdit.test.ts, packages/common/test/urls/get-cdn-asset-url.test.ts
=> feat(hub-common): adds default thumbnail for discussions

packages/discussions/src/utils/channel-permission.ts, packages/discussions/src/utils/channels/can-modify-channel.ts, packages/discussions/test/utils/channel-permission.test.ts
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release instructions for …
=> feat(hub-discussions): add future v2 priv checks for updating channel

package-lock.json, packages/common/src/search/serializeQueryForPortal.ts, packages/common/test/search/serializeQueryForPortal.test.ts
Bug in `serializeMatchOptions` was found via hub-search system tests. Also added tests that verify the serialization permutations.
1. Closes Issues: n/a - reported by team members
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. …
=> fix: address invalid query serialization

packages/common/src/events/api/orval/api/orval-events.ts
=> feat(hub-common): add additional filters for fetching events

package-lock.json, packages/common/src/events/HubEvent.ts, packages/common/src/events/edit.ts, packages/common/test/events/HubEvent.test.ts, packages/common/test/events/edit.test.ts
1. Description: Adds deleteHubEvent function.
1. Closes Issues: #11053
=> feat(hub-common): add deleteHubEvent

packages/common/src/core/types/IHubCardViewModel.ts
1. Closes Issues: [9222](https://devtopia.esri.com/dc/hub/issues/9222) …
=> feat(hub-common): add optional ariaLabel to ICardAction link

package-lock.json, packages/sites/src/remove-site.ts
1. Description: Re-order requests in `removeSite`
1. Closes Issues: [11442](https://devtopia.esri.com/dc/hub/issues/11442), [10931](https://devtopia.esri.com/dc/hub/issues/10931) …
=> fix: re-order requests

packages/common/src/initiatives/_internal/InitiativeBusinessRules.ts, packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/types/Permission.ts, packages/common/src/projects/_internal/ProjectBusinessRules.ts
[11416](https://devtopia.esri.com/dc/hub/issues/11416)
- Adds a permission policy for configuring/viewing catalogs 
- Adds a business rule to projects for the catalogs pane
- Adds a business rule to initiatives for the catalogs pane
1. [x] used semantic commit messages 
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. …
=> feat: add catalogs permissions

packages/common/src/newsletters/api/orval/api/orval-newsletters.ts
=> feat(hub-common): add new fields for newsletter subscriptions

packages/common/src/core/getEntityGroups.ts, packages/common/src/events/HubEvent.ts, packages/common/src/events/getEventGroups.ts, packages/common/src/events/index.ts, packages/common/src/search/Catalog.ts, packages/common/src/utils/index.ts, packages/common/src/utils/is-cuid.ts, packages/common/test/core/getEntityGroups.test.ts, packages/common/test/events/HubEvent.test.ts, packages/common/test/events/_internal/getEventGroups.test.ts, packages/common/test/events/getEventGroups.test.ts, packages/common/test/utils/is-cuid.test.ts
=> feat(hub-common): add getCuid

packages/common/src/search/Catalog.ts, packages/common/test/search/Catalog.test.ts
[11435](https://devtopia.esri.com/dc/hub/issues/11435)
adds a new method, `addCollection` to the `Catalog` class …
=> feat: introduce addCollection method to Catalog class

packages/common/src/content/hostedServiceUtils.ts
- attempt to rectify changes from previous hub.js PR: https://github.com/Esri/hub.js/pull/1642
- validates that the service URL is not that of a secure proxy service
- if it is, don't show the hosted downloads badge!
- copy this to opendata-ui; run `yarn start:prod`
- test here: https://apierrortest-cantechsupport.hub.arcgis.com:4200/datasets/fc63ae8402054d5180587eeabe9022f1_0/explore?location=44.672990%2C-63.658450%2C12.66
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/11360
1. [x] PR title follows semantic …
=> fix: added util for confirming service is not secure proxy

packages/common/src/core/schemas/types.ts
1. Description: adds RESET uischema rule effect
=> feat: adds reset uischema rule effect

packages/common/src/downloads/_internal/file-url-fetchers/fetchHubApiDownloadFile.ts, packages/common/test/downloads/_internal/file-url-fetchers/fetchHubApiDownloadFile.test.ts
Bug: When there is no cache for a dataset whose service have editor tracking disabled and download is requested. Cache generation process is completed, a notice that "cache may be outdated" is present. This might be confusing to the user because user just finished generated a cache.  The notice is not expected immediately after cache generation.
This fixes the bug by pending `trackCacheUpdate` query params which contains the response to hide notice when download job is complete.
1. [ ] used semantic commit …
=> fix(hub-common): add trackCacheUpdate by default when polling download API

packages/common/src/core/types/IHubGroup.ts, packages/common/src/groups/_internal/GroupSchema.ts, packages/common/src/groups/_internal/GroupUiSchemaCreate.ts, packages/common/src/groups/_internal/convertHubGroupToGroup.ts, packages/common/src/groups/_internal/getPropertyMap.ts, packages/common/src/groups/getWellKnownGroup.ts, packages/common/src/permissions/PlatformPermissionPolicies.ts, packages/common/src/permissions/types/PlatformPrivilege.ts, packages/common/test/groups/_internal/GroupUiSchemaCreate.test.ts, packages/common/test/groups/_internal/convertHubGroupToGroup.test.ts
1. Description: Updates to group json schema and create group uiSchema.
1. Closes Issues: [#11368](https://devtopia.esri.com/dc/hub/issues/11368) …
=> feat: group schema and create group uischema

package-lock.json, packages/common/src/search/upgradeCatalogSchema.ts, packages/common/src/sites/_internal/applyCatalogStructureMigration.ts, packages/common/test/search/upgradeCatalogSchema.test.ts, packages/common/test/sites/_internal/applyCatalogStructureMigration.test.ts
ISSUES CLOSED: 11326
- Adds an `event` scope to catalogs in support of enforcing guards on the events3 view
1. Closes Issues: #[11326](https://devtopia.esri.com/dc/hub/issues/11326)
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our …
=> feat(hub-common): add event scope to catalog

packages/common/src/events/api/orval/api/orval-events.ts
1. Description: sharedToGroups filter added to the get-events-dto
=> fix(hub-common): added sharedToGroups filter for get-events

package-lock.json, packages/common/src/users/HubUser.ts, packages/common/src/users/_internal/UserUiSchemaSettings.ts, packages/common/src/utils/internal/updateCommunityOrgSettings.ts, packages/common/src/utils/internal/updatePortalOrgSettings.ts, packages/common/test/users/HubUser.test.ts, packages/common/test/users/_internal/UserUiSchemaSettings.test.ts, packages/common/test/utils/internal/updatePortalOrgSettings.test.ts
1. Description: Adds a showInfoBanner section to User Org Settings. Also adds the save logic. …
=> feat: showInfoBanner for user org settings

packages/common/e2e/catalog-collection-prod.e2e.ts, packages/common/e2e/deep-contains.e2e.ts, packages/common/e2e/hub-sites-contains.e2e.ts, packages/common/e2e/hub-sites.e2e.ts, packages/common/src/core/_internal/deepContains.ts, packages/common/src/core/deepCatalogContains.ts, packages/common/src/core/index.ts, packages/common/src/index.ts, packages/common/src/initiatives/_internal/applyInitiativeMigrations.ts, packages/common/src/search/types/types.ts, packages/common/src/sites/HubSite.ts, packages/common/test/core/_internal/deepContains.test.ts, packages/common/test/core/deepCatalogContains.test.ts, packages/common/test/initiatives/_internal/applyInitiativeMigrations.test.ts, packages/common/test/sites/HubSite.test.ts
export `deepCatalogContains` which delegates to existing internal `deepContains` after constructing the needed `IDeepCatalogInfo[]`
```
export async function deepCatalogContains(
identifier: string,  //id of entity to check is contained
hubEntityType: HubEntityType, // entity type (should be known b/c this will be called by routes)
path: string, // containment path, will be passed around app as query param
context: IArcGISContext,
rootCatalog?: IHubCatalog // typically the catalog for the current site
): Promise<IContainsResponse>
```
run unit tests
1. Part of Issues: 111767
1. [x] Updated meaningful TSDoc to methods including Parameters and Returns, see [Documentation Guide](https://esri.github.io/hub-components/storybook/?path=/story/guides-do …
=> feat: deepCatalogContains delegates to deepContains

packages/common/src/core/schemas/internal/events/EventGalleryCardUiSchema.ts, packages/common/test/core/schemas/internal/events/EventGalleryCardUiSchema.test.ts
=> feat(hub-common): reenable additional info

packages/common/src/core/schemas/shared/CatalogSchema.ts, packages/common/src/core/schemas/shared/index.ts, packages/common/src/search/types/IHubCatalog.ts, packages/common/src/types.ts
[11435](https://devtopia.esri.com/dc/hub/issues/11435)
- adds JSON schema definitions that map to the relevant `IHubCatalog` interfaces
- adds exported const of target entity types
- adds "Hub Project" to the exported enum of AGO item types …
=> feat: scaffold catalog configuration experience

packages/common/src/ArcGISContext.ts, packages/common/src/search/_internal/portalSearchGroups.ts, packages/common/test/ArcGISContextManager.test.ts
- Add `context.resourceGroupIds` pre-populated with group id's for PROD and QA
- Ensure `IHubSearchOptions.httpMethod` is respected in `portalSearchGroups` function
1. Related to Issues: #11602
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs …
=> feat: user overview resources

packages/common/src/content/_internal/ContentSchema.ts, packages/common/src/content/_internal/getDownloadsSection.ts, packages/common/test/content/_internal/ContentUiSchemaSettings.test.ts, packages/common/test/content/_internal/getDownloadsSection.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/11504
Changes the "extract" toggle in the content settings schema to be a "download system" tile select
=> feat(hub-common): change content settings schema's extract toggle to be a tile select

packages/common/src/content/_internal/ContentUiSchemaSettings.ts, packages/common/test/content/_internal/ContentUiSchemaSettings.test.ts
1. Description: switch scheduler to select format
1. Instructions for testing: copy this to the opendata-ui PR (https://github.com/ArcGIS/opendata-ui/pull/14125)
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/11446
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the …
=> feat: switch scheduler to select format

package-lock.json, packages/common/src/search/_internal/hubEventsHelpers/processFilters.ts, packages/common/test/search/_internal/hubEventsHelpers/processFilters.test.ts
=> feat: events processFilters support occurrence && group to sharedToGroup

packages/common/src/core/_internal/deepContains.ts, packages/common/src/core/index.ts, packages/common/src/core/parseContainmentPath.ts, packages/common/src/index.ts, packages/common/src/initiatives/_internal/getPropertyMap.ts, packages/common/src/search/Catalog.ts, packages/common/test/core/_internal/deepContains.test.ts, packages/common/test/core/parseContainmentPath.test.ts, packages/common/test/search/Catalog.test.ts
Four things:
- export `parseContainmentPath` from the library to apps can use it
- fix `Catalog.scopes` to return `{}` instead of `undefined` if `.scopes` is 🥁 `undefined`
- if present, `data.catalogs` should flow through to `IHubInitiative.catalogs`
- update `Catalog.contains` to handle cases where there is no `scope` for the targetEntity, and instead execute queries for all collections.
1. Connected to #11176
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic …
=> fix: small fixes for breadcrumbs and deep containment checks

packages/common/src/discussions/edit.ts, packages/common/src/initiative-templates/edit.ts, packages/common/src/initiatives/HubInitiatives.ts, packages/common/src/items/_internal/slugs.ts, packages/common/src/pages/HubPages.ts, packages/common/src/projects/edit.ts, packages/common/src/sites/HubSites.ts, packages/common/src/templates/edit.ts, packages/common/test/initiative-templates/edit.test.ts, packages/common/test/projects/edit.test.ts, packages/common/test/sites/HubSites.test.ts
1. Closes Issues: [9329](https://devtopia.esri.com/dc/hub/issues/9329) …
=> fix(hub-common): ensure entity slug is unique and typekeyword is in sync

packages/common/src/search/_internal/getWorkflowForType.ts, packages/common/test/search/_internal/getWorkflowForType.test.ts, packages/common/test/search/getAddContentConfig.test.ts
1. Description: [11507](https://devtopia.esri.com/dc/hub/issues/11507) prescribes the order of the create content menu items.
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section …
=> feat: prescribe order of add content config items

packages/common/src/discussions/api/types.ts
Issue: https://zentopia.esri.com/workspaces/sprint-board-60340b9721bc3a4ab6367db5/issues/gh/dc/hub/11614 …
=> feat(hub-discussions): add ChannelFilter to filter channels by disc uri

packages/common/src/discussions/api/types.ts, packages/discussions/src/utils/channel-permission.ts, packages/discussions/src/utils/channels/can-edit-channel.ts, packages/discussions/src/utils/channels/can-modify-channel.ts, packages/discussions/src/utils/channels/channel-to-dto-map.ts, packages/discussions/test/utils/channel-permission.test.ts, packages/discussions/test/utils/channels/can-edit-channel.test.ts
affects: @esri/hub-common, @esri/hub-discussions
validate channel property changes based on existing channel channelAcl roles
Issue [8522](https://devtopia.esri.com/dc/hub/issues/8522)
Issue [11010](https://devtopia.esri.com/dc/hub/issues/11010)
1. Description: add optional parameter `updateData` to `canEditChannel` (only used in V2 routes) and additional validation of the changed channel properties based on existing channelAcl roles: https://confluencewikidev.esri.com/pages/viewpage.action?pageId=153747776#Roles&Privileges-ApplicationtoChannels
1. [ ] Updated meaningful TSDoc to methods including Parameters and Returns, see [Documentation Guide](https://esri.github.io/hub-components/storybook/?path=/story/guides-doc …
=> feat(hub-discussions): channel edit optional update parameter for V2

packages/common/src/newsletters-scheduler/api/orval/api/orval-newsletters-scheduler.ts, packages/common/src/newsletters-scheduler/api/types.ts, packages/common/src/newsletters/api/orval/api/orval-newsletters.ts, packages/common/src/newsletters/api/types.ts, packages/common/test/newsletters-scheduler/api/subscriptions.test.ts
=> feat(hub-common): change subscription actions to singular action

packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/types/Permission.ts
- Limit `hub:feature:workspace:org` to devext so it's no longer the default in our alpha orgs (where we do most dev/test)
- add `hub:feature:inline-workspace` permission, limit to devext so we have to pass `?pe=hub:feature:inline-workspace`
1. Part of Issues: #11691
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to …
=> feat: add inline-workspace flag; limit workspace:org to devext

packages/common/src/content/_internal/ContentUiSchemaDiscussions.ts, packages/common/src/groups/_internal/GroupUiSchemaDiscussions.ts, packages/common/test/content/_internal/ContentUiSchemaDiscussions.test.ts, packages/common/test/groups/_internal/GroupUiSchemaDiscussions.test.ts
1. Description: Updates discussions pane to be more a11y-compliant.
1. Closes Issues: #11728, #11722 …
=> fix(hub-common): remove calcite-radio-group

packages/common/src/discussions/api/types.ts
1. Description: add `channelAcl` to enum `PostRelation` …
=> feat(hub-common): add channelAcl to PostRelation

packages/common/src/content/_internal/ContentBusinessRules.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts, packages/common/src/sites/feed-configuration.ts, packages/common/src/sites/feeds/_internal/defaults.ts, packages/common/src/sites/feeds/_internal/getMajorVersion.ts, packages/common/src/sites/feeds/defaults.ts, packages/common/src/sites/feeds/getFeedTemplate.ts, packages/common/src/sites/feeds/previewFeed.ts, packages/common/src/sites/feeds/setFeedTemplate.ts, packages/common/src/sites/feeds/types.ts, packages/common/src/sites/index.ts, packages/common/test/sites/feeds/_internal/getMajorVersion.test.ts, packages/common/test/sites/feeds/getFeedTemplate.test.ts, packages/common/test/sites/feeds/previewFeed.test.ts, packages/common/test/sites/feeds/setFeedTemplate.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/11611
Adds new helpers for managing feed configurations, such as
- getFeedTemplate()
- setFeedTemplate()
- previewFeedTemplate()
We want to use these new functions instead of the older `getFeedConfiguration()` and `setFeedConfiguration()` as we are moving more and more towards passing around HubEntity objects instead of IModel objects.
Also note, `getFeedTemplate()` will return the correct default template if none is configured. This was a change from `getFeedConfiguration()` …
=> feat(hub-common): add updated utils for managing and previewing feeds

packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/search/types/types.ts, packages/common/src/users/_internal/UserBusinessRules.ts
- add `"hub:user:workspace:events"` and `"hub:user:workspace:discussions"`
- re-enabled "workspace on org url" for QA Alpha orgs
- add `startDate` to `SortOptions`
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in …
=> fix: update permissions for user event and discussion pane

packages/common/src/search/utils.ts, packages/common/src/sites/HubSites.ts, packages/common/src/sites/_internal/_ensureLegacySiteCatalog.ts, packages/common/src/sites/_internal/convertCatalogToLegacyFormat.ts, packages/common/src/sites/upgrade-site-schema.ts, packages/common/test/sites/HubSites.test.ts, packages/common/test/sites/_internal/_ensureLegacySiteCatalog.test.ts, packages/common/test/sites/_internal/convertCatalogToLegacyFormat.test.ts, packages/common/test/sites/upgrade-site-schema.test.ts
When a Site was created via the HubSite class (via the `arcgis-hub-add-content` component), the item that was created had `.catalog` as an `IHubCatalog` _not_ the legacy format. This was due to small deviation between `.fromEditor(..)` and `.create(..)` logic. The fix was to ensure that we apply the same "migration" back to the legacy catalog in the "create" workflow that's applied in the "save" workflow.
1. Closes Issues: Bug found by Tom
1. [x] PR title follows semantic commit format (**CRITICAL** if the …
=> fix: ensure site created via HubSite class has correct catalog format

packages/common/src/discussions/api/types.ts, packages/discussions/test/utils/channel-permission.test.ts
Issue [10427](https://devtopia.esri.com/dc/hub/issues/10427)
Update interfaces for `IChannel`, `ICreateChannel`, `ICreateChannelSettings`, `ICreateChannelPermissions`, `IUpdateChannel`, `IUpdateChannelSettings`, `IUpdateChannelPermissions`
1. Description: Update the discussions interfaces for creating and updating channels for V2 release. Deprecate legacy channel sharing properties `access`, `groups`, `orgs`, `allowAnonymous` in favor of `channelAcl`
1. [ ] used semantic commit …
=> feat(hub-common): update discussions interfaces for V2 release

package-lock.json, packages/common/src/search/_internal/hubEventsHelpers/eventToSearchResult.ts, packages/common/test/search/_internal/hubEventsHelpers/eventToSearchResult.test.ts
1. Description: Makes getUser call optional when converting an event to search result to improve loading times.
1. Closes Issues: #11752 …
=> fix(hub-common): make getUser optional

packages/common/src/core/schemas/internal/metrics/InitiativeUiSchemaMetrics.ts, packages/common/src/core/schemas/internal/metrics/ProjectUiSchemaMetrics.ts, packages/common/src/core/schemas/internal/metrics/rules.ts, packages/common/src/initiatives/HubInitiative.ts, packages/common/src/initiatives/HubInitiatives.ts, packages/common/src/metrics/editorToMetric.ts, packages/common/src/metrics/index.ts, packages/common/src/metrics/metricToEditor.ts, packages/common/src/projects/HubProject.ts, packages/common/src/projects/edit.ts, packages/common/test/core/schemas/internal/metrics/ProjectUiSchemaMetrics.test.ts, packages/common/test/initiatives/HubInitiative.test.ts, packages/common/test/initiatives/HubInitiatives.test.ts, packages/common/test/metrics/editorToMetric.test.ts, packages/common/test/metrics/metricToEditor.test.ts, packages/common/test/projects/edit.test.ts
1. Description: Exposes the `editorToMetric` and `metricToEditor` functions for usage in front end with preview metric. 
1. Closes Issues: [#11855](https://zentopia.esri.com/workspaces/sprint-board-60340b9721bc3a4ab6367db5/issues/gh/dc/hub/11855) …
=> fix(): expose editor to metric functions

package-lock.json, packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/types/Permission.ts
=> feat(hub-common): add feature flag for site pages via catalog

packages/common/src/discussions/api/types.ts, packages/discussions/src/utils/channel-permission.ts, packages/discussions/src/utils/channels/can-post-to-channel.ts, packages/discussions/src/utils/posts/can-create-post.ts, packages/discussions/src/utils/posts/can-create-reply.ts, packages/discussions/src/utils/posts/can-edit-post.ts, packages/discussions/src/utils/posts/index.ts, packages/discussions/src/utils/reactions/can-create-reaction.ts, packages/discussions/test/utils/posts/can-create-post.test.ts, packages/discussions/test/utils/posts/can-create-reply.test.ts, packages/discussions/test/utils/posts/can-edit-post.test.ts
Issue [11879](https://devtopia.esri.com/dc/hub/issues/11879)
1. Description: Add new property `allowPost` to `IChannel` and `ICreateChannelSettings`. Add create new util functions `canCreatePost` and `canCreateReply`. Modify the `canEditPost` util function to also check channel properties `allowPost` or `allowReply`, dependent on whether the post is a post or a reply (has a `parentId`)
1. [ ] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the …
=> feat(hub-discussions): canEditPost is a breaking change until prod migrations are unblocked

packages/common/src/discussions/api/types.ts, packages/discussions/src/types.ts
Related Issue: [11813](https://zentopia.esri.com/workspaces/sprint-board-60340b9721bc3a4ab6367db5/issues/gh/dc/hub/11813)
1. Description: Added `f` query parameter to `ISearchPosts` and  `SearchPostsFormat` enum for its type.
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update …
=> feat(hub-discussions): added enum and parameter for downloading posts as csv

packages/common/src/pages/HubPages.ts, packages/common/src/pages/_internal/computeLinks.ts, packages/common/src/pages/_internal/computeProps.ts, packages/common/test/pages/_internal/computeProps.test.ts
1. Description: hub page entities and search results now have links.workspaceRelative and links.layoutRelative; hub site entities and search results have correct workspaceRelative link.
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/11674, https://devtopia.esri.com/dc/hub/issues/11874
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated …
=> feat: hub page layoutRelative and workspaceRelative links

package-lock.json, packages/common/src/discussions/api/types.ts
ISSUES CLOSED: 11042
- Adds `IExportPostsParams` interface to `hub-common`
1. Closes Issues: #[11042](https://devtopia.esri.com/dc/hub/issues/11042)
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the …
=> feat(hub-common): add IExportPostsParams interface

packages/common/src/search/_internal/portalSearchGroups.ts, packages/common/src/search/_internal/portalSearchItems.ts, packages/common/src/search/_internal/portalSearchUsers.ts, packages/common/src/search/explainQueryResult.ts, packages/common/src/search/types/IHubSearchResponse.ts, packages/common/src/search/types/types.ts, packages/common/src/search/utils.ts, packages/common/test/search/utils.test.ts
1. Description: Adds an optional `executedQueryLength: Kilobyte (number)` to the `IHubSearchResponse` object to allow for calculating the size of a query. 
1. Closes Issues: [#11590](https://zentopia.esri.com/workspaces/sprint-board-60340b9721bc3a4ab6367db5/issues/gh/dc/hub/11590)
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to …
=> feat(): add executed query length to search response

package-lock.json, packages/common/src/core/schemas/internal/getEditorSchemas.ts, packages/common/src/events/_internal/EventBusinessRules.ts, packages/common/src/events/_internal/EventSchemaCreate.ts
* Renames `hub:event:workspace:attendees` permission to `hub:event:workspace:registrants`
* Renames `hub:event:attendees` schema to `hub:event:registrants`
1. Closes Issues: #[11557](https://devtopia.esri.com/dc/hub/issues/11557)
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ …
=> fix(hub-common): rename hub:event:workspace:attendees permission

package-lock.json, packages/common/src/items/_internal/slugs.ts, packages/common/src/items/fetch.ts, packages/common/src/items/index.ts, packages/common/src/pages/HubPages.ts, packages/common/src/pages/_internal/computeProps.ts, packages/common/test/items/_internal/slug.test.ts, packages/common/test/items/fetch.test.ts, packages/common/test/pages/HubPages.test.ts
- adds `fetchItem()` which:
- uses a new internal `parseIdentifier()` to parse the id or slug out of the identifier
- allows callers to pass in the site's org key as a fallback for slugs w/o an org key prefix
- encapsulates the logic for calling the appropriate function to fetch via id or slug
- `fetchPage()` now defers to `fetchItem()` to handle all the above (we will do the same for other item-backed entities in a future PR)
1. [x] PR title follows semantic commit format …
=> feat(hub-common): add fetchItem and call it from fetchPage

packages/common/src/discussions/api/types.ts
1. Description: add `allowPost` to `IChannel` and `ICreateChannelSettings` …
=> feat(hub-common): add allowPost to IChannel and ICreateChannelSettings

package-lock.json, packages/common/src/discussions/api/types.ts, packages/discussions/package.json, packages/discussions/src/utils/posts/can-create-post.ts, packages/discussions/src/utils/posts/can-create-reply.ts, packages/discussions/src/utils/posts/can-edit-post.ts, packages/discussions/src/utils/posts/index.ts, packages/discussions/src/utils/reactions/can-create-reaction.ts, packages/discussions/test/utils/posts/can-create-post.test.ts, packages/discussions/test/utils/posts/can-create-reply.test.ts, packages/discussions/test/utils/posts/can-edit-post.test.ts
1. Description: Add new util functions `canCreatePost` and `canCreateReply`. Modify the `canEditPost` util function to also check channel properties `allowPost` or `allowReply`, dependent on whether the post is a post or a reply (has a `parentId`) …
=> feat(hub-common): add allowPost to IChannel

packages/common/src/discussions/api/types.ts
Issue [11951](https://devtopia.esri.com/dc/hub/issues/11951)
1. Description: Change `ISearchChannels` interface `orgId` => `orgIds`. (Verified Hub and Urban not using) …
=> fix(hub-common): modify ISearchCHannels interface orgId => orgIds

package-lock.json, packages/common/src/core/_internal/computeItemLinks.ts, packages/common/src/items/_internal/slugConverters.ts, packages/common/src/items/_internal/slugs.ts, packages/common/src/items/getItemIdentifier.ts, packages/common/src/pages/_internal/computeLinks.ts, packages/common/test/items/getItemIdentifier.test.ts
and use it to inject slug into site relative URLs for pages …
=> feat(hub-common): add optional includeIdInSlug arg to getItemIdentifier

packages/common/src/core/schemas/types.ts, packages/common/src/sites/_internal/SiteUiSchemaSettings.ts, packages/common/test/sites/_internal/SiteuUiSchemaSettings.test.ts
Updates the `IChangeEventDetail` type to have `required: Set<string>` on it, meaning the currently required properties in the editor.
1. Closes Issues: [#11605](https://zentopia.esri.com/workspaces/sprint-board-60340b9721bc3a4ab6367db5/issues/gh/dc/hub/11605)
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update …
=> fix(): add required type to IChangeEventDetail

package-lock.json, packages/common/src/users/_internal/UserUiSchemaSettings.ts, packages/common/test/users/_internal/UserUiSchemaSettings.test.ts
1. Description: `arcgis-hub-notices` adds launch icons at the end of links by default as requested by design -- so we can remove these pre-pended launch icons that were duplicated
**before**
**after**
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/11884 …
=> fix: removing extra launch icons on user settings

packages/common/src/initiatives/_internal/InitiativeBusinessRules.ts, packages/common/src/projects/_internal/ProjectBusinessRules.ts
Adds the singular catalog permission to projects and initiatives, so that we can later remove the plural catalogs permission after switching the ui over to use the singular permission. 
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we …
=> fix(): add catalog permission

packages/common/src/sites/_internal/SiteBusinessRules.ts
Part of https://devtopia.esri.com/dc/hub/issues/11047
DO NOT MERGE until the functionality this ungates has been verified
=> feat(hub-common): replace temporary workspace feeds permission with hub:site:workspace:feeds

packages/common/src/sites/HubSite.ts, packages/common/src/sites/_internal/SiteSchema.ts, packages/common/src/sites/_internal/SiteUiSchemaCreate.ts, packages/common/test/sites/HubSite.test.ts, packages/common/test/sites/_internal/SiteUiSchemaCreate.test.ts
1. Description: add domain to site creation uiSchema
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/11365
1. [X] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the …
=> feat: adds domain to site creation uiSchema

packages/common/src/core/schemas/shared/CatalogSchema.ts
Updates the catalog schemas to include appearance settings. …
=> fix: update correct schemas for catalog editing

packages/sites/src/index.ts
Export `_get-sharing-eligible-models` so we can use `_getSharingEligibleModels` in solutions service …
=> fix: export _get-sharing-eligible-models

packages/common/src/sites/_internal/SiteSchema.ts
1. Description: Adds format to subdomain of site schema.
1. Closes Issues: [#<number> (if appropriate)](https://devtopia.esri.com/dc/hub/issues/11365) …
=> fix: add format for subdomain field

packages/common/src/discussions/api/types.ts, packages/discussions/src/posts/posts.ts, packages/discussions/test/posts.test.ts
Issue: https://devtopia.esri.com/dc/hub/issues/12176
1. Description: The discussions API added a new route `POST /posts/search`. Use this route for searching and downloading posts. Since this route accepts a POST body, `geometry` and `featureGeometry` parameters no longer to be stringified
1. [ ] …
=> fix(hub-discussions): use POST /posts/search to search and export posts

packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/types/Permission.ts
Part of https://devtopia.esri.com/dc/hub/issues/12248, adds a permission that limits advanced catalog configuration for sites.
=> feat(hub-common): add hub:feature:catalogs:edit:advanced permission for controlling catalog editing

packages/common/src/sites/feeds/_internal/defaults.ts, packages/common/src/sites/feeds/getFeedTemplate.ts, packages/common/test/sites/feeds/getFeedTemplate.test.ts
1. Description: This PR updates `spatial` field of default DCAT US feed template to use default transformer `computeSpatialProperty` with `extent` value. [`computeSpatialProperty`](https://github.com/ArcGIS/hub-feeds-api/blob/main/src/default-feed-templates/dcat-us/template-transforms.js#L164-L189) computes valid value from extent so should be used with `extent` by default.
1. Closes Issues: [#12271]( https://devtopia.esri.com/dc/hub/issues/12271)
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a …
=> fix(hub-common): update spatial element from default dcat us template

packages/common/src/search/_internal/hubEventsHelpers/getUniquePredicateValuesByKey.ts, packages/common/src/search/_internal/hubEventsHelpers/processFilters.ts, packages/common/src/search/_internal/hubEventsHelpers/processOptions.ts, packages/common/src/search/_internal/hubEventsHelpers/toEnumConverters.ts, packages/common/src/search/_internal/hubSearchEvents.ts, packages/common/test/search/_internal/hubEventsHelpers/processFilters.test.ts, packages/common/test/search/_internal/hubEventsHelpers/processOptions.test.ts, packages/common/test/search/_internal/hubEventsHelpers/toEnumConverters.test.ts, packages/common/test/search/_internal/hubSearchEvents.test.ts
https://devtopia.esri.com/dc/hub/issues/12274
1. Description: In `hubSearchEvents`, swap `getEvents` with `searchEvents`. This function points to the new POST /events/search route. Update the process filter and options functions for the new interface (remove parsing to string)
1. [ ] updated `peerDependencies` as needed. …
=> feat(hub-common): hubSearchEvents switch to new POST events search route

packages/common/src/urls/getContentHomeUrl.ts, packages/common/src/urls/index.ts, packages/common/test/urls/getContentHomeUrl.test.ts
1. Description: Adds content home url util.
1. Closes Issues: #11979
=> feat(hub-common): add content home url util

packages/common/README.md, packages/discussions/README.md
1. Description: Force publish after rebase …
=> fix(hub-discussions): publish after rebase

packages/common/src/events/api/events.ts, packages/common/test/discussions/api/discussions-api-request.test.ts, packages/discussions/src/posts/posts.ts
1. Description: Force `next` version and publish after rebase …
=> Force publish 2/5

packages/common/src/discussions/api/types.ts
1. Description: Comment tweak for ICreatePost interface …
=> fix(hub-common): update ICreatePost comment

package-lock.json, packages/common/src/discussions/api/types.ts
1. Description: Fix package-lock after rebase
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the …
=> fix(hub-common): fix package-lock

packages/common/src/discussions/api/channels/channels.ts, packages/common/src/discussions/api/discussions-api-request.ts, packages/common/src/discussions/api/settings/settings.ts, packages/common/src/discussions/api/types.ts, packages/common/src/discussions/api/utils/request.ts, packages/common/test/discussions/api/channels.test.ts, packages/common/test/discussions/api/discussions-api-request.test.ts, packages/common/test/discussions/api/settings.test.ts
Issue [12460](https://devtopia.esri.com/dc/hub/issues/12460)
`hub-common` (all non-breaking changes):
Added types:
- `ICreateChannelParamsV2`
- `ICreateChannelPermissionsV2`
- `ICreateChannelSettingsV2`
- `ICreateChannelV2`
- `IUpdateChannelParamsV2`
- `IUpdateChannelPermissionsV2`
- `IUpdateChannelSettingsV2`
- `IUpdateChannelV2`
- `ICreatePostParamsV2`
Added route functions:
- `discussionsApiRequestV2` // called only within V2 route functions
- `searchChannelsV2`
- `createSettingV2`
- `fetchSettingV2`
- `updateSettingV2`
- `removeSettingV2`
Modified functions:
- `apiRequest` // called from discussionsApiRequestV2, discussionsApiRequest. Version passed as an argument
---
1. Description: Completely separate discussions V1 and V2 interfaces and route …
=> feat(hub-common): add new v2 discussions interfaces and functions

packages/common/src/core/schemas/shared/CatalogSchema.ts, packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/projects/_internal/ProjectBusinessRules.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts, packages/common/src/sites/_internal/applyDefaultCollectionMigration.ts, packages/common/src/sites/defaultSiteCollectionKeys.ts, packages/common/src/sites/index.ts
[12246](https://devtopia.esri.com/dc/hub/issues/12246)
- add/update permissions for site catalogs
- export default site collection keys to be used by catalog builder
- temporarily remove `minItems` requirement in filters schema
1. [x] used semantic commit messages  …
=> feat: add logic/permissions to enable site catalog config in new UI

packages/common/src/search/Catalog.ts, packages/common/test/search/Catalog.test.ts
[12246](https://devtopia.esri.com/dc/hub/issues/12246)
=> fix: account for empty collection filters when merging with scope filters

packages/common/src/core/schemas/shared/subschemas.ts
1. Description: add maxItems to ENTITY_CATEGORIES_SCHEMA
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/12257 …
=> fix: add maxItems to ENTITY_CATEGORIES_SCHEMA

package-lock.json, packages/common/src/ArcGISContextManager.ts, packages/common/src/types/IArcGISContextManagerOptions.ts, packages/common/src/utils/IHubConfig.ts, packages/common/src/utils/LogLevel.ts, packages/common/src/utils/index.ts, packages/common/src/utils/internal/config.ts, packages/common/src/utils/logger.ts
Issue: https://devtopia.esri.com/dc/hub/issues/10713
Adds `globalThis.arcgisHubConfig` to enable consumers to configure Hub.js before using it. It currently has one setting: `logLevel`, ex:
```js
// in application initialization
const logLevel = isProduction ? 'error' : 'debug'
globalThis.arcgisHubConfig = { logLevel }
// start using Hub.js
```
See https://devtopia.esri.com/dc/hub/issues/10713#issuecomment-5337749 for more details. …
=> feat(hub-common): add arcgisHubConfig global variable

docs/src/guides/functional/discussions-v2.md, jasmine.json, packages/common/src/discussions/api/utils/channel-permission.ts, packages/common/src/discussions/api/utils/channels/can-delete-channel-v2.ts, packages/common/test/discussions/api/utils/channel-permission.test.ts, packages/common/test/discussions/api/utils/channels/can-delete-channel-v2.test.ts
Issue [12475](https://devtopia.esri.com/dc/hub/issues/12475)
1. Description: Modify the v2 channel delete permissions check to verify user is org_admin or owner within the defined channelAcl …
=> feat(hub-common): restrict v2 channel delete to org admins or channel permission OWNER roles

packages/common/src/core/schemas/shared/CatalogSchema.ts, packages/common/src/search/Catalog.ts, packages/common/src/search/types/IHubCatalog.ts, packages/common/test/search/Catalog.test.ts
[12663](https://devtopia.esri.com/dc/hub/issues/12663)
- adds `sort` and `filters` to the `GalleryDisplayConfigSchema`
- adds `displayConfig` to `CollectionSchema`
- fix catalog `displayConfig` interface and schema
- Note: it appears that at some point (presumably, when the UI got refactored), we started persisting the top-level catalog `displayConfig` by `targetEntity`. This was never updated in the interface or schema.
1. …
=> fix: add displayConfig to CollectionSchema

package-lock.json, packages/common/src/search/types/IHubCatalog.ts, packages/common/src/sites/_internal/applyDefaultCollectionMigration.ts, packages/common/src/sites/_internal/reflectCollectionsToSearchCategories.ts, packages/common/test/sites/HubSites.test.ts, packages/common/test/sites/_internal/applyDefaultCollectionMigration.test.ts, packages/common/test/sites/_internal/reflectCollectionsToSearchCategories.test.ts, packages/common/test/sites/get-catalog-from-site-model.test.ts
1. Description: related opendata-ui PR: https://github.com/ArcGIS/opendata-ui/pull/14552
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/12610
opendata-ui PR: https://github.com/ArcGIS/opendata-ui/pull/14552
Testing site: https://rochester-moose-qa-pre-a-hub.hubqa.arcgis.com/workspace/sites/8e67c41951804ef9965e290b3d83c182/details?uiVersion=PR-14552
1. [x] updated `peerDependencies` as …
=> fix(hub-common): site collections not hidden properly

packages/common/src/core/schemas/shared/CatalogSchema.ts
[12620](https://devtopia.esri.com/dc/hub/issues/12620)
Update catalog schemas to require at least 1 filter and predicate …
=> fix: update schemas to require catalog scope

packages/common/src/core/schemas/shared/CatalogSchema.ts
[12620](https://devtopia.esri.com/dc/hub/issues/12620)
adds `minProperties` to the `FilterSchema` and `PredicateSchema` for accurate validation in the UI:
- `minProperties` on the `PredicateSchema` provides validation against a config like:
```ts
{
scopes: {
[targetEntity]: {
filters: [ { predicates: [ {} ] } ]
}
}
}
```
- `minProperties` on the `FilterSchema` provides validation against a config like: 
```ts
{
scopes: {
[targetEntity]: {
filters: [ {} ]
}
}
}
```
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic …
=> fix: add minProperties validation to catalog schemas

package-lock.json, package.json
=> chore: fix lint-staged tslint command

package-lock.json, packages/common/test/ArcGISContextManager.test.ts, packages/common/test/content/edit.test.ts, packages/common/test/search/_internal/hubSearchItems.test.ts, packages/common/test/sites/test-helpers.test.ts, packages/downloads/test/poll-download-metadata.test.ts, packages/downloads/test/portal/portal-export-success-handler.test.ts, packages/downloads/test/portal/portal-get-exports-folder-id.test.ts, packages/downloads/test/portal/portal-poll-export-job-status.test.ts, packages/downloads/test/portal/portal-request-dataset-export.test.ts, packages/downloads/test/portal/portal-request-download-metadata.test.ts, packages/downloads/test/request-dataset-export.test.ts, packages/downloads/test/request-download-metadata.test.ts, packages/events/test/register.test.ts, packages/events/test/util.test.ts, packages/sites/test/_update-pages.test.ts, packages/sites/test/get-members.test.ts, packages/sites/test/layout/remove-unused-resources.test.ts, packages/sites/test/link-site-and-page.test.ts, packages/sites/test/test-helpers.test.ts, packages/sites/test/unlink-site-and-page.test.ts, packages/teams/test/create-hub-team.test.ts, packages/teams/test/create-hub-teams.test.ts, packages/teams/test/remove-team-from-items.test.ts, packages/teams/test/remove-team.test.ts, packages/teams/test/update-user-membership.test.ts, packages/teams/test/utils/can-user-create-team.test.ts, packages/teams/test/utils/get-team-by-id.test.ts, packages/teams/test/utils/get-team-members.test.ts, packages/teams/test/utils/search-team-members.test.ts
Removes all use of `UserSession` (except one test that mocks the static `UserSession.completeOAuth2`) from tests.
This will make the transition to REST JS 4 easier.
If build passes, merge.
1. addresses Issues: #<number> (if appropriate)
https://devtopia.esri.com/dc/hub/issues/10768
n/a
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can …
=> chore(hub-common): remove use of UserSession in tests

packages/common/test/groups/add-users-workflow/fixtures.ts, packages/common/test/mocks/mock-auth.ts, packages/common/test/search/utils.test.ts, packages/common/test/test-helpers/fake-user-session.ts, packages/downloads/test/portal/portal-request-download-metadata.test.ts, packages/initiatives/test/mocks/fake-session.ts, packages/initiatives/test/model.test.ts, packages/initiatives/test/update-initiative-site-id.test.ts, packages/teams/test/fixtures.ts
affects: @esri/hub-common, @esri/hub-downloads, @esri/hub-initiatives, @esri/hub-teams …
=> chore(hub-common): remove more uses of UserSession in tests

packages/common/src/search/_internal/hubSearchItemsHelpers/getFieldsQueryParam.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/getFilterQueryParam.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/getFlattenQueryParam.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/getOgcItemQueryParams.ts, packages/common/test/search/_internal/hubSearchItems.test.ts
1. Description: This PR adds `flatten` and `fields` as valid OGC query params in hubSearch(). OGC Search API supports `flatten` query param to include layers items in result and `fields` query param to include only specific fields in response.
1. Closes Issues: [#12300 ](https://devtopia.esri.com/dc/hub/issues/12300)
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release …
=> feat(hub-common): support flatten and fields predicates in hubSearch()

packages/common/src/discussions/api/types.ts
1. Description: Add optional filter parameter `notIds` to discussions service `ISearchChannels` interface …
=> feat(hub-common): add optional param notIds to ISearchChannels

packages/common/src/sites/_internal/applyDefaultCollectionMigration.ts
forcing major release of previous changes
=> feat(hub-common): trigger major version release

packages/common/src/sites/_internal/SiteBusinessRules.ts
Tightens up licensing restrictions for editing the event scope for site catalogs
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release instructions …
=> fix(hub-common): update "hub:site:workspace:catalog:events" permission to include license checks

package-lock.json, packages/common/src/core/schemas/shared/CatalogSchema.ts
=> fix(): removed unused layout options in catalog schema

packages/common/src/core/schemas/shared/CatalogSchema.ts
Forcing a release from from #1851 
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section …
=> fix: removed unused layout options in catalog schema 

package-lock.json, packages/common/src/core/schemas/internal/discussions/EntityUiSchemaDiscussionsSettings.ts, packages/common/src/core/schemas/internal/getEditorSchemas.ts, packages/common/src/discussions/_internal/DiscussionBusinessRules.ts, packages/common/src/discussions/_internal/DiscussionSchema.ts, packages/common/src/discussions/_internal/DiscussionUiSchemaSettings.ts, packages/common/src/discussions/edit.ts, packages/common/src/search/_internal/hubDiscussionsHelpers/channelResultsToSearchResults.ts, packages/common/src/search/_internal/hubDiscussionsHelpers/processChannelFilters.ts, packages/common/src/search/_internal/hubDiscussionsHelpers/processChannelOptions.ts, packages/common/src/search/_internal/hubSearchChannels.ts, packages/common/src/users/_internal/UserBusinessRules.ts, packages/common/src/utils/_array.ts, packages/common/src/utils/batch.ts, packages/common/test/core/schemas/internal/discussions/EntityUiSchemaDiscussionsSettings.test.ts, packages/common/test/core/schemas/internal/getEditorSchemas.test.ts, packages/common/test/discussions/HubDiscussion.test.ts, packages/common/test/discussions/_internal/DiscussionUiSchemaSettings.test.ts, packages/common/test/discussions/edit.test.ts, packages/common/test/discussions/utils.test.ts, packages/common/test/search/_internal/hubDiscussionsHelpers/channelResultsToSearchResults.test.ts, packages/common/test/search/_internal/hubDiscussionsHelpers/processChannelFilters.test.ts, packages/common/test/search/_internal/hubDiscussionsHelpers/processChannelOptions.test.ts, packages/common/test/search/_internal/hubSearchChannels.test.ts, packages/common/test/utils/_array.test.ts
ISSUES CLOSED: 12668
- Adds a reusable entity discussion settings schema
- Hooks up the reusable entity discussion settings schema for discussion boards
- Refactors the hub channel search logic to significantly reduce the number of XHRs needed to fetch the group enrichments
- Adds support for `id` and `notId` channel search API params, integrates into `hubSearch` using `id: string | string[] | { not: string | string[] }` syntax
1. Closes Issues: #12668
1. [x] PR title follows semantic commit …
=> feat(hub-common): add entity discussion settings ui schema

packages/common/src/initiatives/_internal/InitiativeBusinessRules.ts, packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/projects/_internal/ProjectBusinessRules.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts
[12770](https://devtopia.esri.com/dc/hub/issues/12770)
adds premium gating to the "hub:feature:catalogs:edit:advanced" permission …
=> feat: add hub-premium gating to hub:feature:catalogs:edit:advanced permission

packages/common/src/sites/_internal/SiteBusinessRules.ts
- [12770](https://devtopia.esri.com/dc/hub/issues/12770)
Gate the events catalog pane in the site workspace to premium users, but we can't use the `"hub:feature:catalogs:edit:advanced"` permission because it currently has an assertion for sites …
=> fix: site event catalog gating

package-lock.json, packages/common/src/sites/_internal/handleDomainChanges.ts, packages/common/test/sites/_internal/handleDomainChanges.test.ts
1. Description: Prevents inadvertant domain deletion when the org-short is uppercase (and thus the `defaultHostname` has uppercase characters.
2. 
=> fix: case insensitive subdomain comparison

packages/common/src/core/schemas/index.ts, packages/common/src/search/wellKnownCatalog.ts, packages/common/test/search/wellKnownCatalog.test.ts
- [12732](https://devtopia.esri.com/dc/hub/issues/12732)
- adds new well-known group & event catalogs
- groups: "myGroups", "orgGroups", "communityGroups", "publicGroups"
- events: "myEvents", "orgEvents", "worldEvents"
- adds a new `getWellKnownCatalogs` util which returns an array of requested well-known catalogs
- exports internal `getTagItems` util
1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated …
=> feat: add well-known group and event catalogs

.github/workflows/publish-pr-preview.yaml
ISSUES CLOSED: 11743
Updates CI to generate PR-Previews for PRs configured to merge to branches that _are not_ `master`.
1. Closes Issues: #[11743](https://devtopia.esri.com/dc/hub/issues/11743) …
=> chore: generate pr previews for all prs

packages/common/src/org/fetch-org.ts, packages/common/src/urls/getPortalBaseFromOrgUrl.ts, packages/common/test/org/fetch-org.test.ts, packages/common/test/urls/getPortalBaseFromOrgUrl.test.ts
Resolves a bug with `fetchOrg` and `getPortalBaseFromOrgUrl` functions, which did not quite work as expected in Enterprise.
- run tests …
=> [PORTAL-11.5] fix: ensure fetchOrg works on enterprise

package-lock.json, packages/common/src/core/schemas/internal/getThumbnailUiSchemaElement.ts, packages/common/test/content/_internal/ContentUiSchemaEdit.test.ts, packages/common/test/core/schemas/internal/getThumbnailUiSchemaElement.test.ts, packages/common/test/discussions/_internal/DiscussionUiSchemaEdit.test.ts, packages/common/test/events/_internal/EventUiSchemaEdit.test.ts, packages/common/test/groups/_internal/GroupUiSchemaEdit.test.ts, packages/common/test/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.test.ts, packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts, packages/common/test/pages/_internal/PageUiSchemaEdit.test.ts, packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts, packages/common/test/sites/_internal/SiteUiSchemaEdit.test.ts, packages/common/test/surveys/_internal/SurveyUiSchemaEdit.test.ts, packages/common/test/templates/_internal/TemplateUiSchemaEdit.test.ts
1. Description: Minor style changes and element reordering in the image picker used in workspaces
- open the details page in workspaces for site or other entities that use it
- notice should now appear between the helper text and thumbnail in the image picker section
- spacing between helperText, thumbnail, and dropdown below thumbnail should all be 10px apart.
1. Closes Issues: https://devtopia.esri.com/dc/hub/issues/13051
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the …
=> feat: moving notice into image picker

packages/common/src/events/api/events.ts, packages/common/src/events/api/orval/api/orval-events.ts, packages/common/src/events/api/types.ts, packages/common/src/search/_internal/commonHelpers/getApi.ts, packages/common/test/events/api/events.test.ts, packages/common/test/search/_internal/hubSearchEventAttendees.test.ts
1. Description: orval update for the deprecations of `GET /events` from the events api. An earlier ticket refactored hub search to use `searchEvents` instead
[Related hub-engagement pr](https://github.com/ArcGIS/hub-engagement/pull/214)
1. Issue: #12232 (https://zentopia.esri.com/workspaces/sprint-board-60340b9721bc3a4ab6367db5/issues/gh/dc/hub/12232) …
=> feat(hub-common): deprecate GET /events

packages/common/src/associations/getAvailableToRequestEntitiesQuery.ts, packages/common/src/associations/internal/getIncludesAndReferencesQuery.ts, packages/common/src/associations/internal/getIncludesDoesNotReferenceQuery.ts, packages/common/src/associations/internal/getReferencesDoesNotIncludeQuery.ts, packages/common/src/core/schemas/shared/CatalogSchema.ts, packages/common/src/initiatives/HubInitiatives.ts, packages/common/src/metrics/resolveMetric.ts, packages/common/src/search/combineQueries.ts, packages/common/src/search/index.ts, packages/common/src/search/types/IHubCatalog.ts, packages/common/src/utils/internal/resolveItemQueryValues.ts, packages/common/test/search/combineQueries.test.ts
- [12732](https://devtopia.esri.com/dc/hub/issues/12732)
- expose and export the `combineQueries` util for consumption in `opendata-ui`
- additions to `IGalleryDisplayConfig` and `GalleryDisplayConfigSchema` for `layouts` and `imageType`  …
=> feat: additions to gallery display config interface & schema

packages/common/src/discussions/api/types.ts
Allow optional channel acl id to be passed in on channel update
1. Description: add interface `IChannelAclUpdateDefinition`, used on channel update. This interface allows an optional `id` property, if passing in existing channel acls
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can …
=> feat(hub-common): add interface IChannelAclUpdateDefinition

packages/common/src/items/_internal/ensureUniqueEntitySlug.ts, packages/common/src/items/fetch.ts, packages/common/test/discussions/edit.test.ts, packages/common/test/initiative-templates/edit.test.ts, packages/common/test/initiatives/HubInitiatives.test.ts, packages/common/test/items/fetch.test.ts, packages/common/test/pages/HubPages.test.ts, packages/common/test/projects/edit.test.ts, packages/common/test/sites/HubSites.test.ts
1. Description: properly prefix slug with orgUrlKey; fallback to looking for items with slug typeKeyword lacking orgUrlKey prefix. Previously, in most cases, we augmented the user provided slug with the orgUrlKey. However in the case where a developer sets the entity slug to just the slug like 'my-slug' and then calls updatePage, the slug would be stored without the orgUrlKey prefix. I was doing that when migrating pages. So we have some pages stored with typeKeywords like `slug|some-slug` when they should have been `slug|org-url-key|some-slug` this caused us to break routing to pages by slug. This does two things:
a. Prefix the slug with the orgUrlKey in all cases.
b. Fall back to searching for pages by `typekewords: 'slug|some-slug'` if we don't find one with …
=> fix: page slugs

packages/common/src/sites/_internal/SiteBusinessRules.ts
part of [12251](https://devtopia.esri.com/dc/hub/issues/12251)
=> feat(hub-common): ungate the hub:site:workspace:catalog permission, remove deprecated hub:site:workspace:content permission

package-lock.json, packages/initiatives/src/migrations/upgrade-one-dot-one.ts, packages/initiatives/test/upgrades/upgrade-one-dot-one.test.ts
affects: @esri/hub-initiatives
ISSUES CLOSED: 13097 …
=> fix: guard against undefined data.values when setting bannerImage in upgradeToOneDotOne fn

packages/common/src/permissions/checkPermission.ts
1. Description: Reinstates logging of `checkPermission` failures via `Logger`.
=> feat: log checkpermission failures with Logger

packages/common/src/events/_internal/EventBusinessRules.ts
1. Description: Ungates events from alpha orgs. **Events will still only be accessible on QA.**
1. Closes Issues: none. …
=> feat(hub-common): ungate events from alpha

packages/common/src/core/schemas/internal/addDynamicSlugValidation.ts, packages/common/src/core/schemas/internal/metrics/editorToEntity.ts, packages/common/src/core/schemas/shared/subschemas.ts, packages/common/test/core/schemas/internal/addDynamicSlugValidation.test.ts
ISSUES CLOSED: 13184
Update slug validation logic so it allows an empty value for the slug field …
=> fix: configuration editor now allows an empty value for the slug field

jasmine.json, packages/common/src/events/api/orval/api/orval-events.ts, packages/common/src/search/_internal/hubEventsHelpers/processFilters.ts, packages/common/src/search/_internal/hubSearchEvents.ts, packages/common/test/search/_internal/hubEventsHelpers/processFilters.test.ts
1. Description: add optional `notEventIds` filter to `ISearchEvents` interface. Also update the events search filter processing logic for `id` property to handle object with not …
=> feat(hub-common): add notIds to interface ISearchEvents

packages/common/src/events/_internal/PropertyMapper.ts, packages/common/test/events/_internal/PropertyMapper.test.ts
1. Description: Events run catalog schema migrations.
1. Closes Issues: #13328 …
=> fix(hub-common): events have migrated catalog

.eslintrc.js, docs/src/guides/advanced/permissions.md, package-lock.json, packages/common/src/ArcGISContext.ts, packages/common/src/ArcGISContextManager.ts, packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/checkPermission.ts, packages/common/src/users/_internal/UserSchema.ts, packages/common/src/users/_internal/UserUiSchemaSettings.ts, packages/common/src/utils/IUserHubSettings.ts, packages/common/src/utils/hasOwnProperty.ts, packages/common/src/utils/hubUserAppResources.ts, packages/common/src/utils/internal/fetchAndMigrateUserHubSettings.ts, packages/common/src/utils/internal/siteSettingsMigrations.ts, packages/common/src/utils/internal/userAppResources.ts, packages/common/test/ArcGISContext.test.ts, packages/common/test/ArcGISContextManager.test.ts, packages/common/test/mocks/mock-auth.ts, packages/common/test/permissions/checkPermission.test.ts, packages/common/test/users/HubUser.test.ts, packages/common/test/users/_internal/UserUiSchemaSettings.test.ts, packages/common/test/utils/hubUserAppResources.test.ts, packages/common/test/utils/internal/siteSettingsMigrations.test.ts, tsconfig.json
***NOTE*** This needs to be merged with related changes in `opendata-ui`.
- swap from `IUserHubSettings.preview` to `IUserHubSettings.features` to allow both opt-in and opt-out
- migrates existing hub user app resources to this structure, preserving existing settings
- add "gating" permissions to enable formal release of a feature
- `hub:gating:workspace:released` which is a dependency of `hub:feature:workspace`
- update permissions guide
1. Part of Issues: [11970](https://devtopia.esri.com/dc/hub/issues/11970)
1. [x] used semantic commit …
=> [WIP] feat: opt-in/out of hub features and clean release permissions

packages/common/src/ArcGISContextManager.ts, packages/common/src/permissions/HubPermissionPolicies.ts
Ensure workspace permissions cascade as expected
`hub:feature:workspace:user -> hub:feature:workspace -> hub:gating:workspace:released`
When a user opts-out of workspace, `hub:feature:workspace` will be `false` 
1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to …
=> fix: workspace permission update

packages/common/src/ArcGISContextManager.ts, packages/common/src/core/_internal/getEditorSlug.ts, packages/common/src/core/schemas/internal/addDynamicSlugValidation.ts, packages/common/src/core/schemas/internal/metrics/editorToEntity.ts, packages/common/src/discussions/_internal/DiscussionBusinessRules.ts, packages/common/src/groups/_internal/GroupBusinessRules.ts, packages/common/src/items/_internal/slugs.ts, packages/common/src/items/slugs.ts, packages/common/src/pages/HubPage.ts, packages/common/src/sites/HubSites.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts, packages/common/src/users/_internal/UserBusinessRules.ts, packages/common/test/core/schemas/internal/addDynamicSlugValidation.test.ts, packages/common/test/items/_internal/slug.test.ts, packages/common/test/items/slugs.test.ts, packages/common/test/mocks/mock-auth.ts, packages/common/test/pages/HubPage.test.ts, packages/common/test/projects/edit.test.ts, packages/common/test/sites/HubSites.test.ts, packages/sites/test/create-site.test.ts
- export the service status const's for use in -ui
- update workspace:discussion permissions to depend on the discussion service
- gate user:workspace:settings to not enterprise b/c there's only Hub settings present
- fix issues with slug handling in enterprise where `portal.urlKey` is `undefined`; tldr; we handle that by defaulting to `""` for that value
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the …
=> feat: update permissions and slugs

packages/common/src/discussions/api/types.ts
1. Description: add roles to interface `ISearchChannels` …
=> feat(hub-common): add roles to interface ISearchChannels

packages/common/src/discussions/api/types.ts
**Related Issue**: [13549](https://zentopia.esri.com/workspaces/sprint-board-60340b9721bc3a4ab6367db5/issues/gh/dc/hub/13549) …
=> fix(hub-common): discussion post channelId not optional

packages/common/src/groups/_internal/GroupBusinessRules.ts
Added the permission policy for the group events workspace pane …
=> feat(hub-common): add group events workspace permission policy

packages/common/src/search/upgradeCatalogSchema.ts, packages/common/src/sites/_internal/applyCatalogStructureMigration.ts, packages/common/test/search/upgradeCatalogSchema.test.ts, packages/common/test/sites/_internal/applyCatalogStructureMigration.test.ts
Discovered while working on https://devtopia.esri.com/dc/hub/issues/13501
Ports over a temp fix that lived in opendata-ui …
=> fix(hub-common): fix issue where org home sites didn't have default group and user catalog scopes

packages/common/src/discussions/api/types.ts
Description: new relation `replyCount` for discussion api
Related Issue: [2746](https://zentopia.esri.com/workspaces/sprint-board-60340b9721bc3a4ab6367db5/issues/gh/dc/hub/2746) …
=> feat(hub-common): 2746 new relation replyCount discussion post query

package-lock.json, packages/common/src/ArcGISContext.ts, packages/common/src/ArcGISContextManager.ts, packages/common/src/assistants/IHubAssistant.ts, packages/common/src/core/schemas/internal/getEditorSchemas.ts, packages/common/src/core/schemas/shared/HubItemEntitySchema.ts, packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/types/Permission.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts, packages/common/src/sites/_internal/SiteSchema.ts, packages/common/src/sites/_internal/SiteUiSchemaAssistant.ts, packages/common/src/sites/defaults.ts, packages/common/src/types/IArcGISContext.ts, packages/common/src/types/IArcGISContextManagerOptions.ts, packages/common/src/types/IArcGISContextOptions.ts, packages/common/test/ArcGISContext.test.ts, packages/common/test/ArcGISContextManager.test.ts, packages/common/test/content/HubContent.test.ts, packages/common/test/core/schemas/internal/getEditorSchemas.test.ts, packages/common/test/sites/HubSite.test.ts, packages/common/test/sites/_internal/SiteUiSchemaAssistant.test.ts
1. Description: This PR adds the JSON Schema and permissions needed to configure an AI assistant on a Hub Site. See issue [13265](https://devtopia.esri.com/dc/hub/issues/13265), [13264](https://devtopia.esri.com/dc/hub/issues/13264) and `opendata-ui` PR [here](https://github.com/ArcGIS/opendata-ui/pull/14972) 
1. Instructions for testing: The above PR is dependent on these changes and can be tested with the new UI it provides.
1. Closes Issues: # [13264](https://devtopia.esri.com/dc/hub/issues/13264)
1. [ ] PR title follows semantic commit format (**CRITICAL** if …
=> Feat(hub-common): assistant configuration schemas

packages/common/src/sites/_internal/SiteUiSchemaAssistant.ts
=> fix: add comment in site ai assistant schema

packages/common/src/users/_internal/UserUiSchemaSettings.ts, packages/common/test/users/_internal/UserUiSchemaSettings.test.ts
[13587](https://devtopia.esri.com/dc/hub/issues/13587)
Remove `/organization` from the href construction - this route is only accessible to admins of the corresponding organization which is causing a redirect …
=> fix: community org AGO url

package-lock.json, packages/common/src/ArcGISContextManager.ts, packages/common/src/core/types/ISystemStatus.ts, packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/test/groups/getWellKnownGroup.test.ts, packages/common/test/mocks/mock-auth.ts
1. Description: This allows checkPermission() to return true on production if the two assertions are met. …
=> feat(hub-common): add service to platform AI permission check

packages/common/src/initiatives/_internal/InitiativeBusinessRules.ts, packages/common/src/permissions/HubPermissionPolicies.ts, packages/common/src/permissions/types/Permission.ts
- Adds a new temporary permission (`"hub:feature:catalogs:edit:appearance"`) to gate catalog/collection appearance configuration to qa premium alpha organizations
- adds deprecation notice to unused `"hub:feature:catalogs"` permission …
=> feat: add permission for catalog appearance

package-lock.json, packages/common/src/sites/HubSites.ts, packages/common/src/sites/_internal/subdomains.ts, packages/common/src/sites/domains/_lookup-portal.ts, packages/common/test/sites/HubSites.test.ts
After updating a site slug in enterprise, the URL, subdomain and related type keyword were not being updated. This caused the "View Site" button to have the incorrect URL.
Only wa to test is via portal-proxy
1. Closes Issues: [13723](https://devtopia.esri.com/dc/hub/issues/13723)
1. [x] updated `peerDependencies` as needed. **CRITICAL** our …
=> fix(hub-common): site subdomain not kept in sync w slug in enterprise

package-lock.json, packages/common/src/core/schemas/shared/subschemas.ts, packages/common/src/initiatives/_internal/applyInitiativeMigrations.ts, packages/common/src/initiatives/_internal/migrateInvalidTimelineStages.ts, packages/common/src/initiatives/defaults.ts, packages/common/src/projects/_internal/applyProjectMigrations.ts, packages/common/src/projects/_internal/migrateInvalidTimelineStages.ts, packages/common/src/projects/defaults.ts, packages/common/test/initiatives/_internal/applyInitiativeMigrations.test.ts, packages/common/test/initiatives/_internal/migrateInvalidTimelineStages.test.ts, packages/common/test/projects/_internal/applyProjectMigrations.test.ts, packages/common/test/projects/_internal/migrateInvalidTimelineStages.test.ts
1. Description: Updates json schema for timelines.
1. Closes Issues: [13754](https://devtopia.esri.com/dc/hub/issues/13754)
1. [X] Updated meaningful TSDoc to methods including Parameters and Returns, see [Documentation Guide](https://friendly-adventure-7w1eyl2.pages.github.io/storybook/?path=/story/guides-documentation--page) …
=> fix: make stage title required, migrate invalid stages

packages/common/src/core/schemas/internal/getEditorSchemas.ts, packages/common/src/core/schemas/shared/subschemas.ts, packages/common/src/sites/_internal/SiteSchema.ts, packages/common/test/core/schemas/getEditorConfig.test.ts
1. Description: Limit maxLength of site name to 240 characters in enterprise. In enterprise we look up the domain by the site name on a typekeyword prefixed with `hubsubdomain|` which is 13 characters long. So that 13 characters plus the length of the title if it _was_ 250 (and remains 250 in online) would give you a typekeword of 263 characters which is longer than the max length of a typekeyword (256).
1. Closes Issues: [13863](https://devtopia.esri.com/dc/hub/issues/13863)
1. [X] Updated meaningful TSDoc to methods including Parameters and Returns, see [Documentation Guide](https://friendly-adventure-7w1eyl2.pages.github.io/storybook/?path=/story/guides-documentation--page)
1. [X] PR title follows semantic commit format …
=> fix: limit maxLength of site name to 240 characters in enterprise

packages/common/src/core/_internal/createOrUpdateEntitySettings.ts, packages/common/src/groups/HubGroups.ts, packages/common/src/groups/_internal/computeProps.ts, packages/common/src/groups/_internal/convertGroupToHubGroup.ts, packages/common/src/initiatives/HubInitiative.ts, packages/common/test/groups/_internal/computeProps.test.ts, packages/common/test/groups/_internal/convertGroupToHubGroup.test.ts
1. Description: 
1. Closes Issues: #15155
***CRITICAL** 
If you …
=> fix(hub-common): fix create group discussion settings

packages/common/src/groups/getWellKnownGroup.ts, packages/common/test/groups/_internal/GroupUiSchemaCreate.test.ts, packages/common/test/groups/_internal/GroupUiSchemaCreateAssociation.test.ts, packages/common/test/groups/_internal/GroupUiSchemaCreateEdit.test.ts, packages/common/test/groups/_internal/GroupUiSchemaCreateFollowers.test.ts, packages/common/test/groups/_internal/GroupUiSchemaCreateView.test.ts, packages/common/test/groups/_internal/computeProps.test.ts, packages/common/test/groups/_internal/convertGroupToHubGroup.test.ts, packages/common/test/groups/getWellKnownGroup.test.ts
1. Closes Issues: #14097
1. [x] Updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release instructions for more details.
1. [x] These changes …
=> fix(hub-common): partial groups have group typing

packages/common/src/content/_internal/ContentBusinessRules.ts, packages/common/src/permissions/types/Permission.ts, packages/common/test/permissions/HubPermissionPolicies.test.ts
`hub:gating:workspace:released` was not in the `HubPermissionPolicies` array and thus was returning `invalid-permission` when checked. Happily this was not impacting the UX because the code path was only hit by anon users, who don't have access to workspaces so it was ok that the permission check failed.
This PR does add a test which verifies that all defined permission policies have valid permission values in them, as a means of ensuring that this does not happen again
1. Closes Issues: #14102
1. …
=> fix: ensure all permissions are in HubPermissions array

packages/common/src/core/types/IHubSite.ts, packages/common/src/sites/_internal/SiteBusinessRules.ts, packages/common/src/sites/_internal/SitePermissions.ts, packages/common/src/sites/_internal/computeProps.ts, packages/common/test/sites/_internal/computeProps.test.ts
Part of https://devtopia.esri.com/dc/hub/issues/13505.
adds and populates isCatalogV1Enabled field on IHubSite interface. Only applies for fetching the site, no update logic is currently available.
1. [x] These changes have been verified by QA using a `?uiVersion` that includes a PR-Preview of this branch and the `v_req` label has been applied to the issue.
1. [x] OD-UI …
=> feat(hub-common): add / populate IHubSite.isCatalogV1Enabled while fetching

packages/common/src/search/_internal/hubSearchItemsHelpers/getOgcAggregationQueryParams.ts, packages/common/src/search/_internal/hubSearchItemsHelpers/getQQueryParam.ts, packages/common/test/search/_internal/hubSearchItems.test.ts
added `q` and `bbox` to IOgcAggregationQueryParams to support dynamic aggregation of facets on map and search term filters
1. Closes Issues: [12416](https://devtopia.esri.com/dc/hub/issues/12416)
1. [x] Updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we …
=> feat(hub-common): added q and bbox to IOgcAggregationQueryParams

.github/workflows/deploy-docs.yml, .github/workflows/publish-pr-preview.yaml, .github/workflows/pull-request-tests.yml, .github/workflows/release.yml
Stuff I missed from #2014 
This PR updates all GitHub workflow files to standardize on Node.js version 18, removing older version configurations and npm 7 setup steps that are no longer necessary.
- Updates Node.js versions across all workflows from various versions (12, 14, 16) to 18
- Removes npm 7 installation steps since npm workspaces are natively supported in Node 18
- Simplifies workflow configurations by removing outdated version compatibility code
1. [ ] Updated meaningful TSDoc to methods including Parameters and Returns, see [Documentation Guide](https://friendly-adventure-7w1eyl2.pages.github.io/storybook/?path=/story/guides-documentation--page)
1. [ ] …
=> chore: update all workflows to use node 18
